### ISSUE TITLE
Cannot "Join as group" to battlegrounds when in a crossfaction group.

### ISSUE THREAD

**Issue by evilbeaverface** [RetroWoW/RetroWoW#1]
**Description**: When leading a group with members of both factions and the player speaks to a battleground battle master they cannot "Join as group"

**Current behavior**: same as above

**Expected behavior**: When leading a group with members of both factions and the player speaks to a battleground battle master they **can** "Join as group"

**Steps to reproduce the problem**:

1. invite someone to a group or raid from the opposite faction to your character
2. speak to a battle master
3. click "Join as group"

**Source:** Me. IGN: Banality, Ironically, Ironicly, Unironically, Unironicly, Tankservice, Marxian, Uniconically, Platitudes. Everyone in game is complaining about this in the world channel and so is everyone on discord. Please fix this asap! <3

**Comment by MrKelzo** [comment]
Fixed, will be pushed next restart
