### ISSUE TITLE
unable to receive the donated gold

### ISSUE THREAD

**Issue by wmh5196** [RetroWoW/RetroWoW#1]
**Description**: 20000 gold was bugged and lost

**Current behavior**: I opened the gold letter sent from system when I was lagged, however, I did not receive the 20000 gold I should have take.

**Expected behavior**:  return 20 dp to me, or 20000gold to character hknol

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

![image](https://user-images.githubusercontent.com/121515389/209709182-30a44f81-cb99-445f-9105-562bf24f99d5.png)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Hello, looks like you received the gold token already, check your bags for "Gold Token 20k" with this icon;

![image](https://user-images.githubusercontent.com/25086832/209799418-7bbd030f-a1ef-4dd3-913c-0ed4806ada50.png)
