### ISSUE TITLE
Seal of Command hits too hard

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#100]
**Description**: Per the tooltip, the damage from the proc should be 70% of weapon damage.  Currently it hits for a considerable amount MORE than weapon damage.

**Current behaviour**: Deals more than weapon damage

**Expected behaviour**: Should deal less than weapon damage

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
Item tooltip, character screen and:

https://youtu.be/f6SPpRZmuBU?t=10m40s

@10:44 in the video he gets the referenced crit vs a tauren warrior.

Note in that video that he has AQ40/Naxx gear (including the fabled Might of Menethil!), he has vengeance, crusader judgement AND berserking and he crits for 2200.  On live servers it is possible to get 2200 dmg crits with those same buffs/debuffs WITHOUT berserking

**Comment by xiaoxoxo** [comment]
Keep in mind, most paladins here wear full ap gear, paladin in video uses t2.5 which has far less ap.

**Comment by Phocus26** [comment]
regardless of what their AP is, they should not be doing more than weapon damage.  They should be doing 30% less.

**Comment by Bam27** [comment]
Insufficient source. 

Damage is scaling as it should as far as the staff and developers know. (I know, I have been testing paladins' damage scaling for a long time now.)

Can you provide a more accurate parse from source and control conditions? Everything I have tested lines up with what damage is possible for paladins for 1.12

**Comment by Phocus26** [comment]
https://youtu.be/6oiIy5j5oUA?t=5m57s

If you look at the damage against a cloth wearing class, the proc and white hits are pretty close to the same, that's how it should be.  70% wep dmg as sp dmg should be close to a white hit vs cloth (they have around 25% dmg reduction).

Testing on my paladin now using a weapon with very consistent damage: 

You hit Training Dummy for 362
Your Seal of Command hits Training Dummy for 433 Holy damage

This test was done with 2h weapon specialization talent (20/0/31 talents) and without sanctity aura on and no judgements or debuffs were applied to the dummy.

**Comment by modnaros** [comment]
Quoted from http://web.archive.org/web/20061110225913/http://forums.worldofwarcraft.com/thread.html?topicId=11381284&sid=1

Seal of Command does its holy damage based on what your weapon output is: SoC DPS = (Avg. Weapon Hit x .70) / 8.5 Seal of Command does have a +spell power coeficent (29%), but if you are a retribution paladin, then you will most likely want to forgo large amounts of +spell power for AP and melee crit. Judgement of Command and Righteousness both benefit from +spell power a lot more (43% and 50%, respectively) so if you plan to be judging either a lot, you may want to pick up a little +spell power.
