### ISSUE TITLE
bullets, my only wekaness..

### ISSUE THREAD

**Issue by Studabb** [RetroWoW/RetroWoW#100]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by Studabb** [comment]
Projectiles are bought at x1 instead of x200 i'm considering outing myself because of this ty - P.S, I'm a virgin

**Comment by MrKelzo** [comment]
Hello which item?
