### ISSUE TITLE
Attacks that miss or are immune do not put players in combat

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#101]
**Description**: If you miss an auto attack or are immune to an attack against you, you will not be put in combat.

**Current behaviour**: If you miss an auto attack or are immune to an attack against you, you will not be put in combat.

**Expected behaviour**: Any hostile action taken against a player should put you in combat.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
https://youtu.be/Kr_inDkNPBQ?t=22m53s

Note that he doesn't drop combat while bubble+hearthing; currently paladins are bubbling and mounting on live servers.

**Comment by Phocus26** [comment]
https://youtu.be/zgbPO4lkmNo?t=5m43s

A miss, resist, immune, ect.. should also pull players out of stealth.

**Comment by MrKelzo** [comment]
Spells are removing stealth now when you go in stealth while the caster is casting on you.
