### ISSUE TITLE
Boots of the Full Moon

### ISSUE THREAD

**Issue by skunkin** [RetroWoW/RetroWoW#101]
**Description**:
These boots used to be in the darnassus/org mall "boots 2" vendor. All vendors were taken away after the core release. Also.... all items in the vendors that have a <random enchantment> are bugged. When you buy the item no random enchantment gets added and it is stat-less.
**Current behavior**: Tell us what happens
Can you add these boots to the boots vendor. Item from dire maul - used to be in the vendors.
**Expected behavior**: Tell us what should happen instead
Boots of the Full Moon in the Boots vendor
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
"all items in the vendors that have a are bugged" What are you even talking about? They are all fine.
"Boots 2" vendor is removed a long time ago. Some items from it are added into the other NPC.

**Comment by skunkin** [comment]
The boots 2 vendor was in the darnassus and orgrimmar malls until those
vendors were removed when the new core launched. I was asking if the item I
mentioned could be added to the boots vendor in the Hyjal mall. I would
often buy said boots from the city malls and have them on a lot of my
characters.
Also, what I meant was every item in the mall vendors that sell items with
a "Random enchant",  which is a lot of them, are bugged. It is supposed to
add a random enchant, (i.e +10 stamina +10 agility) but it doesnt. It
simply only includes the automatic stats and not the random ones. Why would
I take time to make an account and figure out how to use this site if the
bug I was explaining wasnt imminent. My thread was closed without an
explanation or description of why either of the issues I brought up were
taken away/not working.
