### ISSUE TITLE
HS cd bug

### ISSUE THREAD

**Issue by YokujinKaze** [RetroWoW/RetroWoW#102]
**Description**:
HS gets sometimes 5min or 60 min cd
**Current behavior**: Tell us what happens
switches between custom and original cd

**Steps to reproduce the problem**:

1. use HS
2. get 5 mins OR 60 min cs
3. wait

**Include Screenshots from the issue if necessary**:
http://prntscr.com/k5cjfy

**Comment by MrKelzo** [comment]
This is not a bug, close your game and remove your wdb folder (cache)
