### ISSUE TITLE
Long duration CC appears too reliable

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#103]
**Description**: It appears that the heartbeat checks on long duration CC are not working properly any longer.  For example, freezing trap used to usually break randomly between 8 and 15 seconds as long as you have the trap mastery talent.  Now it always lasts 15-16 seconds and with a 15 second cooldown on the ability, this allows you to trap > do something > trap > dps without them ever breaking free.  Similarly, fear and polymorph last 15+ seconds on first cast and doesn't ever appear to break before 15 seconds (unless a fear breaks on damage).

**Current behaviour**: Long duration CC is too reliable and lasts too long consistently

**Expected behaviour**: Long duration CC should have random breaks after 5 seconds and should never last longer than 15 seconds.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
http://wowwiki.wikia.com/wiki/Polymorph?oldid=345903

**Comment by robinsch** [comment]
That's not how reporting a bug works. If it feels to consistent for you find a source on how HB is calculated. Currently it is calculated with spell hit chance. Threashold is only for player case. The breaking's chance is calculated from the CC's miss chance and the CC's resist chance.

**Comment by modnaros** [comment]
The wiki itself reads "No matter the listed duration, players have an ever-increasing chance to break the effect each second, with 100% chance at 15 seconds. Expect the spell to last 7 seconds on average."

**Comment by Phocus26** [comment]
@robinsch  This was a little bit different because it was previously working and changed at some point.  I did link a detailed write up for how heartbeat is supposed to work in the group chat but I will put an excerpt from that link here:

DR 1 : max duration 20 sec, HB Resist starts proccing after 6 sec (so random chance of breaking between 6 and 15 seconds, ever-increasing chance of proccing each second faster everytime from 6 to 15, 100% at 15 sec, max duration will not be reached because HB Resist has 100% proc chance at 15 sec)
DR 2 : max duration 10 sec, HB Resist starts proccing after 6 sec (so random chance of breaking between 6 and 10 seconds, ever-increasing chance of proccing each second, faster everytime from 6 to 10, still 100% at 15 sec but max duration is 10 sec so it will not be reached)
DR 3 : max duration 5 sec, no HB resist because <6 seconds max duration.
DR 4 : immune

**Comment by modnaros** [comment]
Freezing trap currently has no internal DR.

1st time you are trapped, you are debuffed for 30 seconds, with a max CC duration between 15-18 seconds.
2nd time you are trapped, you are debuffed for 18 seconds, with a max CC duration between 15-18 seconds.
The 3rd time works as intended only due to the debuff not lasting long enough for the CC to go through it's max duration.
