### ISSUE TITLE
Oil Stacks

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#104]
**Description**: Wizard Oil and Mana Oil stacks are bugged, a lower stack will stack with a higher stack and a higher stack will stack with a lower stack, if you put a lower stack with a higher stack it will reset the charges and vise versa

**Current behavior**:  Wizard Oil and Mana Oil stacks are bugged, a lower stack will stack with a higher stack and a higher stack will stack with a lower stack, if you put a lower stack with a higher stack it will reset the charges and vise versa
**Expected behavior**:  There should be separate stacks for varying charges

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
What??
