### ISSUE TITLE
Naxx Shoulder Enchant

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#105]
**Description**: You can't enchant other peoples shoulders with the Naxx enchant right now

**Current behavior**: You can't enchant other peoples shoulders with the Naxx enchant right now

**Expected behavior**: You should be able to enchant other peoples shoulders

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Whenever you report a bug like this provide a source to confirm it

**Comment by Voidwiggles** [comment]
I don't have a source for this, I just know that you guys made it to where it was possible to enchant other peoples shoulders with the Naxx shoulder enchant before the core update.
