### ISSUE TITLE
rouge stealth

### ISSUE THREAD

**Issue by rec0d** [RetroWoW/RetroWoW#106]
**Description**:

**Current behavior**: youre mounted cant go stealth

**Expected behavior**: You should cast stealth and be invisible

**Steps to reproduce the problem**:

1. remove the error message code
2. remove the if statement for if you're mounted
3. You should find the code in player.h or player.cpp depense on what source you're useing :) 

**Source:**
https://vanilla-twinhead.twinstar.cz/?spell=1784#reported-fixes
https://classicdb.ch/?spell=1784#see-also-ability
http://vanilla-wow.wikia.com/wiki/Stealth_(mechanic)

**Include Screenshots from the issue if necessary**:
https://imgur.com/a/3gyWIB8

**Comment by mentos987** [comment]
You should get an addon like "Ezdismount". It should solve your issue.
