### ISSUE TITLE
Succubus cannot cast Seduce while attacking

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#107]
**Description**: This has negative synergy with the other issues reported related to passive pets attacking but the succubus has problems casting seduce while doing anything other than sitting still for an extended period of time.

**Current behaviour**: While attacking a target, the succubus is not able to cast seduce

**Expected behaviour**: When commanded to seduce a target, the succubus should pause her attack and cast seduce.

**Steps to reproduce the problem**:

1. command a succubus to attack a hostile target
2. command a succubus to cast Seduce at that target
3. 

**Source:**
N/A

**Comment by Nemathegreatone** [comment]
Succubus still can't cast "Seduce" while in combat. "Your pet is in combat"

**Comment by robinsch** [comment]
Tested, works fine.
