### ISSUE TITLE
BG Bots

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#108]
**Description**: Bot fixes: Bots climb terrain in WSG. Bots "steal" flags from team members.

**Current behavior**: Bots climb terrain in bgs and steal flags from players
**Expected behavior**: Bot fixes: Bots climb terrain in WSG. Bots "steal" flags from team members.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
2 bugreports again at once and with no proof, respect the bug reporting guide and report all bugs seperate AND with a valid source...

**Comment by MrKelzo** [comment]
They cannot "steal" your flag, there is no such code for it

**Comment by MrKelzo** [comment]
Bot shoudln't climb the GY with flag now.
