### ISSUE TITLE
Soulfire doesn't appear to ever stun w/Pyroclasm

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#108]
**Description**: Several weeks of gameplay has not yielded a single Soulfire stun.  Possibly not working correctly.  Other warlocks have also mentioned that they have never seen a stun with 2/2 talents (25% chance to stun).

**Current behaviour**: The % chance to stun never appears to occur

**Expected behaviour**: Spells like soulfire should infrequently stun their target.

**Steps to reproduce the problem**:
N/A

**Source:**
N/A

**Comment by Nemathegreatone** [comment]
Talent Pyroclasm still not working as it should. 

By adding 2 points to it, you receive a 25% chance that spells (Rain of Fire, hellfire and Soul fire) will cast on target spell ID: 18093

After 20+ casts in a row, nothing happened.
