### ISSUE TITLE
Did not get a roll for Earthfury Vestments 

### ISSUE THREAD

**Issue by vidfinner** [RetroWoW/RetroWoW#11]
**Description**: Did not get the roll option for the Earthfury Vestments

**Current behaviour**: Tell us what happens
dice never showed up on my screen
**Expected behaviour**: Tell us what should happen instead
Option should pop up
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
Raid ID 430 I have the screen shot to show that it timed out

**Comment by vidfinner** [comment]
![wowscrnshot_012317_015503](https://cloud.githubusercontent.com/assets/25294006/22196373/8b3d674e-e112-11e6-802f-f631939c3d06.jpg)

**Comment by Bam27** [comment]
Could you provide more details?

Does this happen outside of instances?
Is there any way to reproduce this? We need a method to reproduce in order to identify what's wrong.
Were you, or the party leader far away from the boss when this happened?

**Comment by vidfinner** [comment]
I was not the raid leader and I was standing right on the boss. I got the other rolls. There was two chest pieces that dropped I got the roll for the giantstalker, but not the earthfury piece. I tried to reenter the instance (I deaded and was the only one that could rez)and was unable to loot the chest piece. 

Please help. 

Thank you

On January 23, 2017, at 10:18 AM, Bam27 <notifications@github.com> wrote:

Could you provide more details?

Does this happen outside of instances?
Is there any way to reproduce this? We need a method to reproduce in order to identify what's wrong.
Were you, or the party leader far away from the boss when this happened?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RetroWoW/RetroWoW","title":"RetroWoW/RetroWoW","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/RetroWoW/RetroWoW">https://github.com/RetroWoW/RetroWoW</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bam27 in #11: Could you provide more details?\r\n\r\nDoes this happen outside of instances?\r\nIs there any way to reproduce this? We need a method to reproduce in order to identify what's wrong.\r\nWere you, or the party leader far away from the boss when this happened?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/RetroWoW/RetroWoW/issues/11#issuecomment-274533939">https://github.com/RetroWoW/RetroWoW/issues/11#issuecomment-274533939</a>"}}}
