### ISSUE TITLE
PTR - AV - NPC's from the opposing team are friendly.

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#11]
**Description**:
I've joined Alterac Valley as Horde character and got into the Alliance team. The NPC's on the Horde side are friendly to me.
**Current behavior**: Tell us what happens
I've joined Alterac Valley as Horde character and got into the Alliance team. The NPC's on the Horde side are friendly to me.
**Expected behavior**: Tell us what should happen instead
Horde NPC's should be hostile because even though the character is Horde, but he is on the Alliance side.
**Steps to reproduce the problem**:

1. Join AV as Horde character and get into the Alliance team.
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Should be fixed now
