### ISSUE TITLE
Mind control helm does not turn players into a commandable pet

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#110]
**Description**:  

**Current behaviour**: Makes the target friendly to your faction but they still have control of their character.

**Expected behaviour**: The target should follow the controlling player and act as a basic pet with no special abilities other than: attack, return and the 3 pet states.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
https://www.youtube.com/watch?v=aDXXr3ad3is
See 1:32 and 3:15

**Comment by modnaros** [comment]
The Mind Controlled target will also use their cds and abilities. 
https://www.youtube.com/watch?v=aDXXr3ad3is
See 1:32

**Comment by xiaoxoxo** [comment]
Looks like it works as long as target isn't in combat.

**Comment by Phocus26** [comment]
http://wowwiki.wikia.com/wiki/Gnomish_Mind_Control_Cap

_There are a few limitations on this item. If, as a hunter or warlock, you already have a pet summoned, you will get the message "you already have a creature summoned." It also cannot be used if the target is in combat, thus requiring that it be triggered before combat._

**Comment by Phocus26** [comment]
malfunctions were reported at 5% in another thread

**Comment by modnaros** [comment]
From using it ingame I can definitely say the malfunctions are more than 5%

**Comment by Soviethammer** [comment]
Malfunction feels more like 60%

**Comment by modnaros** [comment]
Bump

**Comment by robinsch** [comment]
Commit: 761074fc0390e6263438cf2e6b55579874710d14

**Comment by modnaros** [comment]
Quick note: A bug with MC helmet is that the wearer of the helmet is supposed to be able to use it in combat, but his target must not be combat flagged, that is missing from the mechanics of it I believe because if I get put in combat, I can't MC someone who isn't in combat and I've tested this multiple times.

**Comment by modnaros** [comment]
Partially fixed as of 4/3/2017.

The enemy player when mind controlled will become a pet, have a pet bar w/ attack, passive, follow, stay.

The enemy player when mind controlled will also retain the ability to move independently of their new "master" and do not cast helpful spells/use cooldowns as they would in referenced media above.

Also, when you click the "Dismiss" command, it does not work, they remain your pet for the full duration of the mind control/until it breaks.

**Comment by Soviethammer** [comment]
A common bug before was that if you did this as a hunter and had a pet before you did your mc helm, your pet would just stop working
