### ISSUE TITLE
Charecter bug

### ISSUE THREAD

**Issue by artvdv** [RetroWoW/RetroWoW#111]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:I do not see quests

1. I do not see quests
2. My honor points have not been updated for a month
3. my nick name Wirles 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by utkuuanal** [comment]
Description: my ghost stuck at arena cant revive

Current behavior: Tell us what happens

Expected behavior: Tell us what should happen instead

Steps to reproduce the problem:I 

name Killmelol

Source:

Include Screenshots from the issue if necessary:

**Comment by MrKelzo** [comment]
Try disable your addons and clear the WDB Folder.
