### ISSUE TITLE
Onyxia lockout

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#113]
**Description**: Ony lockout increased?

**Current behavior**: Just did Ony, raid lockout says reset in 4 days 12 hours

**Expected behavior**: Ony lockout was resetting every day

**Steps to reproduce the problem**:

1. Kill the bish
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

![image](https://github.com/RetroWoW/RetroWoW/assets/150904264/f76d8c66-3f42-4362-88d1-42c94e3341b1)

**Comment by MrKelzo** [comment]
should be set to 2days now for testing, we'll see in 2 days.
