### ISSUE TITLE
Target Dummy

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#116]
**Description**: People are getting target dummies to follow them around in the mall

**Current behavior**:  People are getting target dummies to follow them around in the mall

**Expected behavior**: They should remain in place

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
"Steps to reproduce the problem:" is always emtpy in your reports
