### ISSUE TITLE
Pet mana regen undertuned

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#116]
**Description**: Succubus does not regen enough mana per tick.  Currently 36, should be 100.

**Current behaviour**: Succubus regens 36 mana per tick

**Expected behaviour**: Should regen 99-100 mana per tick

**Steps to reproduce the problem**:

1. cast a spell
2. wait for mana regen to tick
3. 

**Source:**
https://youtu.be/IJIJLBqSAkY?t=40s

watch the pets mana closely on his UI, you can see it ticking up after she hasn't cast for a while

**Comment by robinsch** [comment]
This depends on aura, master stats etc. Closing this because not enough sources.
