### ISSUE TITLE
Hunter Tier 3 Set bonus doesnt work

### ISSUE THREAD

**Issue by skunkin** [RetroWoW/RetroWoW#117]
**Description**:
4 piece set bonus should increase you and your pets attack power however it does not after the core released
**Current behavior**: Tell us what happens
The buff doesnt get applied
**Expected behavior**: Tell us what should happen instead
+50 attack power to you and your pet buff
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Phocus26** [comment]
Confirmed and bump!
