### ISSUE TITLE
Aeri Gryphon AV test serv

### ISSUE THREAD

**Issue by Soulweavver** [RetroWoW/RetroWoW#12]
**Description**: It seems all the Gryphons that are suppose to be triggered by defending towers for 1 min are up in AV

**Current behaviour**: Tell us what happens
The gryphons are inactive in the middle of the field of strife even Aeri Gryphon
**Expected behaviour**: Tell us what should happen instead
He spawns if you defend the beacon of the Wing Commanders for 1min
**Steps to reproduce the problem**:

1. Go to AV
2. Go to field of strike
3. Look at the gryphon  that is there without being summoned

**Source:**
Slades in-game report (Daedratic on normal serv)

http://imgur.com/a/DHesE

**Comment by robinsch** [comment]
DELETE FROM `creature` WHERE (`guid`='53134');
