### ISSUE TITLE
Bruisweed in stonetalon

### ISSUE THREAD

**Issue by mollypercoutes** [RetroWoW/RetroWoW#12]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
I am playin other servers and even on overpopulated server there's a tons of bruisweed in stonetalon, i am 99% sure there's not enought nods of it
**Expected behaviour**: Tell us what should happen instead
Shoulde be more bruisweed
**Steps to reproduce the problem**:

1. Run in stonealon
2. Search nodes

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Bam27** [comment]
Please provide a source. Speculation from other private server experience is not a valid evidence. 
Closing this until a valid source is provided.
