### ISSUE TITLE
Instance cap accountwide bug

### ISSUE THREAD

**Issue by Wayburn** [RetroWoW/RetroWoW#120]
**Description**:
Instance cap accountwide?
**Current behavior**: Tell us what happens
I was farming diremaul on my rogue and got instance capped, so i logged off and got on another toon and i joined a ZG group. I walked into the zg portal and i was instance capped.
**Expected behavior**: Tell us what should happen instead
I shouldnt be instance capped on a alt toon that i havent played in days?
**Steps to reproduce the problem**:

1. Get instance capped on a toon
2. Log a different toon
3. Walk into instance

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Its hourly
