### ISSUE TITLE
Pets get slowed when owner is cced/slowed

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#121]
**Description**: Lets say I put my pet to chase an enemy far away from me. Suddenly a mage appear and sheeps me. Now I call back my pet. but now somehow pet moves at turtle speed.

**Current behavior**: Pet gets slowed without having any slow effects on it

**Expected behavior**: Should keep its normal speed

**Steps to reproduce the problem**:

1.  Send pet to chase enemy, get sheeped/slowed(maybe other cc effects too). Now call back ur pet and it will run 10% speed of normal.
2. 
3. 

**Source:**

**Comment by robinsch** [comment]
That's blizzlike. If pet uses follow movement it should sync speed with the owner.
