### ISSUE TITLE
Make heavy runecloth bandage higher stack

### ISSUE THREAD

**Issue by Soviethammer** [RetroWoW/RetroWoW#122]
**Description**: This is not a bug, but since this server is abit custom and basically everything else is able to have higher stacks. I'd suggest to higher the stack to 100x

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Soviethammer** [comment]
Since you made the lvl 45 scrolls high stacks you should do it to the rest of the scrolls (the lower lvl ones) since hunters use the low ranks for pets. Would be a great fix and shouldn't be to hard. Cheers.

**Comment by Soviethammer** [comment]
Heavy Runecloth Bandage - 14530
Scroll of Agility - 3012
Scroll of Agility II - 1477
Scroll of Agility III - 4425
Scroll of Stenght - 954
Scroll of Stenght - 2289
Scroll of Stenght - 4426
Scroll of Stamina - 1180
Scroll of Stamina II - 1711
Scroll of Stamina III - 4422
Scroll of Protection - 3013
Scroll of Protection II - 1478
Scroll of Protection III - 4421
Scroll of Intellect - 955
Scroll of Intellect II - 2290
Scroll of Intellect III - 4419
PVP Tokens - stack of 1000 maybe?

**Comment by Bam27** [comment]
I think 225 is the limit; we've elected to use 200 for these kinds of items.

**Comment by Soviethammer** [comment]
Cheers bam

**Comment by Bam27** [comment]
UPDATE item_template SET stackable=200 WHERE entry IN(14530, 3012, 1477, 4425, 954, 2289, 1180, 4426, 1711, 4422, 3013, 1478, 4421, 955, 2290, 4419);



@MrKelzo

**Comment by MrKelzo** [comment]
Will be applied after the next restart
