### ISSUE TITLE
Nameplates

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#122]
**Description**: Friendly targets are showing enemy nameplates sometimes

**Current behavior**: When I'm doing things in the mall or elsewhere, I'm encountering a problem where enemy nameplates are showing on friendly targets

**Expected behavior**: I should not see enemy nameplates on friendly targets

**Steps to reproduce the problem**:

1.  I'm not sure, it happens randomly
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:  
[WoWScrnShot_111623_081821.odg](https://github.com/RetroWoW/RetroWoW/files/13380508/WoWScrnShot_111623_081821.odg)

**Comment by Voidwiggles** [comment]
I might have provided the wrong screenshot, let me know if I did, sorry!

**Comment by MrKelzo** [comment]
Where does it happen? Also add a jpg or png image.

**Comment by Voidwiggles** [comment]
![Nameplates](https://github.com/RetroWoW/RetroWoW/assets/147562144/96beb226-0059-44c7-a6dd-401e74afaa2d)

It happens on Cursed Island, the mall, and Gurubashi Arena

**Comment by MrKelzo** [comment]
It's a visual bug related to crossfaction groups & areas
