### ISSUE TITLE
Noggenfogger Visual Bug

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#124]
![Visual](https://github.com/RetroWoW/RetroWoW/assets/147562144/b8722e8c-efc6-43c7-b212-568c7a4aece1)
**Description**: Noggenfogger visual bug

**Current behavior**: Noggenfogger skeleton form does not show Thunderfury in your offhand, it won't show it without tmog, or with it

**Expected behavior**: You should be able to see Thunderfury in your offhand in skele form

**Steps to reproduce the problem**:

1.  Equip Thunderfury in your offhand, or tmog it, and use noggenfogger to become a skeleton
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
This is client related.
