### ISSUE TITLE
Gouge has no dr and should share it with sap

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#124]
Description: Currently since maybe 2 months ago gouge has no dr at all, and It doesn't share dr with sap like it's intended to.

Current behaviour: Tell us what happens
Rogues can gouge, wait for stealth cd, cast a full duration sap, or spam gouge every 10 sec without it being on dr.

Expected behaviour: Tell us what should happen instead
Gouge should have dr and share it with sap.

Steps to reproduce the problem:

Spam gouge every 10 sec
Cast sap after gouge
Source:
Very reliable addon Nature Enemycastebar. http://tinypic.com/r/29bhibn/9
Another one: http://wow.gamepedia.com/index.php?title=Diminishing_returns&oldid=390493

**Comment by MrKelzo** [comment]
https://github.com/RetroWoW/RetroWoW/issues/90

@ptr
