### ISSUE TITLE
Attunement to the Crater can't turn in/

### ISSUE THREAD

**Issue by Deathbizzlee** [RetroWoW/RetroWoW#124]
**Description**:
Yea.. Can't turn in the quest I have all the stuff for it.
**Current behavior**: Tell us what happens
Finished Quest but cannot continue
**Expected behavior**: Tell us what should happen instead
Complete quest to start a new questline
**Steps to reproduce the problem**:

1. Talk to guy
2. click chosen quest
3. cant continue to turn in

**Source:**
Mall quest bug Retro-WoW

**Include Screenshots from the issue if necessary**:
![discord pic](https://user-images.githubusercontent.com/41906526/43398076-fa656b64-93d4-11e8-83d5-7f5f45073459.png)

**Comment by mentos987** [comment]
Try abandoning the quest then relog and retake the quest. This bug is an old one.
