### ISSUE TITLE
Hunter traps seen by everybody

### ISSUE THREAD

**Issue by Soviethammer** [RetroWoW/RetroWoW#125]
**Description**: Hunters freezing trap can be seen by anybody all the time. Its supossed to be hidden if you're not a rogue with detect traps.

**Current behavior**: Traps are not hidden.

**Expected behavior**: Traps shouldn't be seen by other players if not allied. Only rogues should have a chance to spot them with Decect traps. 

**Steps to reproduce the problem**:

1. Duel a hunter, tell him to use freezing trap
2. Its not hidden
3. 

**Source:**
http://vanilla-wow.wikia.com/wiki/Detect_Traps
http://vanilla-wow.wikia.com/wiki/Freezing_Trap

**Comment by Soviethammer** [comment]
http://imgur.com/a/36Hqc

**Comment by Soviethammer** [comment]
Closed because?

**Comment by robinsch** [comment]
Fixed.

**Comment by Soviethammer** [comment]
Okey thanks!

**Comment by Soviethammer** [comment]
So next restart?

**Comment by robinsch** [comment]
No, needs to be pushed on PTR and then confirmed by one of our testers. Then it's pending on live update which follow the comming days after fix was confirmed on PTR.
