### ISSUE TITLE
Large Rope Net

### ISSUE THREAD

**Issue by yottamori** [RetroWoW/RetroWoW#126]
**Description**: Large Rope Net is very useful item for fc 

**Current behavior**: after update Large Rope Net removed from drop

**Expected behavior**: Greymist Netter and Murloc Netter was drop Large Rope Net

**Steps to reproduce the problem**:

1. plz fix 
2. ...
3. ....

**Source:**
https://classicdb.ch/?npc=513  https://classicdb.ch/?npc=2204

**Comment by MrKelzo** [comment]
Dropped by following NPCs (ID):

513
2204
504

**Comment by yottamori** [comment]
are u trolling me ? thay does not drops ill report with video naw and u can watch that item removed
