### ISSUE TITLE
Add earthstrike and rockfury bracers to vendors

### ISSUE THREAD

**Issue by Soviethammer** [RetroWoW/RetroWoW#129]
Hey, since its pretty much impossible to complete the badge farm on this server due to population and other things. I suggest you add the items to the AQ vendor, or make a new vendor for items from the badge farm. Alot of people that I asked, starters and engamers want this. 

Earthstrike - 21180
Rockfury bracers - 8574
Fist of Cenarius - 21188
Wrath of Cenarius - 21190

Thanks.

**Comment by MrKelzo** [comment]
Please use the suggestions section on our forum instead.
http://retro-wow.com/forum/forumdisplay.php?fid=19
