### ISSUE TITLE
Gurubashi Arena Chest

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#130]
**Description**: The Gurubashi Arena chest is bugged

**Current behavior**: The previous Gurubashi Arena chest won't despawn, and when the npc comes down to spawn a chest, it won't spawn a new chest with the trinket in it

**Expected behavior**: The previous chest  Gurubashi Arena chest should despawn, allowing  a new chest to spawn with the trinket

**Steps to reproduce the problem**:

1. Don't loot everything from the chest and wait for the npc to spawn a new one
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Fixed next restart
