### ISSUE TITLE
DONATIPN BUG

### ISSUE THREAD

**Issue by Rafsentraine** [RetroWoW/RetroWoW#132]
I bought 10 000 Gold on website, 
I send it to my 19 Twink (Brabys) but when i trade it with the Pnj , he take token but he dont give me gold,

**Comment by MrKelzo** [comment]
This was already fixed last night

**Comment by Rafsentraine** [comment]
Ok but what about the 10k gold ?

I don’t receive on my character , the PNJ give me nothing
