### ISSUE TITLE
Pet Pathing

### ISSUE THREAD

**Issue by skunkin** [RetroWoW/RetroWoW#132]
**Description**:
Pets should not be able to attack players when they dont have a direct line of sight of them.
**Current behavior**: Tell us what happens
Pets can attack players regardless of of they have line of sight or not.
**Expected behavior**: Tell us what should happen instead
Pets should have a 'cant attack that player because your pet does not have line of sight' message. Very annoying because warlocks and hunters just send their pets at WSG flag carriers and then they follow their pet right to the player no matter where he is hiding. 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by mentos987** [comment]
You would need a source for this. I have never seen it. Or is it more of a suggestion?
