### ISSUE TITLE
Mind Quickening Gem not working correctly.

### ISSUE THREAD

**Issue by barcodekillr** [RetroWoW/RetroWoW#133]
**Description**:
Mind Quickening Gem is not properly working. 
''Quickening the mind, increasing the Mage's casting speed by 33% for 20 sec.'' is the description.

**Current behavior**: Tell us what happens

However, it's not 33%. A regular Frostbolt (without talents) is a 3 second cast, but with Mind Quickening Gem used it's reduced to 2.3 seconds.
A Fireball (with the talent Improved Fireball) is also a 3 second cast, but with Mind Quickening Gem used it's reduced to 2.3 seconds. 
So the expected haste % is not based on a ''regular'' spell without talents, since the 33% doesn't apply to any of them.
Same goes with Scorch, 1.5 seconds -> 1.1 seconds.
And Pyroblast, 6 seconds -> 4.5 seconds.

**Expected behavior**: Tell us what should happen instead

The 3 second casts should be reduced by 1 second, therefor making it a 2 second cast, 1.5 seconds into 1 second and 6 seconds into 4 seconds.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Works perfectly fine; This item was debuffed in the 1.12.1 patch. It used to increase casting speed by 25%.

Source: https://wowpedia.fandom.com/wiki/Mind_Quickening_Gem
