### ISSUE TITLE
Big-mouth Clams and drop rates of Golden Pearls

### ISSUE THREAD

**Issue by AImedes** [RetroWoW/RetroWoW#134]
Hey Kelzo, it’s Marklar the enchanter. 

I'm providing an update on the drop rates of Golden Pearls when opening Big-mouth Clams (https://classicdb.ch/?item=7973#contains) after you Fixed the drop rates of uncommon and poor items which should now mirror the original rates.

After doing extensive farming, I can say with confidence that before incorporating the vmangos changes it was (at least) two or three times more likely to get Golden Pearls (GPs) even after the fixed droprates. 
Also, I noticed that it was possible and had a lot of instances of finding 2 Black Pearls (BPs) in the same clam, which I had never seen before. Also BPs should be about 2,2 times more likely to drop than GPs (based on classic database), but in practice I noticed that I had about 4 times more BPs than I did GPs, each time when spending an few hours farming clams.

Specifically, in the Isle of Dread cave (northern part of the island) in Feralas, as a BIS mage clearing mobs at respawn rate, my average GP acquisition rate has been around 1.5-2 GPs per hour post-change. This rate is an improvement over the initial sharp drop of last week's change, but it still falls short of the pre-update experience. Previously, I would consistently gather 6-8 GPs per hour, occasionally reaching as high as 10-14 GPs. I’m not sure if that’s intended or not, I’m just reporting the changes as I see them after opening hundreds of clams each day.

While I acknowledge my role as an enchanter might introduce a perception of bias, but my concern primarily stems from the current challenge in meeting the enchanting demands of the player base and because I am not keen on leaving players hanging, or increasing the price of 30 Spell Power on weapon - especially because I want it to be affordable for the newer players (and frankly, all players). 

I do a lot of enchanting for free already and I give back as much as humanly possible to the community and players .I try to guide and help new players understand how flourish on Retro-Wow, how to start gearing and make gold and introduce the server’s features every day and will continue to do so. 
My concern is that I find myself spending more time farming pearls (and essences) than spending time doing pve/pvp activities or socializing, while keeping up with demand - which was not my experience before the changes. 

(Essence of Air has a lot to do with it aswell, now that Whirling Invaders are gone from Silithus. Dust Stormers have reduced drop rate for essences, that is similar to that of GPs in clams, but that is a conversation for another post)

**Comment by MrKelzo** [comment]
The drop % was nerfed from 1.7 to 0.5 (by vmangos) prob due this comment

![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/8a7dffe7-62fe-4140-bb13-3c0f4f0d98cb)

But I will revert the change and set it to 1.7 as before.

**Comment by AImedes** [comment]
> The drop % was nerfed from 1.7 to 0.5 (by vmangos) prob due this comment
> 
> ![image](https://private-user-images.githubusercontent.com/25086832/286448918-8a7dffe7-62fe-4140-bb13-3c0f4f0d98cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjgyNTIsIm5iZiI6MTcwMTI2Nzk1MiwicGF0aCI6Ii8yNTA4NjgzMi8yODY0NDg5MTgtOGE3ZGZmZTctNjJmZS00MTQwLWJiMTMtM2MwZjRmMGQ5OGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE0MjU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZWQyMWZkMjU3NzFjODQ3OTZiMDM2NDJmM2MyNTUyOGM1NzRiN2ExMDFkMDc1NzVkOTRhNzE4OGZiNGQxZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1H2owi8rZxRrjJnTaetQzZeG1l7PTk0EbJOlz2bflO8)
> 
> But I will revert the change and set it to 1.7 as before.

Ι tested it , farmed arround 500 clams and didn't get a single drop of GP. Maybe something went wrong or was I terribly unlucky?

**Comment by MrKelzo** [comment]
I forgot to reload the table, should be fine now

**Comment by AImedes** [comment]
Awesome, thanks for the fast response!

**Comment by AImedes** [comment]
> I forgot to reload the table, should be fine now

It's good now, got my first pearl in about 80 clams
