### ISSUE TITLE
Large Rope Net removed

### ISSUE THREAD

**Issue by yottamori** [RetroWoW/RetroWoW#135]
I was farmed 30-40 min before I record this video and nothing droped. u can watch here - https://www.youtube.com/watch?v=FlbOJtGbHt8
"Large Rope Net" removed from game after update. before update this mobs droped 3-5x net every pull. plz fix this item if possible

**Comment by MrKelzo** [comment]
Ye looks like it's removed after patch 1.7.0 thats why it doesn't drop atm.
https://wowpedia.fandom.com/wiki/Large_Rope_Net

**Comment by yottamori** [comment]
)))))))) u cant add plzzz?
