### ISSUE TITLE
Stuck in death mode flying around hijal

### ISSUE THREAD

**Issue by neffff** [RetroWoW/RetroWoW#137]
**Description**:
Stuck in death mode in my account Thjke after use a teleport for the mall before dying.
**Current behavior**: Tell us what happens
Stuck in ghost mode moving around i can't log out or quit. nothing
**Expected behavior**: Tell us what should happen instead
Can you Unstuck me?
Thank you.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please open a ticket ingame.

**Comment by timelord-riccard** [comment]
Hello,

I have the same problem, can sombody help me ?

Kind regards,

Riccardo
