### ISSUE TITLE
blink in horde side wsg gets stuck

### ISSUE THREAD

**Issue by oldspices** [RetroWoW/RetroWoW#138]
**Description**:
when you mage blink down the ramp in the room where gate is @ start you dont move forward
**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead
you should be able to go down
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by modnaros** [comment]
I honestly couldn't understand this. You need to use more detail when describing your issues. "down the ramp in the room where gate is @ start" Meaning the horde flag room? 

If you blink down it, you do in fact blink forward, there are obvious terrain issues with blink but if this is what you mean, no it works fine unless you're aimed at an awkward angle, or if you're standing on the flat ground that is slightly above the ramp. 

It's a game mechanic, not a bug. /thread
