### ISSUE TITLE
missing items at vendor

### ISSUE THREAD

**Issue by mio1000** [RetroWoW/RetroWoW#139]
**Description**: The following shadow resistance items are missing at vendors for gold:
https://classicdb.ch/?item=20537
https://classicdb.ch/?item=21530
https://classicdb.ch/?item=21529

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Phocus26** [comment]
The legs and neck are quest rewards and are obtainable via that quest chain.
