### ISSUE TITLE
Activity Point Issue

### ISSUE THREAD

**Issue by redsfate** [RetroWoW/RetroWoW#139]
**Description**:   My activity points haven't updated since i donated to retro wow.  

**Current behavior**: I have played for MANY hours and the chat "in game" shows that I'm earning them 
             but the website isn't showing any accrual.  

**Expected behavior**: I should have way more activity points 

**Steps to reproduce the problem**:

1. Play several hours
2. check website
3. note lack of earned activity points

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:
![Screenshot (9)](https://github.com/RetroWoW/RetroWoW/assets/152266062/8aa6daa5-edc8-4dfc-9015-d5b009d1b401)
![Screenshot (9)](https://github.com/RetroWoW/RetroWoW/assets/152266062/d91a83f0-8103-45a9-8601-30bbd5171ea9)

**Comment by andriiaz** [comment]
Can confirm that I've discover this issue as well.

**Comment by MrKelzo** [comment]
Was fixed already earlier today

**Comment by redsfate** [comment]
will i get activity points back, it seems it's still stuck at 58
