### ISSUE TITLE
PTR Weapons with Chance on hit: Steals x life

### ISSUE THREAD

**Issue by Rank1paladin** [RetroWoW/RetroWoW#14]
**Description**: Weapons with life steal effect like neretzek and ashbringer not scale with spellpower

**Current behavior**: tested with 400+ sp, zero scale

**Expected behavior**: chance on hit: steals x life proc scale 100%  with spell power.

**Steps to reproduce the problem**:

1. Equip sp gear and a wep like Ac, Ntbd, ancient hakkari from zg.
2. Hit the dummi

**Source:**

https://classicdb.ch/?item=21856#comments
https://classicdb.ch/?item=19852#comments
Its nerfed only in classic wow maybe in tbc . Work fine in the past.(2006, 1.12)

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/209857210-3a4430ba-9783-4f56-b4ad-b431b702fe41.png)
https://us.forums.blizzard.com/en/wow/t/neretzek-the-blood-drinker-spell-power-scaling/630801/27

https://eu.forums.blizzard.com/en/wow/t/corrupted-ashbringer-not-working/224903/11

https://www.reddit.com/r/classicwow/comments/laknax/question_for_people_with_corrupted_ashbringer/

![image](https://user-images.githubusercontent.com/25086832/209857902-9b9a0e16-a2d2-4cd7-9b1c-e6e552c562b2.png)
https://www.reddit.com/r/classicwow/comments/dcu0i2/confirmed_weapon_procs_that_scale_with_spell/
