### ISSUE TITLE
Players eligible for ony/nef/hakkar quest items that already have them, or even completed the quest already

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#140]
**Description**: Players receiving multiple ony/nef/hakkar quest items

**Current behavior**: Players are able to need/greed and receive items like Ony head, Nef head, Heart of Hakkar, when they already have one or are already on the quest or even completed the quest. Some players are needing on these items when they can't even use them, taking them from other players that haven't gotten them yet.

**Expected behavior**: If you already have the quest item, are on the quest, or have completed the quest, they should not be eligible to receive that loot. 

**Steps to reproduce the problem**:

1. Get one of the quest items, accept the quest, maybe even complete the quest, then go get another one. 
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
This is due to crossfaction raiding, these items are unique but exist for each faction with a separate ID
