### ISSUE TITLE
Greater Paladin Blessings (15min) dissapear if buffer paladin logs out

### ISSUE THREAD

**Issue by mauricioreyes** [RetroWoW/RetroWoW#141]
**Description**:

Greater Paladin Blessings (15min) dissapear if buffer paladin logs out

**Current behavior**: 
When a paladin buffs you with 15minutes blessings and then the buffer logs out, the blessings are lost. This doesn't happen with the 5minutes blessings. Other class buffs don't show this behavior. 

**Expected behavior**: Tell us what should happen instead

AFAIK, greater blessings should remain independently of the logged status of the buffer

**Steps to reproduce the problem**:

1. have a paladin in your group
2. have the paladin buff you a 15min (e.g. greater blessing of kings)
3. have the paladin log out4. 
4. check the blessing dissapear on the character being buffed5. 

**Source:**
unfortunately I didn't find anything 

(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)
**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/29e58574-9327-4762-9aa5-ba8780443bd9)
