### ISSUE TITLE
COMBAT points as rogue in BGs reseting when attacking same target (not swaping targets)

### ISSUE THREAD

**Issue by Qbaa89** [RetroWoW/RetroWoW#142]
**My combat points get resetet tho I dont switch target**:

**its 70 % of games that it happens. I try to reload game /start again etc but nothing works**: Tell us what happens

**Combat points should stay on a target. Its rogues only dmg deal so it sucks when its broken

**: Tell us what should happen instead

**I cant send my zip file with MP4 when im playing so I donno how to show you this problem... Cant show it on images....**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
This is blizzlike behavior. Closing this.
