### ISSUE TITLE
Greater Paladin Blessings (15min) dissapear if buffer paladin logs out - With screenshots :)

### ISSUE THREAD

**Issue by mauricioreyes** [RetroWoW/RetroWoW#142]
Description:

Greater Paladin Blessings (15min) dissapear if buffer paladin logs out

Thanks for checking Kelzo, now I added screenshots (Happy to show it in-game as well) 

Current behavior:
When a paladin buffs you with 15minutes blessings and then the buffer logs out, the blessings are lost. This doesn't happen with the 5minutes blessings. Other class buffs don't show this behavior.

Expected behavior: Tell us what should happen instead

AFAIK, greater blessings should remain independently of the logged status of the buffer

Steps to reproduce the problem:

1. have a paladin in your group (In screenshot the paladin's name is Lioter)
2. have the paladin buff you a 15min (e.g. greater blessing of kings)- see second screenshot
3. have the paladin log out. See third screenshot
4. check the blessing dissapear on the character being buffed5. See third screenshot

Source:
unfortunately I didn't find anything online

(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)
Include Screenshots from the issue if necessary

**Comment by MrKelzo** [comment]
This is NOT a bug and was explained already on your previous report https://github.com/RetroWoW/RetroWoW/issues/141
