### ISSUE TITLE
Hunter traps not invisible

### ISSUE THREAD

**Issue by Nelielu** [RetroWoW/RetroWoW#143]
**Description**:
Hunter traps are not invisible 
**Current behavior**: Tell us what happens
People just dodge them cause they can see it
**Expected behavior**: Tell us what should happen instead
Rogues should be able to disarm the traps and that's it.
**Steps to reproduce the problem**:

1. Set a trap
2. Enemies can see it
3. 

**Source:**
Vanilla

**Comment by Bam27** [comment]
This has been fixed already. 

#125

**Comment by Sunqtt** [comment]
the thing that guy was trying to say is that rogues are supposed to see hunter's trap, since they are able to desarm them.

rogues have a passive : http://vanilla-wow.wikia.com/wiki/Detect_Traps

right nw rogues can't see trap in retrowow
