### ISSUE TITLE
It's a secret to everybody - quest

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#143]
**Description**: 2nd part in a chain, I am supposed to find a pack underneath the water. The pack (I believe) is supposed to have a number of items  in it that are required to move to the next step. The pack has none of the items so can't move forward

**Current behavior**: The pack doesn't give the quest items

**Expected behavior**: The pack should have the quest items--

Large Compass
Curled Map Parchment
Lion-headed key

**Steps to reproduce the problem**:

1. Take the quest from the broken boat, grab the satchel, find it empty... except for a picture
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:
![image](https://github.com/RetroWoW/RetroWoW/assets/150904264/b81530cc-4116-4ee5-96d5-92cd1603a5e1)

**Comment by MrKelzo** [comment]
![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/b95edc8e-517a-4b23-a3fa-917e68550165)
Works fine to me
