### ISSUE TITLE
Gnomish Battle Chicken bugged

### ISSUE THREAD

**Issue by Paul8000** [RetroWoW/RetroWoW#145]
Hi, since new Core "Gnomish Battle Chicken" has been bugged, was too lazy to report until now

Using it bugs out your Character 95% of the time and makes unable able to cast/use abilities until you die (mounting up sometimes fixes it aswell)

Greetings
Clotz

**Comment by MrKelzo** [comment]
Follow the report guide and provide all details. I cannot reproduce it.
