### ISSUE TITLE
Deadly poison stacks with spell power

### ISSUE THREAD

**Issue by Soviethammer** [RetroWoW/RetroWoW#145]
**Description**: Deadly poison stacks with spell power

**Current behavior**: Currently deadly poison stacks with spell power

**Expected behavior**: Shouldn't stack with spell power

**Steps to reproduce the problem**:

1. Get spell power gear and a flask
2. Get deadly posion max rank
3. See.
Here's a screenshot of a rogue using spell power gear for posion http://imgur.com/a/40yCG
http://db.vanillagaming.org/?item=20844#wh-comments
**Source:**

**Comment by Soviethammer** [comment]
needs to be fixed ASAP, so many rogues using spell power gear now

**Comment by xiaoxoxo** [comment]
ip banning for this seems little harsh

**Comment by MrKelzo** [comment]
should be fixed, please reopen if it still exists
