### ISSUE TITLE
AQ20 Gear Tokens and AQ Rep Tokens

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#147]
**Description**: Someone in my guild said that the AQ20 gear tokens are bugged and that you can't turn them in, I was also told that the AQ rep items are bugged and that you can't turn them in. I have not had the opportunity to look into this yet but I was hoping you could check it out.
**Current behavior**: You can't turn in AQ20 tokens or AQ rep tokens

**Expected behavior**: You should be able to turn them in

**Steps to reproduce the problem**:

1.  Obtain an AQ20 gear token and go to the npc with the required rep, the npc will not give you the quest for the token from what I've been told
2. Obtain the rep token from the bosses in AQ and try turning them in
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Give all details, which items, quest name, quest giver
