### ISSUE TITLE
Noggenfogger Bug

### ISSUE THREAD

**Issue by Voidwiggles** [RetroWoW/RetroWoW#149]
**Description**:  I asked around after you said that the Noggenfogger bug was on my end and I found out that it's a bug that everyone I've talked to is experiencing as well. Can you please look into the Noggenfogger bug and fix it? It's not just on my end. I would really like to see Thunderfury in my offhand on my warrior and rogue, I donated for it on both characters.

**Current behavior**: The Noggenfogger skeleton buff makes Thunderfury disappear in your offhand, you can't see it while your weapons are sheathed.

**Expected behavior**: Thunderfury should show up in your offhand even when it's sheathed.

**Steps to reproduce the problem**:

1.  Turn into a skeleton using Noggenfogger Elixir and equip Thunderfury in your offhand.
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
This is just visual client issue and not a bug related to the server
