### ISSUE TITLE
Night Elves dont turn into wisps when they die.

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#150]
**Description**: Racial is broken.

**Current behavior**: You turn into a ghost

**Expected behavior**: Turn into a wisp with +50% move speed.

**Steps to reproduce the problem**:

1. ....DIE!!!!
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/45307738-1757a180-b520-11e8-987d-74d32ec79c71.png)
