### ISSUE TITLE
Jindo the Hexxer ZG boss

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#151]
**Description**: boss spawns impossible adds

**Current behavior**: the boss spawns invisible adds that are to be killed by *only* a cursed player taht can see them. the adds are super strong or there are a large amount of them (maybe tuned for 40 man). we did the fight with 5 bis players and we were deleted the moment adds were spawned

**Expected behavior**: adds should be weaker or less numerous so they are manageable

**Steps to reproduce the problem**: 

1. Do the fight
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
The ads you are talking about have 1400 HP only and it is the same as before.

**Comment by MrKelzo** [comment]
Will be fixed after next restart
