### ISSUE TITLE
Combat Bug - Gluth

### ISSUE THREAD

**Issue by sopse** [RetroWoW/RetroWoW#152]
**Description**:
Everytime you do naxx and you killed gluth you are still in combat. All raids ive been in so far just Alt + F4 its but surely this should be fixed so we no longer need to do that.

**Current behavior**: Tell us what happens
Keeps you in combat even after you killed gluth.

**Expected behavior**: Tell us what should happen instead
Exit combat after gluth is dead

**Steps to reproduce the problem**:

1. Just clear abomination wing and you will get the combat bug once you killed gluth

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Fixed after next restart
