### ISSUE TITLE
Qiraji Lord Insignia

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#153]
**Description**: Can't turn in the rep items dropped off each boss in AQ40

**Current behavior**: Nowhere to turn it in

**Expected behavior**: Should be able to turn it in at one of the NPCs in hte front

**Steps to reproduce the problem**:

1. Get an insignia from a dead boss, try to turn in
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by Usinggithubcoolguy** [comment]
Are there any details as to why this is invalid? With the new core update, no raiders have been able to turn in the Qiraji Lord's Insignia. We can still loot them off all bosses besides C'thun, but there is nowhere to turn them in. The NPC that you usually turn them in to has no option to do so. 

![image](https://github.com/RetroWoW/RetroWoW/assets/150904264/21ff2017-3e0b-4676-ad59-5a14a7a52b11)

**Comment by MrKelzo** [comment]
The report was invalid, but the quest is added now
