### ISSUE TITLE
Not sure if bug or intentional -- Unable to disenchant blue items from Maraudon

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#154]
**Description**: Farming Large Radiant shards for enchant. Unable to disenchant Noxious shooter, Satyr's Lash, Phytoskin Spaulders, Bloomsproud Headpiece, Claw of Celebras. Maybe this is intentional for some reason, but if so, it's very difficult to farm Large Radiant shards for enchants. 

**Current behavior**: If I try to disenchant, I get the error "That item can't be disenchanted"

**Expected behavior**: Expected to be able to disenchant them

**Steps to reproduce the problem**: 

1. Get the item
2. Attempt to disenchant
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Starter items from the vendors cannot be disenchanted.

**Comment by Usinggithubcoolguy** [comment]
Can large radiants be added to the vendor then? How else can we get them... :)
