### ISSUE TITLE
Rumsey rums

### ISSUE THREAD

**Issue by myysti** [RetroWoW/RetroWoW#155]
**Description**:Rumsey rums are gone from the vendor (barkeep kelly) in southshore, hillsbraid (where they are usually)

**Current behavior**: Tell us what happens the npc doesn't have rumsey rums

**Expected behavior**: Tell us what should happen instead the npc should have a tab that sells rumsey rums
**Steps to reproduce the problem**:

1. go there
2. try click npc its not even a vendor anymore
3. *cry*

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**: Yes i know this image says its only available in old hillbraid but before the new core update you were able to just go to normal southshore directly and get it
![image](https://github.com/RetroWoW/RetroWoW/assets/151477733/59d98697-4e5c-4d9d-8586-828efd542948)

**Comment by MrKelzo** [comment]
Also this 
![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/aee7af1e-555f-4c6b-ac28-13e88affc340)
But I've added it anyway.
