### ISSUE TITLE
Silverwing Supply Officer missing items

### ISSUE THREAD

**Issue by mio1000** [RetroWoW/RetroWoW#155]
**Description**: There are missing various epic and bue items at this vendor   https://www.classicdb.ch/?npc=14753

**Current behavior**: only few items can be bought, others not available

**Expected behavior**: the vendor should sell based on reputation with Silverwing sentinels (same for horde equivalent) several epic and blue items 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
This vendor is working as intended. You need reputation in order to view the related items.
