### ISSUE TITLE
AQ20 Kurinaxx - Spawns sand pits extremely fast, is this tweaked still for 20man?

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#157]
**Description**:The sand pits that spawn on Kurinaxx spawn so fast, it's extremely difficult to avoid them. It occurred to me, maybe this is because the mechanic is still functioning as if it were a 20 man raid... 

**Current behavior**: Sand pits spawn so quickly they are near impossible to avoid. Especially in melee heavy groups. 

**Expected behavior**: Maybe they should spawn a bit slower. Maybe even 1/4 the rate, to account for 5 man vs. 20 man. 

**Steps to reproduce the problem**:

1. Engage Kurinaxx and see how fast the sand pits spawn
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Sandtrap timers are the same for past 9 years

**Comment by Usinggithubcoolguy** [comment]
Doesn't mean they were correct to begin with... If it was never updated for a 5 man raid, it's been wrong for 9 years.
