### ISSUE TITLE
Horde Nef head no turn in

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#158]
**Description**:Horde Nef head is not able to be turned in. The NPC Overlord Saurfang has no quest turn in option, no dialogue at all

**Current behavior**: Can turn the head in to thrall, then the chain goes to Saurfang, but not able to talk to Saurfang

**Expected behavior**: Should be able to turn in to saurfang

**Steps to reproduce the problem**:

1. Get the head, follow the quest chain
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)
https://www.wowhead.com/classic/quest=7784/the-lord-of-blackrock
![image](https://github.com/RetroWoW/RetroWoW/assets/150904264/4416245b-b7b4-4dee-b420-a78425b7da25)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Means you have the alliance one

**Comment by Usinggithubcoolguy** [comment]
But we can still accept the quest and turn in the initial step in the chain to Thrall?
