### ISSUE TITLE
High Priestess Jek'lik LoS still a problem

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#159]
Description: There is a LoS issue, like a wall in front of her

Current behavior: Try to pull, shoot, cast, anything, get LoS issue. We always have to use an AoE on the wall to pull her... Blizzard, volley, etc. 

Expected behavior: Should be able to shoot her

Steps to reproduce the problem:

1. Try to cast a single target spell or shoot her, doesn't work.
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
pushing the fix in 15 mins from now
