### ISSUE TITLE
Speed/Berserking/Restoration buffs in WSG

### ISSUE THREAD

**Issue by Smlzlikecrit** [RetroWoW/RetroWoW#16]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The battleground buffs are applied as debuffs so you're unable to remove them
(not sure about av/ab but wsg it happens and therefore should happen in others).
PS: Happens in azshara crater as well

**Expected behaviour**: Tell us what should happen instead
The buffs should be considered as a beneficial spell which you can remove 

**Steps to reproduce the problem**:

1.  Join wsg
2.  Get any of the available buffs 
3.  Observe it become a non-beneficial spell

**Include proofs for this behaviour**
https://youtu.be/dMjzmmqrfxU?t=219

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by nono234** [comment]
You linked a tbc video(you can just tell by the LFD icon), its supposed to be a debuff in vanilla. Proof: https://youtu.be/CStaLR0ipxY?t=173
