### ISSUE TITLE
Piercing Howl (Warrior) Bug

### ISSUE THREAD

**Issue by kamiyo1230** [RetroWoW/RetroWoW#160]
**Description**: 
Piercing Howl can only slow 1 target, not multiple targets

**Current behavior**: Tell us what happens
Piercing Howl can only slow 1 target.

**Expected behavior**: Tell us what should happen instead
Piercing Howl should slow all enemies near the warroir.

**Steps to reproduce the problem**:

1.  Have a warrior with piercing howl
2.  Test on dummies
3. 

**Source:**
Ability description

**Include Screenshots from the issue if necessary**:

**Comment by skunkin** [comment]
+1. Very annoying bug
