### ISSUE TITLE
Razuvious is 1 shotting full BiS tanks

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#161]
**Description**: Since recent reset, just did Naxx, Razuvious is 1 shotting full BiS tanks

**Current behavior**: Unbalancing Strike for 13000 damage. HIT. That's a HIT. Not crit. 

**Expected behavior**: Razuvious is a puppy dog usually

**Steps to reproduce the problem**:

1. Go tank that fatboy
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:
![image](https://github.com/RetroWoW/RetroWoW/assets/150904264/0e61de62-cbab-434e-9e87-866fda64caba)

**Comment by MrKelzo** [comment]
he must be very angry at you

**Comment by MrKelzo** [comment]
Was related to a recent pull, reverting it.
