### ISSUE TITLE
Delay on Reflectors

### ISSUE THREAD

**Issue by Kekttop** [RetroWoW/RetroWoW#161]
Theres a experienced delay on the effect of using reflector

The trinket needs to be activated before opponent release spell to be able to procc

Even if opponent has casted spell , in the air or not , reflector should always procc before landing if activated

**Comment by robinsch** [comment]
No reflection is checked on cast. You could never reflect already flying projectiles on retail.

**Comment by Kekttop** [comment]
got it all wrong then! ty
