### ISSUE TITLE
[Mage] Grenade triggers Ignite

### ISSUE THREAD

**Issue by Tanbao001** [RetroWoW/RetroWoW#162]
Grenade / Talent tree bug

Hello,
as it seems, Iron Grenades (probably Thorium Grenades as well, haven't tested it) are triggering a ignite as a mage, when you have specced the talent Ignite (tooltip: ''Your criticial strikes from fire damage spells cause the target to burn for additional 40% of your spell's damage over 4 sec..'').

As far as I can remember, that shouldn't be the case (never saw it before).

Ignite Talent (1.12)
[https://wowpedia.fandom.com/wiki/Ignite_(Classic)](url)

Iron Grenade Description of **Wowpedia.fandom.com**
[https://wowpedia.fandom.com/wiki/Iron_Grenade](url)

Thorium Grenade Description of **Wowpedia.fandom.com**
[https://wowpedia.fandom.com/wiki/Thorium_Grenade?so=search](url)

A Clip is added.

**Comment by MrKelzo** [comment]
![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/037032d6-0f3e-4602-94e5-904889a58e26)

**Comment by MrKelzo** [comment]
![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/5fe2c879-35de-4a13-b558-b7e57f6bb46c)
