### ISSUE TITLE
Bloodlord Mandokir "watching you" kills you even if you don't do anything

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#163]
**Description**:Seen multiple times where myself or others hit esc, exit out of all actions... but the boss still kills us. 

**Current behavior**: Glares at you, "watching you", esc out, still die

**Expected behavior**: If you perform no actions while he's watching you, I believe you are supposed to live

**Steps to reproduce the problem**:

1. Do the fight. I'm not entirely sure because it seems like it happens sometimes but other times it functions properly
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by sopse** [comment]
I did the fight last night aswell. Can confirm this happens

**Comment by Hawelar** [comment]
I confirm this bug

**Comment by MrKelzo** [comment]
Let me know if there are still issues.
