### ISSUE TITLE
Character Stuck

### ISSUE THREAD

**Issue by EricDelaware** [RetroWoW/RetroWoW#165]
**Description**:
Died during a raid, rest of the raid was still alive when I decided to res.  When I could not zone, I tried to blink into the zone with mana shield and ice barrier on. Got teleported somewhere strange. Now I am just falling, taking damage almost down to zero but not enough to kill me. Cannot hearth or use .st.
**Current behavior**: Tell us what happens
Falling in the Air.
**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Have raid still alive in Ony
2. Have Ice Barrier and Mana Shield on as a mage. 
3. Blink into the instance right.
Badassb Human Female Mage

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
Please create a ticket in the event this happens again. 

Closing this.
