### ISSUE TITLE
Warlock talent: Pyroclasm (malfunction)

### ISSUE THREAD

**Issue by kamodil** [RetroWoW/RetroWoW#165]
**Description**: **Pyroclasm**, a warlock talent does not work properly.

**Current behavior**: Having spent talent points on this talent, the spell hellfire won't proc any stuns.

**Expected behavior**: According to the what is described in the talent, having spent talent points in **Pyroclasm** hellfire is supposed to be able to proc stuns.

**Steps to reproduce the problem**:

1. Add stuns to the talent?
2. I don't know how to code.
3. 

**Source:**
https://wowpedia.fandom.com/wiki/Pyroclasm_(warlock_talent)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Works fine.. 

![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/dd3f0171-06a3-4bb7-892e-d561323fd69c)

**Comment by kamodil** [comment]
Hi again and thanks for your reply. Are you using Hellfire or Rain of Fire? Rain of Fire works for me but Hellfire doesn't. I've tried several times on 3 dummies at a time.
