### ISSUE TITLE
Quest Objective level bug=> Taming the best, 2nd and 3rd part, Teldrassil, Alliance

### ISSUE THREAD

**Issue by Timaios28** [RetroWoW/RetroWoW#166]
**Description**: Taming the beast, Teldrassil, 2nd and 3rd part, the beasts to be tamed are lvl 60.

**Current behavior**: The Nightsaber stalker in the 2nd part should be lvl 7-8. Instead it's 60. And so is the Strigid Screecher that is required to be tamed on the 3rd part.

**Expected behavior**: The Strigid Screecher should be lvl 7-8 and so does the Nightsaber stalker. The quest cannot be finished when the beasts are lvl 60 and it is a major quest for the Elf hunter.

**Steps to reproduce the problem**:  You don't even have to take the quest to check it out. Just go to where the Nightsade Stalkers and the Strigid Screechers are and you'll see they are lvl 60 in a noob area.

**Comment by MrKelzo** [comment]
Fixed after next restart (tuesday night)

**Comment by Timaios28** [comment]
Nice! Thanks!
