### ISSUE TITLE
i got banned for no reason 

### ISSUE THREAD

**Issue by ghost** [RetroWoW/RetroWoW#166]

**Comment by Nelielu** [comment]
This ain't the ban appeal place dude don't bother the dev with this please he has a lot to do and no time to spend reading things he cannot do shit about.
Here is the link:
http://retro-wow.com/forum/forumdisplay.php?fid=35

**Comment by Claaw** [comment]
thats the Thing. i can not go into the Forum because it says im banned

**Comment by Nelielu** [comment]
Make a new account on the forum then.
