### ISSUE TITLE
Whipper Root Tuber issue

### ISSUE THREAD

**Issue by Hawelar** [RetroWoW/RetroWoW#167]
**Description**: Item is not added to inventory

**Current behavior**: You apply 3 Cenarion Plant Salves to Corrupted Whipper Root. When you are trying to gather a plant, it disappears without being added to your inventory. Result: minus 3 Cenarion Plant Salve and there is not a single Whipper Root Tuber in your inventory.

**Expected behavior**: You apply 3 Cenarion Plant Salves to Corrupted Whipper Root. Get some Whipper Root Tubers.

**Steps to reproduce the problem**:

1. apply 3 Cenarion Plant Salves to Corrupted Whipper Root
2. try to gather the plant
3. get nothing to your inventory

**Source:**
[Whipper Root Tuber](https://vanilla-wow-archive.fandom.com/wiki/Whipper_Root_Tuber)

**Comment by Mukilian** [comment]
Would love to be able to farm Whipper Roots again on all my characters.

Also big thanks to Hawelar for taking the time to open this issue.

Another idea would be to be able to donate for them.
