### ISSUE TITLE
Immune Trap Reflect

### ISSUE THREAD

**Issue by Senexity** [RetroWoW/RetroWoW#168]
**Description**:

**Current behavior**: When the enemy is using Gyrofreeze Ice Reflector on my Freezing Trap, the reflect has no effect as I am "immune".

**Expected behavior**:  When the enemy is using Gyrofreeze Ice Reflector on my Freezing Trap, the Freezing Trap should land on me.

**Steps to reproduce the problem**:

1. Place Freezing Trap.
2. Use Gyrofreeze Ice Reflector and step on the Freezing Trap.
3. Nothing happens as the hunter is"immune".

**Source:**
As proof, Gyrofreeze Ice Reflector was working properly on Freezing Trap before core update.

**Include Screenshots from the issue if necessary**: 
![Capture d’écran (154)](https://github.com/RetroWoW/RetroWoW/assets/133498850/0fc729fc-9c31-459a-9117-1f09a1a811d5)

**Comment by MrKelzo** [comment]
https://www.wowhead.com/classic/item=18634/gyrofreeze-ice-reflector#comments
