### ISSUE TITLE
Frost Trap LoS Bug

### ISSUE THREAD

**Issue by Senexity** [RetroWoW/RetroWoW#169]
**Description**:

**Current behavior**: My frost trap does not work and disappear if the enemy stepping on it is not in my line of sight.

**Expected behavior**: My frost trap should work when the enemy is stepping on it, irrespective of whether he is in my line of sight or not. Expected behavior of the frost trap should be similar to the freezing trap's one (i.e. no line of sight requirement).

**Steps to reproduce the problem**:

1. Cast frost trap.
2. Get out of line of sight of the enemy.
3. Enemy steps on the frost trap.
4. The frost trap does not work and disappear.

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:
![Capture d’écran (155)](https://github.com/RetroWoW/RetroWoW/assets/133498850/28e1794b-4c01-4ae1-a067-538f8332c8de)

**Comment by MrKelzo** [comment]
This is due our custom LoS.
