### ISSUE TITLE
illiyana Moomblaze and Kelm Hargunth

### ISSUE THREAD

**Issue by samrogueRW** [RetroWoW/RetroWoW#17]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
They aren't selling items like healing potions/bandges
**Expected behaviour**: Tell us what should happen instead
They should sell items like healing potions/bandges but you gotta have some rep to buy these items 
**Steps to reproduce the problem**:

1. go both of the NPCs
2. try to talk to them 
3. and you will find out that they sell nothing

**Include proofs for this behaviour**

http://www.wowhead.com/npc=14753/illiyana-moonblaze#sells
http://www.wowhead.com/npc=14754/kelm-hargunth

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**
https://imgur.com/2DpstGj

**Comment by MrKelzo** [comment]
https://github.com/RetroWoW/RetroWoW/issues/4
