### ISSUE TITLE
channeled aoe through walls

### ISSUE THREAD

**Issue by cahji304** [RetroWoW/RetroWoW#17]
**Description**: Aoe spells usable without line of sight

**Current behaviour**: classes with aoe spells are able to cast them through walls, IE mage blizzard from flag room of warsong gulch down tunnel through the walls.

**Expected behaviour**:  line of sight should prevent this

**Steps to reproduce the problem**:

1. cast down tunnel from Flag room with mage
2. 
3. 

**Source:**

**Comment by Bam27** [comment]
Invalid
