### ISSUE TITLE
Benediction quest bug

### ISSUE THREAD

**Issue by theripler** [RetroWoW/RetroWoW#170]
**Description**:
I completed the "Balance of Light and Shadow", and can't turn in the quest. 

**Current behavior**: Tell us what happens
I, saved 50 folks and the questgiver with the ? above the head. Dosen't happends anything when i try talk to her.
**Expected behavior**: Tell us what should happen instead
i should have being done and get an item. 
**Steps to reproduce the problem**:
i really don't want to do the quest again,, because it's very hard and unfair. 
1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by theripler** [comment]
Now i abandoned the quest for retake it. now i can't it -.-

**Comment by Nemathegreatone** [comment]
If that is the case, open a ticket and we'll take care of it, i'm quite sure the quest is fully working.

**Comment by fuhgawz** [comment]
I have the same issue @Nemathegreatone and i posted a ticket and new issue here on the website. is there anything you can do to assist?
