### ISSUE TITLE
Rogue combo

### ISSUE THREAD

**Issue by Alicca** [RetroWoW/RetroWoW#170]
**Description**: rogue lose combo when he changes target

**Current behavior**: Tell us what happens
When rogue change target he instantly lose his combo on last target

**Expected behavior**: Tell us what should happen instead
He should only lose combo if he hit another target 
**Steps to reproduce the problem**:

1. Attack someone or any npc and get combo point on him
2. Target another player or npc
3. You lose all combos by just targeting someone else

**Source:**
Really hard to find source for it.

 but i think evreyone knows how is it right now its NOT blizzlike and it really fucks up the rogues alot. I stoped doing bgs woth my rogues cuz of that :(

**Comment by xiaoxoxo** [comment]
This is blizzlike, works the same way on the other two popular projects also.

**Comment by Alicca** [comment]
Yeh but losing it when u target friendly targets in duels is retarded bro

**Comment by modnaros** [comment]
This literally was just FIXED, it's not being removed. Deal with it learn to adapt, it's vanilla get over yourself, I had to. Buck up buttercup and all that.

**Comment by Alicca** [comment]
It just makes people happier and happier to see rogues waker. NICE! Its not like this server is full blizzlike to make rogues remove combo points by targeting a FRIENDLY PLAYER
