### ISSUE TITLE
BWL razorgore orb bug again

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#171]
**Description**: Razorgore orb bugs out when you click on it, immediately cancels the channeling, and you get the debuff so you can't grab it again

**Current behavior**: Click orb, immediately cancels, and you get the debuff so you can't channel again

**Expected behavior**: Click on orb, channel, control razorgore

**Steps to reproduce the problem**:

1. Try it, click the orb... happened to us like 4x in a row
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Disable your addons and try again. Works fine to me and there are no other reports about it.
