### ISSUE TITLE
Deviate Eradication quest bugged

### ISSUE THREAD

**Issue by b0ldi** [RetroWoW/RetroWoW#172]
**Description**: https://www.wowhead.com/classic/quest=1487/deviate-eradication This quest in Wailing Caverns is bugged. Quest reward is a BIS belt pattern for lvl 19 twinks, otherwise wouldn't care.

**Current behavior**: If you kill the noted mobs, the quest is not counting it, quest cannot be completed.

**Expected behavior**: If you kill the mobs, the quest is counting it and you can complete the quest.

**Steps to reproduce the problem**:

1. Take the quest
2. Kill the mobs
3. Check if its counting

**Source:**
(https://www.wowhead.com/classic/quest=1487/deviate-eradication)

**Include Screenshots from the issue if necessary**:
![DE quest bug](https://github.com/RetroWoW/RetroWoW/assets/162577878/f4bd01fa-2917-4d9f-92df-29b2273a56e5)

**Comment by Usinggithubcoolguy** [comment]
Make sure you're not in a raid. You won't get quest credit in a raid

**Comment by b0ldi** [comment]
Thank You!
I will check, but that must have been the problem. I was probably in a raid from a previous session.
