### ISSUE TITLE
Six Demon Bag trinket cooldown visual big

### ISSUE THREAD

**Issue by skunkin** [RetroWoW/RetroWoW#173]
**Description**: 30 minute cooldown trinket currently has a visual appearance of a 3 minute cooldown.

**Current behavior**: 30 minute cooldown trinket currently has a visual appearance of a 3 minute cooldown. However even tho it shows as a 3 minute cooldown the item still wont be able to be used for another 27 minutes.

**Expected behavior**: it should visually show as a 30 minute cooldown as opposed to 3 minutes

**Steps to reproduce the problem**:

1. use Six Demon Bag (trinket)
2. see the 3 minute cooldown timer (even though it wont be usable for 30 minutes)
3. should see the full 30 minute cooldown timer

**Source:**
[(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)](https://www.wowhead.com/classic/item=7734/six-demon-bag) says 30 min cd

**Include Screenshots from the issue if necessary**:
![image](https://github.com/RetroWoW/RetroWoW/assets/41055511/90952353-a718-410e-8575-0b01adac0d9c)

**Comment by skunkin** [comment]
![Desktop Screenshot 2024 05 16 - 04 49 04 26](https://github.com/RetroWoW/RetroWoW/assets/41055511/227e6f97-e117-4ed4-aa9c-7db4e1057ba4)

**Comment by skunkin** [comment]
do these even get looked into anymore

**Comment by MrKelzo** [comment]
![image](https://github.com/user-attachments/assets/d657a3f7-eb0a-4ee3-89e1-23948f4f959c)
