### ISSUE TITLE
Plants break line of sight

### ISSUE THREAD

**Issue by ifyousayso** [RetroWoW/RetroWoW#176]
**Description**: Plants break line of sight.

**Current behavior**: Plants break line of sight.

**Expected behavior**: Plants **do not** break line of sight.

**Steps to reproduce the problem**:

1. Select a target behind a tree.
2. Attempt to cast a spell at it.
3. Error.

**Source**:

1. http://wowwiki.wikia.com/wiki/Line_of_sight "Terrain (that is, dirt and trees) only block Line of Sight indoors. All dirt and most trees do NOT block spells or abilities when fighting outdoors."
2. https://us.battle.net/forums/en/wow/topic/2325616793 "Apr 4, 2011" says it's been like that for 6 years.

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
"Custom LoS implemented: LoS will be calculated for M2 objects. (eg barriers, trees in BGs)"
