### ISSUE TITLE
Cannot unstuck with pet summoned

### ISSUE THREAD

**Issue by lance36** [RetroWoW/RetroWoW#177]
**Description**:
Cannot unstuck with pet summoned
**Current behavior**: Tell us what happens
spell channeling is interrupted somehow while pet is summoned. have to dismiss pet for it to work.
**Expected behavior**: Tell us what should happen instead
i get unstucked\teleported back to mall is the expected.
an interrupted spell is what happens
**Steps to reproduce the problem**:

1. be a hunter (dont know if this is valid with other classes aswell)
2.  say .st
3.  get interrupted

**Source:**
playtime

**Comment by Soviethammer** [comment]
Never had any issues with this i have 20 days played on my hunter. Does it happen always or just sometimes?

**Comment by lance36** [comment]
dosent happear to happen if i have a wolf as a summoned pet.
it happens every time if i have a raptor as summoned pet.

**Comment by xiaoxoxo** [comment]
my cast bar disappears but .st still goes off

**Comment by Bam27** [comment]
Please clear your cache files; I have no trouble using the .st command with a pet.

**Comment by Bam27** [comment]
If the bug persists you may post here and I can re-open this issue. :)
