### ISSUE TITLE
I got banned for nothing?

### ISSUE THREAD

**Issue by ninoforthewin** [RetroWoW/RetroWoW#178]
**Description**: Hello, I was fighting in Gurubashi arena, as I was getting killed I teleported to another place. And as I teleported I died and fell through the map, got disconnected and it says my account is banned for some speed tick?

**Current behavior**: I didn't use any cheats, it just happened that I teleported to another place and must've bugged out.

**Expected behavior**: Unban me, please.
account name: ninoforthewin
character name I was banned on: Laserpheet
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by dustin232012** [comment]
I was JUST banned for the same thing, for doing the EXACT same thing.  My character took off running and glitched through the world and next thing I knew.. I was banned??????????
