### ISSUE TITLE
Warlock Pyroclasm talent

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#18]
**Warlock Pyroclasm talent**:

**Current behaviour**: Currently doesn't work at all.

**Expected behaviour**: Should have a chance to stun per Rain of fire, Hellfire tick or Soulfire.

**Steps to reproduce the problem**: Cast any of these spells and there will be no chance at all of this talent proccing.

**Source:**

read talent.

**Comment by robinsch** [comment]
On PTR.

**Comment by Envenom** [comment]
Works on PTR.
May need to check % is working correctly as didn't proc enough for 26% (talents)

**Comment by xiaoxoxo** [comment]
proc chance feels way too low, did some testing just now, out of 200 hellfire ticks it only procced twice vs my alt in duels.. thats with the 2/2 talent (26%)

**Comment by robinsch** [comment]
26% are for a full Hellfire. Proc chance per tick is 26% / tickAmount

**Comment by xiaoxoxo** [comment]
2.6% per tick seems more correct
