### ISSUE TITLE
Disenchanting

### ISSUE THREAD

**Issue by Smlzlikecrit** [RetroWoW/RetroWoW#18]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Unable to loot the disenchanted mats

**Expected behaviour**: Tell us what should happen instead
After disenchanting an item, you should be able to loot the enchanting material from the window, and if you close the window it automatically should loot it into your bags unless you have  full bags then it shouldn't disappear/close until space in the bags has been created

**Steps to reproduce the problem**:

1. Disenchant an item 
2. Try loot the enchanting mats
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MrKelzo** [comment]
Can't find any info about this.
