### ISSUE TITLE
PTR - Sayge and Professor Thadeus Paleo talking too much

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#18]
**Description**:
Sayge and Professor Thadeus Paleo talk too much when you stand near them and flood the chat. 
**Current behavior**: Tell us what happens
Sayge and Professor Thadeus Paleo talk too much when you stand near them and flood the chat. 
**Expected behavior**: Tell us what should happen instead
They should be silent like on the live version to keep the chat clean.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**
<img width="836" alt="image" src="https://user-images.githubusercontent.com/76588473/209824459-5c3e3d2c-30f9-4eaf-8825-d175aba73b69.png">

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
🤣
