### ISSUE TITLE
Shop eats my AP and gives no items, happened x2

### ISSUE THREAD

**Issue by meh326** [RetroWoW/RetroWoW#186]
**NO Items given x2**:

**Current behavior**: All items in my shop say "No Item or Realm specified. And yet if i try spend AP, they are spent, with nothing given to account.

**Expected behavior**: Maybe I could actually use AP and DP????

I spent Ap to get a fang of mystics and also major mana potions x5

**Comment by MrKelzo** [comment]
Open a ticket ingame or on discord. It doesn't take away your DP as long you don't receive anything.
