### ISSUE TITLE
Hunter's Mark and 8/8 Dragonstalker Bonus

### ISSUE THREAD

**Issue by Feltyham** [RetroWoW/RetroWoW#186]
I think there is a bug regarding Hunter's Mark and the 8/8 Dragonstalker Bonus.

If Hunter's Mark is active on a target, the 8/8 bonus will never proc. If the 8/8 bonus is active on a target and you cast Hunter's Mark, the Hunter's Mark replaces the 8/8 bonus debuff. It appears they do not stack and the 8/8 bonus cannot supersede the Hunter's Mark.  

It's been awhile since I've played vanilla and I have no other way of testing this in a different environment. Regardless, I think the two debuffs should stack, however I cannot find a source to confirm this.

**Comment by Simplest1012** [comment]
bump

**Comment by Feltyham** [comment]
I tested this on the new core PTR, huzzah it works correctly on there. 

See the attached screenshot for proof. 
![wowscrnshot_111817_144816 - bug fixed new core ptr](https://user-images.githubusercontent.com/28421439/32984204-fa62c4ea-cc6f-11e7-9f60-8c2d1c11114e.jpg)

Thanks to the developers for giving us the opportunity to test the new core.
