### ISSUE TITLE
Seal of Ascension quest seems not functional

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#188]
**Description**: Seal of Ascension to forge the key for UBRS, when mind controlling Emberstrife and using Flames of the Black Dragonflight (called something like that) it seems to have no impact on the Unforged Seal of Ascension

**Current behavior**: Weaken and mind control Emberstrife, use Flames of the Black flight... nothing happens.

**Expected behavior**: When using Flames of the Black flight, it should forge the seal of ascension and promp the quest to be completed.

**Steps to reproduce the problem**: 

1. Beat Emberstrife to 10%
2. Place the Unforged seal of ascension
3. Use Orb of Draconic Energy to mind control him
4. Use the ability (I believe it was called Flames of the Black Dragonflight) to "forge" and complete the quest

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:
![image](https://github.com/user-attachments/assets/8a6134b0-d6d7-4fd4-8b42-f925a525a356)

**Comment by MrKelzo** [comment]
Clear your cache
