### ISSUE TITLE
Weapon skill NOT BLIZZLIKE

### ISSUE THREAD

**Issue by Hanzemon** [RetroWoW/RetroWoW#188]
**Introduction.**

This will be a long article about the flaws in the current attack table and the mechanics involved, I will briefly touch the current behavior and compare it to the Blizzlike Classic behavior by going deeply into the mechanics involved, Any error or lack of information regarding the current behavior should not be taken too strongly as I will provide the correct behavior that will kick the other into the maelstrom forever.

--------------------------------------------**THE CURRENT BEHAVIOR**-------------------------------------------

Right now the effects of Weapon skill over the Miss chance **against a mob 3 levels higher**  looks like this:

Weapon skill: 300  --->    Chance to miss: 8.60% 
Weapon skill: 301  --->    Chance to miss: 7.96%
Weapon skill: 302  --->    Chance to miss: 7.32% 
Weapon skill: 303  --->    Chance to miss: 6.66% --Hail satan 
Weapon skill: 304  --->    Chance to miss: 6.04% 
Weapon skill: 305  --->    Chance to miss: 5.40%   

_Every 1 weapon skill is reducing 0.64% chance to miss the target, this only occurs when the difference between the mob's defense skill and player's weapon skill is > 10._

Now beyond 305 it changes and the effects of weapon skill over the miss chance against a mob 3 levels higher looks like this:

Weapon skill: 306  --->    Chance to miss: 5.36%
Weapon skill: 307  --->    Chance to miss: 5.32%
Weapon skill: 308  --->    Chance to miss: 5.28% 
Weapon skill: 309  --->    Chance to miss: 5.24%
Weapon skill: 310  --->    Chance to miss: 5.20%
Weapon skill: 311  --->    Chance to miss: 5.16% 
Weapon skill: 312  --->    Chance to miss: 5.12%
Weapon skill: 313 --->     Chance to miss: 5.08% 
Weapon skill: 314  --->    Chance to miss: 5.04% 
Weapon skill: 315  --->    Chance to miss: 5.00% 

_Now every 1 weapon skill reduces the chance to miss the target by 0.04%._

[Table](https://media.discordapp.net/attachments/271013458139414528/344830038807412737/unknown.png?width=766&height=667)

---------------------------------------**INTENDED BEHAVIOR (BLIZZLIKE)**---------------------------------------

**In the original version of World of Warcraft it worked like this:**

--Citing Wow Gamepedia on _Weapon skill_ September 30th 2006.

_For each point that your weapon skill exceeds your opponent's defense, you gain the following:_

_Your chance to miss decreases by 0.04%._
_Your chance to score a critical hit increases by 0.04%._
_Your opponent's chance to block your attack decreases by 0.04%._
_Your opponent's chance to parry your attack decreases by 0.04%._
_Your opponent's chance to dodge your attack decreases by 0.04%._

_Effectively, you can consider weapon skill to be the inverse of the defense skill_. 

Source: [Wow Gamepedia on Weapon Skill  30 September, 2006.](https://wow.gamepedia.com/index.php?title=Weapon_skill&oldid=267725)

-

 **Now, that brings some doubts, it specifies "exceeds". But what about when it's lower?. 
Let's have some more insight:**

--Citing Wow Gamepedia on _Dual wield_ September 6th 2006.

...Take a rogue for example vs. a 63 monster, he has 5%+(0.04% * 15)= 5.6% base miss chance (assuming he has 300 weapon skill and the monster has no special internal Defense skill bonuses),** plus 19% dual wield miss chance, leaving us with a total miss chance of 24.6%.

**We can see it has actually the same effect**

Source: [Wow Gamepedia on Dual wield 6 September, 2006.](https://wow.gamepedia.com/index.php?title=Dual_wield&oldid=236329)

-

**Okay, now we know that the miss chance against a lvl 63 mob at 300 weapon skill is 5.6%  and not 8.6%, but, what does the actual **Attack Table** look like?**

**Let's jump into that:**

--Citing WoWWiki on Attack table October 29th 2006.

_Example 2
Elliot the Rogue is level 60, and is attacking a boss mob along with the rest of his raid group. He has stocked up on all sorts of +crit gear, so his crit chance against the boss mob is a whopping 30%. Since he is dual-wielding, he incurs an additional +19% miss chance on every autoattack swing; and although his +5 weapon skill gear does counter a little bit of this, he did not bring any +hit gear with him, so his miss chance against a boss mob is 24.4%. (+Hit gear doesn't directly increase your chance of a hit; instead, it reduces your chance of a miss.) When he attacks the boss mob from the front, Elliot's attack table looks like this:_

![example 2](https://user-images.githubusercontent.com/32701428/48597024-fc474a80-e931-11e8-8bf1-35bbfc83eda0.PNG)

_Note that despite his nominal "crit chance" of 30%, his miss chance from dual-wielding and his glancing blow chance due to the boss's high level mean that only 19.4% of his attacks are going to be critical hits. This conundrum is sometimes referred to as the Crit Cap -- his chance to crit is capped at 19.4%, so 10.6% of his +crit bonus is wasted._

**Hanzemon: Now we can notice that Elliot's chance to miss is 24.40% instead of 24.60% (5% base + 0.6% Wepskill/Defskill difference + 19% dual wield) this is because as said before he has +5 Weapon skill which reduces his chances to miss by: 5 * 0.04% = 0.20%; now substract it to the total miss chance: 24.60% - 0.20% = 24.40%.** **Let's continue a lilttle further.** 

_Realizing his stupidity, Elliot maneuvers around behind the boss mob to continue his attacks. From behind, a mob cannot parry or block, so Elliot's attack table now looks like this:_

![example 2 1](https://user-images.githubusercontent.com/32701428/48597053-26007180-e932-11e8-8b4c-e2382a8a06d6.PNG)

**And finally but not less important, for yellow attacks**

![image](https://user-images.githubusercontent.com/32701428/48596861-306e3b80-e931-11e8-8b98-63f1be1ff8be.png)

Source: [WoWWiki on Attack table October 29th 2006](http://wowwiki.wikia.com/wiki/Attack_table?oldid=303353)

------------------------------------------------------**EVIDENCE**-----------------------------------------------------

**Now I will show you the post of a player that played World of Warcraft back in 2006.**

--Citing the player Zoroaster member of < The Obsidian Order > from Aggramar server in the forums of WoW Europe.

 **Regarding Avoidance:**

_Dodge, Block and Parry all have a base stat of 5% for mobs. They increase as the mobs Defense becomes higher than your weapon skill at 0.04 per point. Each Mob gains 5 points in defence per level. Block and Parry only apply when attacking from the front. _

_Base miss chance is 5%. If you duel weild your white attacks (auto attacks) suffer a further 19%. All your +hit gear reduces this number. For every point the mob defense is higher than your weapon skill, miss goes up by 0.04. _

**His examples of the Attack table**

_Your yellow strikes (special attacks) aren't that effected by targetting the boss, but your white strikes (auto attacks) all of a sudden are much less damaging. Worse to come - say you have +5% Hit and 25% crit, fresh from farming level 60 mobs..._ 

Yellow (Special) 
5.6% Dodge 
5.6% Parry (0) 
5.6% Block (0) 
0.6% Miss 
24.4% Crit (-0.6 due to weapon/defence differnece) 
58.2% Hit (69.4) 

White (Auto) 
5.6% Dodge 
5.6% Parry (0) 
5.6% Block) (0) 
19.6% Miss 
40% Glancing 
23.6% Crit (24.4) 
0% Hit (10.4) 

Source & complete post (I recommend you to read it): http://web.archive.org/web/20061115223930/http://forums.wow-europe.com/thread.html?topicId=14381707&sid=1

---------------------------------------------GLANCING BLOW DAMAGE----------------------------------------

**To finish let's go over glancing blows real quick**

--Citing Wow Gamepedia on _Weapon skill_ September 30th 2006.

_Glancing Blow chance
The percentage chance of a glancing blow on any melee auto-attack, with either the main hand weapon or the off-hand weapon, is normally agreed to be the following:_

_(NPC’s Defense skill – YOUR Weapon skill – 5) * 3% + 10%_

**_... where "YOUR Weapon skill" is capped at your level * 5._**

**With this formula we can calculate the glancing blow chance very easily, which is 40% against bosses regardless of all the +Weapon Skill bonuses you might have, including racials.**

Source: [Wow Gamepedia on Weapon Skill  30 September, 2006.](https://wow.gamepedia.com/index.php?title=Weapon_skill&oldid=267725).

**Thanks to Killerduki, for debating with me the behavior of the current private servers in comparison with all the data and evidence from retail Classic World of Warcraft** .

-Hanzemon.

**Comment by mentos987** [comment]
That is a lot to read. What exactly is the problem? Do melees do too much or too little dmg to nps'?

**Comment by Hanzemon** [comment]
@mentos987 Chance to miss is 8.6% right now is, instead of 5.6% and Orcs/Humans/Trolls get 3.2% chance to hit from their +5 Weapon Skill racials with Axes/Maces/Swords/Bows.

what +5 Weapon skill should do:
Increase chance to hit by 0.20%.
Increase chance to crit by 0.20%.
Reduce the chance your attacks will be parried 0.20% - Melee Only.
Reduce the chance your attacks will be dodged 0.20% - Melee Only.
Reduce the chance your attacks will be blocked 0.20% - Melee Only.
Reduce the glancing blow damage reduction - Melee Only.

what +5 Weapon skill does:
All that's mentioned in the "should do list".
Increases chance to hit by 3%.

**Comment by Hanzemon** [comment]
@mentos987  bump

**Comment by VovremyaRetroWoW** [comment]
Blue post says the actual miss chance against lvl63 with 300 weapon skill is 9%.
https://classic.wowhead.com/guides/classic-wow-weapon-skills#hit-cap-clarification-blue-post
True table
https://github.com/magey/classic-warrior/wiki/Attack-table#weapon-skill

**Comment by Hanzemon** [comment]
@VovremyaRetroWoW  yes, this is outdated. By the sheer calculations from the wikis what I've posted is true but Classic staff has confirmed the real numbers.
