### ISSUE TITLE
pet attack line of sight

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#19]
**Description**: Cannot send pets on targets that are line of sight

**Current behaviour**: nothing, pet acting like an idiot

**Expected behaviour**: Pet should attack target

**Steps to reproduce the problem**:

1. Send pet on target hiding behind object
2. 
3.

**Comment by robinsch** [comment]
Working fine for me. Can you fraps it?

**Comment by xiaoxoxo** [comment]
Maybe I can show u ingame?
