### ISSUE TITLE
PTR - Hearthstone cooldown - 1 hour.

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#19]
**Description**:
Hearthstone cooldown is 1 hour.
**Current behavior**: Tell us what happens
Hearthstone cooldown is 1 hour.
**Expected behavior**: Tell us what should happen instead
Cooldown should be 5 min like on the live version.
**Steps to reproduce the problem**:

1. Use hearthstone.
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Will be fixed after next restart, clearing cache files is suggested after next restart
