### ISSUE TITLE
Seal of Ascension quest - unable to turn in. 

### ISSUE THREAD

**Issue by Usinggithubcoolguy** [RetroWoW/RetroWoW#190]
**Description**: Completed the quest. The guy, Scarshield Infiltrator/Vaelan, has no dialogue option to turn the quest in. 

**Current behavior**: The NPC "scans you", reveals himself, and then you can chat with him but he only has dialogue bubbles you can click through. 

**Expected behavior**: Unless I'm wildly misinformed, this is the NPC that I turn in the quest, Seal of Ascension, to

**Steps to reproduce the problem**:

1. Have the completed quest
2. Speak to the NPC and try to turn it in
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:
![image](https://github.com/user-attachments/assets/2f4c7012-93b6-402b-846b-18520b5aa7bd)
![image](https://github.com/user-attachments/assets/74e80fb4-d5ff-4d0b-9a41-0352af2fceee)

**Comment by MrKelzo** [comment]
https://github.com/RetroWoW/RetroWoW/issues/188

**Comment by Usinggithubcoolguy** [comment]
Did that... doesn't change anything

**Comment by Usinggithubcoolguy** [comment]
Already tried that... doesn't change anything

Deleted WDB, WTF and disabled all addons. no change
