### ISSUE TITLE
Accidentally returned 2k PVP Token Mail 

### ISSUE THREAD

**Issue by Mystaro02** [RetroWoW/RetroWoW#196]
As I was opening my mail. I accidentally scolled down too far with my mouse and hit RETURN before picking up the 2k pvp token out of my mail slot.

**Current behavior**: The mail returned the item and it was not recovered, checked my account on website and the DP wasn't refunded either :(

**Expected behavior**: Either DP should be returned or Token should be Resent.

**Steps to reproduce the problem**:

1. Opened my mail
2. Clicked Return before I hit the item to grab it
3. Mail Gone

**Source:**

**Comment by oldspices** [comment]
this is not so much a bug but maybe you should post in the normal forums about this

**Comment by Mystaro02** [comment]
I did.  Was told to talk to the founder and no response
