### ISSUE TITLE
Teleporting while in combat results in ban

### ISSUE THREAD

**Issue by buritoo** [RetroWoW/RetroWoW#198]
**Description**:
While in combat ( i was trying to fighting multiple mobs and i was running from them ), teleport out of the zone by using one of the teleport NPCs.
Action will result in ban.

**Current behavior**: Tell us what happens
Well... you will be banned.

**Expected behavior**: Tell us what should happen instead
Die in current location, or not be able to teleport at all.

**Steps to reproduce the problem**:

1.  I was fighting the ogres in tanaris zone
2. Since i was loosing, I wanted to teleport out from the danger
3. I was teleported to selected location as a dead characted, but I was flying..sort of.
4. I was banned.

**Comment by MrKelzo** [comment]
You cannot use the teleport NPC while in combat.
