### ISSUE TITLE
Purge procs Elemental Focus (1/1) aka Clearcasting

### ISSUE THREAD

**Issue by ouroboroz1** [RetroWoW/RetroWoW#2]
Elemental Focus
Instant
Gives you a 10% chance to enter a Clearcasting state after casting any Fire, Frost, or Nature **damage spell**. The Clearcasting state reduces the mana cost of your next damage spell by 100%.

Purge procs elemental focus aka clearcasting - shaman

**Comment by Bam27** [comment]
https://classicdb.ch/?spell=16164

**Comment by MrKelzo** [comment]
Cannot reproduce. Tested 30x+

![image](https://user-images.githubusercontent.com/25086832/41236171-b923cebc-6d90-11e8-8ca9-47b6faf637cb.png)

**Comment by ouroboroz1** [comment]
proof: https://www.youtube.com/watch?v=65JjkWR_yrQ
at 20s and 35s. combatlog lefthand corner
