### ISSUE TITLE
Goblin rocket boots 

### ISSUE THREAD

**Issue by Sunqtt** [RetroWoW/RetroWoW#2]
**Description**: Goblin rocket boots are supposed to be usefull 5 or 6 times maximum. On retro wow they never explode wich make some situation pretty op for instance when a pally is under feedom with boots, or when a druid is with those boots. 5min cd for such a speed is very op. The other boot that increase speed have 30min cd, and even the speed they give is less important than Goblin rocket boots speed effect.

Goblin rocket boots : http://classic.openwow.com/item=7189

**Current behaviour**: Goblin rocket boots never explode

**Expected behaviour**:  Goblin rocket boots should explode with a 20% proc rate

**Steps to reproduce the problem**: Use Goblin rocket boots 

**Source:** 
That very existence of that item is the main source :
 http://www.wowhead.com/item=7190/scorched-rocket-boots

Different comments: 
http://db.vanillagaming.org/?item=7189#wh-comments
https://forum.nostalrius.org/viewtopic.php?f=45&t=7234
http://www.wow-one.com/forum/topic/60698-goblin-rocket-boots-not-xtreme-versions/

**Comment by robinsch** [comment]
@Sunqtt Can you research what should happen to Gnomish Rocket Boots?

**Comment by robinsch** [comment]
And you might find a video. Should the explosion show some kind of visual?

**Comment by Sunqtt** [comment]
Anything i could find regarding Gnomish rocket boots is the visual effect, and its a comment that describe it : http://fr.wowhead.com/spell=12905/bottes-fusees-gnomes#english-comments

He is talking about 1.12 version and saying : These make great riding boots because if you get knocked off the horse, just pop these and run off. when they fail, you get hit with a minor form of conflag (basically blind+fire damage).

I'll keep searching for anything else.

**Comment by Sunqtt** [comment]
Also the existence of can help you with the visual maybe : https://vanilla-twinhead.twinstar.cz/?spell=13158

We learn here a little about the visual, and also that it will cause to drop the flag : http://wowwiki.wikia.com/wiki/Gnomish_Rocket_Boots

**Comment by robinsch** [comment]
I'm missing the following things:

- [ ] Correct time? Can it malfunction at the beginning, at the end, in between?

- [ ] Visual spell

- [ ] Gnomish Rocket Boots?

**Comment by Bam27** [comment]
The boots break[?] several times, giving you a grey item that gives you mats until they finally break for good. They should break one time only. 

Reproduce steps; 
1. Use boots
2. repeat until you break them
3. see grey boots in bag, but item is still equipped on player.
