### ISSUE TITLE
Sweeping Strikes + Whirlwind Doesn't Work Properly

### ISSUE THREAD

**Issue by Ruenkiller** [RetroWoW/RetroWoW#20]
**Current behaviour**: On the new core, sweeping strikes will only hit 1 extra target, once, regardless of how many people whirlwind hit and how many stacks you have left. So if I sweeping strikes whirlwind and hit 4 people, it'll only hit 1 extra target 1 time, even if I have 5 stacks of sweeping strikes. It does, however, work properly with cleave. 

**Expected behaviour**: It should hit the same amount of people the original ability hit. If whirlwind hits 4 different people, sweeping strikes should hit 4 different people, assuming you've got at least 4 stacks of sweeping strikes left.

**Steps to reproduce the problem**:

1. Go to training dummies.
2. Use sweeping strikes.
3. Use whirlwind. Use cleave to verify that it works.

**Include proofs for this behaviour**
I have no proofs of this behavior, I can't find any websites that distinctly state this, but it is common knowledge. It work properly on the old core and it works properly on LH(not entirely but better than this).

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Spell has been changed so many times that I can't find the original spell on either of the sites listed. Not sure if the spell ID would be the same or not. 

**Include Screenshots from the issue if necessary**
![image](https://user-images.githubusercontent.com/35074688/41126942-369c7b36-6a77-11e8-9cce-114e1fc50015.png)
![image](https://user-images.githubusercontent.com/35074688/41126969-4ea67f74-6a77-11e8-87a0-d11c9bd102cd.png)

**Comment by MrKelzo** [comment]
Range for target selection when proccing Sweeping Strikes with whirlwind = 8 yards
