### ISSUE TITLE
Additional on weapon attack/ melee attack DMG from [Equip] items are not effected by spell power

### ISSUE THREAD

**Issue by RamiresMalganis** [RetroWoW/RetroWoW#206]
As on top:

items:
Fiery Retributer
Fiery Plate Gauntlets (tested on my own on retro-wow, but the others are the same effect)
Blazefury Medallion

(6) Apply Aura #42: Proc Trigger Spell  ( SPELL! ) (classicDB)
All three on equip skills are not effected by spell power as they should.

On a spell power up to ~500 + 30 spell dmg weapon enchant the 2 Fire Dmg on Blazefury Medallion
should do around 75 Dmg each hit.

Dunno if its a bug, but probably its a thing you should think about =)

Ty
Ramires

**Comment by MrKelzo** [comment]
It works fine, shouldn't stack at all
