### ISSUE TITLE
Spell Dmg not working on additional melee damage proccs (no invalid report)

### ISSUE THREAD

**Issue by RamiresMalganis** [RetroWoW/RetroWoW#209]
the bug report:
items:
Fiery Retributer
Fiery Plate Gauntlets (tested on my own on retro-wow, but the others are the same effect)
Blazefury Medallion

(6) Apply Aura #42: Proc Trigger Spell ( SPELL! ) (classicDB)
All three on equip skills are not effected by spell power as they should.

On a spell power up to ~500 + 30 spell dmg weapon enchant the 2 Fire Dmg on Blazefury Medallion
should do around 75 Dmg each hit.

Dunno if its a bug, but probably its a thing you should think about =)

Ty
Ramires

the answer
MrKelzo:
It works fine, shouldn't stack at all

the truth:
https://www.youtube.com/watch?v=lWMgNjaQ8Zo
produced by a R14 Rogue on a german live server
same character as on the PvP vid on that channel

just watching on other private server scripts doesnt always give a look on what was really going on
on live 1.12.1

ty 
Ramires

**Comment by MrKelzo** [comment]
Was never supposed to stack. Read the info once more
