### ISSUE TITLE
Sheen of Zanza not useable at all

### ISSUE THREAD

**Issue by drgreed** [RetroWoW/RetroWoW#218]
**Description**: Can't use Sheen of Zanza getting error message

**Current behavior**: Tell us what happens: When I try to drink Sheen of Zanza I get the error message 'The spell is not available to you'

**Expected behavior**: Tell us what should happen instead: I drink Sheen of Zanza and get the Tooltip effect

**Steps to reproduce the problem**:

1. Play Rogue
2. Try to drink Sheen of Zanza
3. 'The spell is not available to you'

**Source:** Item: Sheen of Zanza

**Include Screenshots from the issue if necessary**:

**Comment by mentos987** [comment]
True
