### ISSUE TITLE
Alterac Valley is 20v20 instead of 40v40

### ISSUE THREAD

**Issue by ifyousayso** [RetroWoW/RetroWoW#219]
**Description**: Alterac Valley is 20v20 instead of 40v40

**Current behavior**: Alterac Valley is 20v20.

**Expected behavior**: Alterac Valley should be 40v40.

**Steps to reproduce the problem**:
1. Watch how there are multiple full (20v20) AVs running simultaneously instead of fewer 40v40.

**Source**:

**Include Screenshots from the issue if necessary**:

**Comment by kove400** [comment]
Yes, I have noticed this as well.  Needs to be checked
