### ISSUE TITLE
PTR - Transmog binding items.

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#22]
**Description**:
On the live game version you can use boe item for tmog and after the relog it doesn't bind to your toon.
**Current behavior**: Tell us what happens
When you use BOE item for tmog it binds to your toon.
**Expected behavior**: Tell us what should happen instead
According to the live game version BOE item should not bind to your toon after you make relog.
**Steps to reproduce the problem**:

On the LIVE game version:
1. Use unbinded BOE item for tmog (it should be in your bag). 
2. Right after you used it for tmog it becomes "Soulbound".
3. Relog.
4. Check the item - it should become unbindend and can be transfered to other character.

Repet the same steps on PTR - the BOE item used for tmog will bind to your toon and does not unbind after relog.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Dovlatoff** [comment]
If it needs to be clarified, I can make a video.

**Comment by MrKelzo** [comment]
Vid is not necessary, I do understand the issue

**Comment by MrKelzo** [comment]
We are currently discussing this with the staff members, but for now we all agree that the tmogged items should remain soulbound which is more fair.
