### ISSUE TITLE
Net

### ISSUE THREAD

**Issue by Smlzlikecrit** [RetroWoW/RetroWoW#22]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Item doesn't stack at all

**Expected behaviour**: Tell us what should happen instead
Suggesting to allow them to stack in 10 or 20

**Steps to reproduce the problem**:

1.  Obtain item https://classicdb.ch/?item=835 multiple times
2.  
3. 

**Include proofs for this behaviour**
proof in step 1

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

item=835

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by mollypercoutes** [comment]
As i remember, they didnt stack. Cause they BoP - like unique item, cause you cant stack two uniques.
