### ISSUE TITLE
Account banned cause i got stuck underground with warrio charge

### ISSUE THREAD

**Issue by Gwyndevil** [RetroWoW/RetroWoW#222]
I charged at an enemy and sudenly i was underground falling endlessly got dc and bam account is banned .....

**Comment by Feltyham** [comment]
Hello Gwyndevil,

This part of the forum is for bug tracking, please post in: http://retro-wow.com/forum/forumdisplay.php?fid=35, this is for ban appeals.

Explain what happened there and someone should be able to assist you.
