### ISSUE TITLE
Missing gold, marks of honor taken.

### ISSUE THREAD

**Issue by Mikeyscummie** [RetroWoW/RetroWoW#24]
**Current behaviour**: Yesterday i played some wars and got 10 marks of honor, i turned it in for 1000 gold then played some more games. I logged on the next day and saw my gold was gone and my marks of honors were gone as well still. Basically payed for something that disappeared the next day. I know i got it because i did the quest for it, and i can still do it without paying the 100 pvp tokens. 

**Expected behaviour**: I should've still had the gold on my account, of course i worked for it. 

**Steps to reproduce the problem**:

1. I don't know i am not a developer
2. maybe fix the glitch so i don't have to work for hours just for my work to be poofed away the next day....
3. 

**Include proofs for this behaviour**
I don't know how i can provide proof for this situation, especially since i didn't expect it to happen to me. Maybe theres a way for you guys to check my quest completions? Or some type of log, i have no idea. 
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MrKelzo** [comment]
Do you share your account? & Let me know your account name please.
