### ISSUE TITLE
Channeled spell tracking issue

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#24]
**Description**: Channeled spells do not properly track targets that run through the caster 

**Current behaviour**: The channel is interrupted

**Expected behaviour**: Your character should turn to face the target and continue to cast your channeled spell

**Steps to reproduce the problem**:

1. cast a channeled spell at a target (ex. drain life, arcane missiles, mind flay)
2. have the target run through you repeatedly at close range
3. 

**Source:**

**Comment by xiaoxoxo** [comment]
thx pistom u real mvp for raporting this game breaking bug.

**Comment by robinsch** [comment]
On PTR.

**Comment by Envenom** [comment]
Working on PTR
