### ISSUE TITLE
Lost account

### ISSUE THREAD

**Issue by Zupeex** [RetroWoW/RetroWoW#253]
**Description**:
Lost account
**Current behavior**: Tell us what happens
I didn't play for a couple of years and now I lost the Email one of my accounts were binded to.
I know one of my main character name on the server but I forgot the password. 
I know the account also.
**Expected behavior**: Tell us what should happen instead
Please help me get my account back.
**Steps to reproduce the problem**:

1. 
2. Why would I wanna reproduce the problem ? 
3. 

**Source:**
Don't Understand this one, sorry. 

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please contact me @Discord (Kelzo)
