### ISSUE TITLE
banned (?)

### ISSUE THREAD

**Issue by skybacks** [RetroWoW/RetroWoW#255]
Hello to the retro team - wow

I was banished approximately 1 week ago because of a priest who hack in warsong with the spell "Mind Control " and makes for us float in air so that the players are detected by anti-cheat.
I do not know to whom to send to me, I already have to send a few days ago an e-mail on "information retrowow@gmail.com" without results.
I would have wanted to write on the forum but as I am banished I is not there any more access, I am a little lost.

I hold really enormously my account, many hours ago of game(set,play) and to be banished because of somebody else is really frustrating.
Especially that I me invested(surrounded) a lot in the community and I love the server.

Thank you to have taken time to read to me and I apologize for posting this e-mail on the bad place(square), I don't know what to do anymore.
If somebody little to pass on(transmit) him(it) in good one(maid) people or at the right place.

I give you my account : "dyroth" 

Cordially.

**Comment by Alicca** [comment]
This is not the place to make bann appeal, go to the forum and make bann appeal not in a bug report

**Comment by skybacks** [comment]
Hello and thank you for your answer.
I shall have like I can post my e-mail on the forum but as I am banished I cannot.
When I go on the forum, I have this message " I'm sorry, but you are banned. You may not post, read threads, or access the forum. Please contact your forum administrator should you have any questions."
And I cannot contact the administrator. I am to block . . . 
How I can make to recover, my account, if I cannot go any more on the forum?

**Comment by Alicca** [comment]
Change your IP usually this bug gets fixed by it self later but to post on the forum from the same account you need to change your ip or get a VPN (be aware from viruses links while u looking^^)

**Comment by Alicca** [comment]
U arent actullay banned on the forum its just a bug that happenes for unknown reasson, all u need to do os change IP and later try ur old ip maybe it get fixed randomly like it usually do

**Comment by skybacks** [comment]
It's good !! i have my account ;)
Thx for help Alicca !!

**Comment by Alicca** [comment]
Yw'ed anytime^
