### ISSUE TITLE
item

### ISSUE THREAD

**Issue by mohrog** [RetroWoW/RetroWoW#256]
**Description**: i bought an item on the site but i didn't know i had to pick the character aswell, so it went to the wrong one, may i redirect it or something like that??

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please open a ticket ingame.
