### ISSUE TITLE
I donted and it sent it to the wrong char :(

### ISSUE THREAD

**Issue by knicknack11** [RetroWoW/RetroWoW#257]
**Description**:
I bought 4k of pvp tokens and a shaman mace and it was sent to my rogue :(

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. send it to trollonmydik
2. 
3. 

PLEASE REMOVE THEM FROM RECONDO EMAIL AND SEND THEM TO TROLLONMYDIK EMAILS.

**Comment by MrKelzo** [comment]
Please open a ticket ingame.
