### ISSUE TITLE
Bug with Charecter

### ISSUE THREAD

**Issue by Kakyza** [RetroWoW/RetroWoW#258]
**I cant to enter Molten Core dungeon**:

**I cant enter MC system write me: You have entered too many instances recently. And then i cant enter any dungeon. After relog system teleport me in <The Masonary>**: Tell us what happens

**I should to enter in dungeon and dont teleport in <The Masonary> after relog**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. I cant raiding and enter any dungeon
2. And this problem have all my characters on account
3. I dont know what i should to do

**Source: Help me pls T-T**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
"As of Patch 1.9 or so, players are limited to entering 5 instances per hour."
Source: https://vanilla-wow.fandom.com/wiki/Instance_limitations
