### ISSUE TITLE
Thunderfury proc deals damage to only 1 target instead of up to 5.

### ISSUE THREAD

**Issue by InanBlack** [RetroWoW/RetroWoW#258]
**Description**:
As stated in title. The Item's tooltip clearly hints that the proc will affect up to 5 targets
if they are in melee range.

**Current behavior**:
The item procs applying 2 debuffs and dealing damage to the main target, and applying 1 debuff to 
other targets *as intended*, but deals no damage to the other targets/the lightening isn't jumping, like it's stated in the tooltip/*is intended*.
 
**Expected behavior**: 
The item procs applying 2 debuffs on main target and 1 debuff on all targets in melee range, and the lightening jumping targets, damaging up to 5 of them.

**Steps to reproduce the problem**:

1. Engage in combat with the Target Dummys in Hyjal.
2. Wait for Thunderfury to proc.
3. Notice that only one target will take damage.

**Source:**
Tested personally. 

P.S. Thunderfury is a iconic weapon of vanilla, and having a bug like this discurages most players  spending more time playing to get this weapon or eventually donating and supporting the project.

Sorry if this is a repost, couldn't find anything related on BugTracker.

**Comment by Retnoab** [comment]
Working as intended http://db.vanillagaming.org/?spell=21992

**Comment by hollowtipz2123** [comment]
@Retnoab the tooltip states that 5 targets are affected, would this not also mean that damage also "jumps" to the additional targets?
