### ISSUE TITLE
Pet slowed

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#26]
**Description**: In pvp if owner is under cc effect or slow effect, pet will run slower than normal(if using pressing pet follow)

**Current behaviour**: Pet is running slowly

**Expected behaviour**:  Should run normal speed

**Steps to reproduce the problem**:

1.  get cced, press pet follow key
2. get slowed, get cced, press pet follow key
3.

**Comment by Phocus26** [comment]
A note on this, it also appears that your pet is slowed by default when you summon him.  You must command him to follow, then send him to attack again for him to move at full speed.

**Comment by robinsch** [comment]
On PTR. Note: Pets inherrit owners speed when not in combat.

**Comment by Soviethammer** [comment]
This still dont work on live. Thanks
