### ISSUE TITLE
Broken Tooth

### ISSUE THREAD

**Issue by Euphemistic** [RetroWoW/RetroWoW#263]
**Description**: Broken Tooth is not classified as a beast, in fact he is not classified as anything. It just says Broken Tooth Level 37 with no classification, and therefore cannot be tamed by hunters.

![brokentoothbug](https://user-images.githubusercontent.com/31416279/29785474-5a6d157a-8bed-11e7-96f1-2d175d643df6.png)
**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by kamiyo1230** [comment]
Delete files in WDB folder and then it will be fixed.

**Comment by Euphemistic** [comment]
Ah, tyvm worked like a charm.
