### ISSUE TITLE
Succubus

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#27]
**Description**: Succubus not able to use spell "Seduction" while having the lesser invisibility buff on.

**Current behaviour**: Pet will continue being stealthed and auto attacking target

**Expected behaviour**: Pet should leave stealth and use Seduction if that spell is being pressed.

**Steps to reproduce the problem**:

1. Send stealthed succubus to seduce enemy player
2. 
3. 

**Source:**

**Comment by robinsch** [comment]
On PTR.
