### ISSUE TITLE
PTR - Epic Mounts Vendor Items Missing ALLIANCE SIDE

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#27]
**Description:**
The following mounts are missing from the Epic Mounts vendor:

- White Mechanistrider
- Palomino Bridle
- Reins of the Nightsaber
- White Stallion Bridle
- Black Ram
- Icy Blue Mechanostrider
- Reins of the Ancient Frostsaber
- Frost Ram

**Current behavior: Tell us what happens**
These mounts should be obtainable for 1k gold each.
**Expected behavior: Tell us what should happen instead**
There are no such mounts.
**Steps to reproduce the problem:**

1. Create Gnome character.
2. Check the Epic Mounts vendor.

Source:

Include Screenshots from the issue if necessary:

**Comment by MrKelzo** [comment]
White Mechanistrider = Swift White Mechanostrider
Reins of the Ancient Frostsaber = Reins of the Frostsaber

Item names are bit different, but its the same item, rest is fixed. Thanks for your report

**Comment by Dovlatoff** [comment]
> White Mechanistrider = Swift White Mechanostrider Reins of the Ancient Frostsaber = Reins of the Frostsaber
> 
> Item names are bit different, but its the same item, rest is fixed. Thanks for your report

Sorry, it's my fault.
It's not White Mechanostrider, but it's **White Mechanostrider Mod A**

And it looks like that items are different.
**White Mechanostrider Mod A**
<img width="357" alt="image" src="https://user-images.githubusercontent.com/76588473/209856247-eb4ca57d-d924-49c7-826c-595854fe7948.png">
**Swift White Mechanostrider**
<img width="399" alt="image" src="https://user-images.githubusercontent.com/76588473/209856294-0ee69906-115d-498a-a32d-712096c55b41.png">


The same applies to Frostsabers:
**Reins of the Ancient Frostsaber**
<img width="517" alt="image" src="https://user-images.githubusercontent.com/76588473/209856405-02268751-a61b-4a8a-9cdf-c5dab65c6051.png">
**Reins of the Swift Frostsaber** (sadly, I could not find "Reins of the Frostsaber" at vendor, so I think you were refering to "Reins of the Swift Frostsaber")
<img width="518" alt="image" src="https://user-images.githubusercontent.com/76588473/209856619-140cfb41-82eb-4230-bf91-be39a0d8e703.png">

**Comment by Dovlatoff** [comment]
So, if it's possible, please, consider adding **White Mechanostrider Mod A** and **Reins of the Ancient Frostsaber** to the vendor. These mounts are unique and obtainable from this vendor on the live version.

**Comment by MrKelzo** [comment]
I will check this today

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/209976375-92a1a9e8-3d29-44a1-a3a3-3c9819364f43.png)
![image](https://user-images.githubusercontent.com/25086832/209976492-fd8ab57d-88ea-4819-ac71-4d54a7988831.png)

Swift White Mechanostrider are the same on both realms

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/209976727-8fddc87c-e921-4b84-96ab-edc3847c0fb9.png)
![image](https://user-images.githubusercontent.com/25086832/209976753-1f18ac2f-f4c8-4041-913d-ebaba7889bd1.png)
White Mechanostrider Mod A is also the same on both realms

**Comment by MrKelzo** [comment]
Reins of the Frostsaber is also added to the vendor, renamed into Reins of the Ancient Frostsaber just like on live. Its the same item & model but the name was different.
