### ISSUE TITLE
Pyroclasm talent

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#28]
**Description**: Proc chance way too low, atleast with hellfire

**Current behaviour**: Procs 2 times over 200 hellfire ticks with 2/2 talent (26%)

**Expected behaviour**: Should proc more often?
**Steps to reproduce the problem**:

1.  Hellfire target
2. 
3. 

**Source:**

**Comment by robinsch** [comment]
Read law of large numbers
