### ISSUE TITLE
Gnomish Death Ray bug

### ISSUE THREAD

**Issue by fullmetalpanic** [RetroWoW/RetroWoW#280]
**Description**: Gnomish Death Ray is doing so little dmg 

**Current behavior**: when you charge up the deathray you take 73 or 80  damage per second the charged death ray hits for 428 and i cant critical strike i even tried it with recklesness

**Expected behavior**: it should drain up to 300-350 hp on a war with ~5000 hp and hit for like 4k on crits also it should have the ability to crit based upon your characters critchance

**Steps to reproduce the problem**:

Make yourself a Gnomish Death Ray and then watch the 428 hits

**Source:**

http://db.vanillagaming.org/?item=10645#wh-comments 

https://www.youtube.com/watch?v=VWO-Idi0KX4
https://www.youtube.com/watch?v=leoK-k0AP2g

**Comment by muted45** [comment]
I agree. Is there no resolution to this yet?

**Comment by MrKelzo** [comment]
Fixed on PTR
