### ISSUE TITLE
Never got verification email

### ISSUE THREAD

**Issue by cuppaper** [RetroWoW/RetroWoW#283]
**Description**:Never got the email looked everywhere....all email folders  spam inc. I made a new account with a diferent email and still no email

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
open a valid email address and try again.
