### ISSUE TITLE
Crash upon login

### ISSUE THREAD

**Issue by Jcorbett5585** [RetroWoW/RetroWoW#286]
When I log into my warlock Unpleasant, I am unable to take any action except for moving around, and about 30 seconds or so after the client crashes. All other characters on the account work and can login/interact with the game as intended. Nothing has changed to my knowledge aside from joining a guild, but I do not see how that could have any influence.

I have already tried the in game stuck feature (which I was able to use, although it did not remedy the problem) any input/assistance is thankfully welcome.

**Comment by Zegzamzuzu** [comment]
This is Zegzamzuzu, and my account is doing the same thing. Hopefully they will be able to fix it or I will not be able to play anymore.
