### ISSUE TITLE
Druid Hibernate not working on hunter pets.

### ISSUE THREAD

**Issue by Archaureous** [RetroWoW/RetroWoW#29]
**Current behaviour**: In pvp matches and duels as a druid, i am unable to use hibernate on hunter pets, as they do not have the qualification of beast, the spell says invalid target.

**Expected behaviour**:  The spell hibernate should at the least begin to cast on a hunter pet, but they need the qualification of beast for it to work.
**Steps to reproduce the problem**: Try to hibernate any hunter pet in a pvp scenario.

**Include proofs for this behaviour** Screenshot of Hunter pet having no qualification for type of mob.
![wowscrnshot_060818_000307](https://user-images.githubusercontent.com/40053854/41143778-77d912e8-6aaf-11e8-8c2e-b65222a03d99.jpg)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills** Im sorry, I could not find the spell id for Hibernate, druid balance skill, all ranks 1-3.

**Include Screenshots from the issue if necessary** Screenshot of invalid target on enemy hunter pet while trying to cast hibernate, as the pet should be a beast, it would normally work.
![wowscrnshot_060718_235620](https://user-images.githubusercontent.com/40053854/41143731-40581f30-6aaf-11e8-8f6e-21986d2a101e.jpg)

**Comment by MrKelzo** [comment]
Works fine, please close your client and clear your WDB folder (Cache)

![image](https://user-images.githubusercontent.com/25086832/41228093-69bb88ce-6d77-11e8-92a3-340a510d103d.png)
