### ISSUE TITLE
PTR Duel Reseting Cooldowns for Sayge

### ISSUE THREAD

**Issue by Funnie1** [RetroWoW/RetroWoW#29]
**Description**: On PTR DuelMod is no longer resetting Sayge's 2hr internal CD like on live servers

**Current behavior**:  .Duel on & dueling another character to reset cooldowns no longer resets sayge's cd

**Expected behavior**: Reset Sayge CD

**Steps to reproduce the problem**:

1. .Duel on & pick up a sayge buff
2. Duel another character
3. Interact with Sayge

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
This is not a bug, the duel reset now only resets player CDs.
