### ISSUE TITLE
Force Reactive Disk

### ISSUE THREAD

**Issue by hollowtipz2123** [RetroWoW/RetroWoW#290]
**Description**:
No damage from blocking with force reactive disk.

**Current behavior**: Tell us what happens
Animation goes off, but there is no accompanying damage that proceeds animation.

**Expected behavior**: Tell us what should happen instead
Animation should trigger, along with lightning (nature) damage to all surrounding enemies.

**Steps to reproduce the problem**:

1. Equip [Force Reactive Disk]
2. gather group of mobs
3. upon block or multiple blocks, witness animation trigger with no damage.

**Source:**
https:/db.vanillagaming.org/?item=18168

**Comment by Smlzlikecrit** [comment]
Force Reactive Disk works in the new core. It has been tested.
New core is on it's way shortly, a bit more patience is just required.

Thread can be closed
