### ISSUE TITLE
Password Validation and Length

### ISSUE THREAD

**Issue by Domedz** [RetroWoW/RetroWoW#293]
**Description**: 

You web site allows you to set an account password that can not actually be used to login to the WoW client due to the length of the password.

**Current behavior**: 

You can create a password greater than 16 characters even though the limit on the password field of the WoW client is 16 characters.

**Expected behavior**: 

The web site should limit the password to 16 characters or less.

**Steps to reproduce the problem**:

1. Create a password greater than 16 characters
2. Attempt to login to WoW client 
3. Notice you cant type more than 16 characters into the password field

**Source:**

Me - new user joining

**Include Screenshots from the issue if necessary**:

Try it

**Comment by MrKelzo** [comment]
You can change your password from the UCP, reload the page in case you get an error.
