### ISSUE TITLE
Not Receiving Email to Finish Account Creation

### ISSUE THREAD

**Issue by Bosshog51** [RetroWoW/RetroWoW#295]
**Description**: Not receiving the email to complete the account creation.

**Current behavior**: Not receiving the email to finish the account creation.

**Expected behavior**: I should be receiving the email with the link to complete the account registration.

**Steps to reproduce the problem**:

1.  Tried to re-create an account, but came up with the same problem.
2. Tried the same thing with a different email address, but had the same issue.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please check your spam folder.

**Comment by Bosshog51** [comment]
It ended up coming after a few hours but lmao thanks for the advice! Never
thought to check there!!!!!!!
