### ISSUE TITLE
New Core: Quest item drop % incorrect

### ISSUE THREAD

**Issue by Smlzlikecrit** [RetroWoW/RetroWoW#296]
**Description**: An quest item that should be 100% drop chance whilst on the quest.
Quest: Fiery Blaze Enchantments    ID: 706
Quest Item: Black Drake's Heart      ID: 4612

**Current behavior**: Quest item does not drop.

**Expected behavior**: Quest item should be 100% drop chance while on the quest

**Steps to reproduce the problem**:

1. Accept quest Fiery Blaze Enchantments (quest=706) quest from Sigrun Ironhew (npc=2860) 
2. Kill either Scalding Whelp (npc=2725) or Scorched Guardian (npc=2726).
3. Notice no quest item 

**Source:** 
http://db.vanillagaming.org/?quest=706
http://db.vanillagaming.org/?item=4612
http://db.vanillagaming.org/?npc=2726
http://db.vanillagaming.org/?npc=2725

Regards
-Smlzlikecrit

**Comment by MrKelzo** [comment]
Report here; https://github.com/RetroWoW/PTR/issues
