### ISSUE TITLE
Guild Creation Error

### ISSUE THREAD

**Issue by FrugoUnderhill** [RetroWoW/RetroWoW#297]
**Description**:
I have a guild charter signed by 10 accounts
The "register Guild Charter" option from the guild master in ORG does nothing.

**Current behavior**: Tell us what happens
I click the register guild charter and nothing happens

**Expected behavior**: Tell us what should happen instead
The guild should be created

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please close wow and remove your WDB folder (cache files) and try again.
