### ISSUE TITLE
New Core: Item: Skullforge Reaver

### ISSUE THREAD

**Issue by Smlzlikecrit** [RetroWoW/RetroWoW#297]
**Description**: The second part of the proc doesn't work. 
"Chance on hit: Drains target for 2 Shadow damage every 1 sec and transfers it to the caster. Lasts for 30 sec." 

**Current behavior**: Upon the proc, the damage to the target is inflicted.

**Expected behavior**: Upon the proc, the specified damage should be inflicted (which it is), AND the damage inflicted should be transferred to the caster, which it is not.

**Steps to reproduce the problem**:

1. Buy Skullforge Reaver
2. Attack NPC/target/mob, wait for proc
3. Damage is inflicted; healing not received

**Source:**
http://db.vanillagaming.org/?item=13361

**Comment by MrKelzo** [comment]
Report here; https://github.com/RetroWoW/PTR/issues
