### ISSUE TITLE
Account creation not working

### ISSUE THREAD

**Issue by BEAMZY** [RetroWoW/RetroWoW#298]
**Description**: Not receiving the email to complete the account creation.

**Current behavior**: Not receiving the email to finish the account creation.

**Expected behavior**: I should be receiving the email with the link to complete the account registration.

**Steps to reproduce the problem**:

1. Tried to re-create an account, but came up with the same problem.
2. Tried the same thing with a different email address, but had the same issue.
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please check your Spam folder.
