### ISSUE TITLE
New Core: Onyxia Raid

### ISSUE THREAD

**Issue by hotrod67** [RetroWoW/RetroWoW#298]
**Description**:
Everything about the fight on the PTR is scripted excellent except the disorientation.
**Current behavior**: Tell us what happens
Around midway through the fight with Onyxia she will fly into the air and shoot down fireballs disorientating everybody it hits, it seems though as if it triggers and she does it to often as there have been moments where a 5 second disorientation has turned into 15 almost always causing a wipe.
**Expected behavior**: Tell us what should happen instead
The disorientation should still happen as scripted but not as often.
**Steps to reproduce the problem**:

1.  Get a 5 man group together
2. Enter Onyxia Liar
3. Fight her until she flys until the air and starts to disorientate.

**Source:**

**Comment by MrKelzo** [comment]
Report here; https://github.com/RetroWoW/PTR/issues
