### ISSUE TITLE
bloodfang chest

### ISSUE THREAD

**Issue by holyrogue1** [RetroWoW/RetroWoW#299]
**Description**:
i was clicking to get a bloodfang chest it worked but its not in my inventory
**Current behavior**: Tell us what happens
i was clicking to get a bloodfang chest it worked but its not in my inventory. and again i clicked boss but its not working.....
**Expected behavior**: Tell us what should happen instead
can u check plz? T.T
**Steps to reproduce the problem**:

1.  I was clicking to get a bloodfang chest
2. it worked but its not in my inventory.
3. and again to check, i clicked boss but its not working.....

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please open a ticket ingame.

**Comment by holyrogue1** [comment]
How to open a ticket??
