### ISSUE TITLE
Improved Ambush

### ISSUE THREAD

**Issue by roughanal** [RetroWoW/RetroWoW#3]
**Description**: Improved Ambush

**Current behaviour**: Improved Ambush is supposed to increase ambush crit to 95% 

**Expected behaviour**: Crit chance doesn't change

**Steps to reproduce the problem:**

1. look at talent tree
2. add points 
3. look in spellbook to see if ambush changed

**Source:** 
![imp ambush](https://cloud.githubusercontent.com/assets/25257380/22169724/71d9ecac-df44-11e6-8d7d-63048bfde540.jpg)

**Comment by Sunqtt** [comment]
It could be a visual bug, i was ambush spec once and i dont remember having such a low crit chance. You need to have an addon that show the crit chance and ambush a dummy 100 or 200 times i think

**Comment by robinsch** [comment]
Reopen if crit is actual bugged. Tooltips don't get updated.

**Comment by roughanal** [comment]
it updates for improved backstab why wouldnt it update for improved ambush

**Comment by roughanal** [comment]
anyhow was tryin to help out thats all
