### ISSUE TITLE
improved sprint

### ISSUE THREAD

**Issue by mcgankinston** [RetroWoW/RetroWoW#3]
with the talent "Improved Sprint" the rogue is removed from all slows and is supposed to give immunity to slows/snares for .5s after the use of sprint. on the new core this is not a thing. i belive this is a big deal because with mages having the frostbite talent and ice armor giving consistant slows. improved sprint is essentially useless seeing that the rogue is very easily slowed immediatly after the use. in many cases frostbite will proc right as the rogue uses sprint. overall a very annoying bug that ruins mage vs rogue please fix thank you

**Comment by samrogueRW** [comment]
It should work like Mages blink where it gives you a buff for immunity to stuns for 0.5 sec aswell.
but you need a prove of it Mcgank.

**Comment by MrKelzo** [comment]
Works fine to me.
