### ISSUE TITLE
PTR - ALLIANCE/HORDE Battle Standard

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#30]
**Description**:
https://classicdb.ch/?item=18606
https://classicdb.ch/?item=18607
These two items are not obtainable in the live game, but are available on PTR. They increase health of all nearby party members.
**Current behavior**: Tell us what happens
You can get these items and use them not only on Battlegrounds as it is stated in the item description, but in raids as well.
**Expected behavior**: Tell us what should happen instead:
Either these items should be removed or their effect should be turned off for everything except battlegrounds.
**Steps to reproduce the problem**:

1. Buy them from https://classicdb.ch/?npc=12781 or https://classicdb.ch/?npc=12793
2. Go to any raid.
3. Use them.

**Source:**
<img width="242" alt="image" src="https://user-images.githubusercontent.com/76588473/209859570-ed6b34f7-10de-4232-94a7-9b91cc6b8ae9.png">

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/76588473/209859474-449d6c42-5696-471e-bdc3-15b0d2a38784.png">

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
These 2 were disabled on live. Will be disabled on PTR as well. AV ones still work fine.
