### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Randomoon** [RetroWoW/RetroWoW#304]
**Description**:
banned for bug in game
**Current behavior**: Tell us what happens
when yeti killed me i teleport in cursed island and on cursed island I on my corpse fly in orgrimmar I can't not my manage i just fly in orgrimmar and i try 
respawn,I doing that and I take off.
**Expected behavior**: Tell us what should happen instead
I should not be banned
**Steps to reproduce the problem**:

1. I can't not loggin in accaunt
2. I was banned
3. 

**Source:**
bug,I NEVER not use cheats
**Include Screenshots from the issue if necessary**:
https://user-images.githubusercontent.com/50950670/58249527-d038d600-7d67-11e9-8289-1857d9831f1c.png

**Comment by sethdubs** [comment]
Proper place to appeal bans is https://retro-wow.com/forum/forumdisplay.php?fid=35
