### ISSUE TITLE
bug with firemag boss he disepard with my loot!!

### ISSUE THREAD

**Issue by capoqb** [RetroWoW/RetroWoW#305]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by capoqb** [comment]
boss disaperd firemag with my trinket!!

**Comment by MrKelzo** [comment]
Please open a ticket ingame.
