### ISSUE TITLE
Won't connect except constant disconnect

### ISSUE THREAD

**Issue by Wolfyz** [RetroWoW/RetroWoW#309]
**Disconnecting**:

**Current behavior**: Won't let me log on disconnecting

**Expected behavior**: Should be able to log on help please
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Nemathegreatone** [comment]
Open your realmlist.wtf file and copy these two lines:

set realmlist logon.retro-wow.com
set realmname "RetroWoW"
