### ISSUE TITLE
PTR ZG Buff & Zanza Potions no longer persist through death

### ISSUE THREAD

**Issue by Funnie1** [RetroWoW/RetroWoW#31]
**Description**: ZG buff & Zanza pots no longer persist through death

**Current behavior**: ZG Buff & Zanza pots no longer persist through death

**Expected behavior**: I believe they're both intended to persist through death like on live?

**Steps to reproduce the problem**:

1. Pick up buffs
2. Die
3. Buffs dont last through death 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by kurtosmurtos** [comment]
The Spirit of Zandalar will no longer persist through death.  It can be found in the 1.11 patch notes https://vanilla-wow-archive.fandom.com/wiki/Patch_1.11.0. It is possibly for this reason that they are different. The patch notes do not mention zanza potions however. Event though retro runs on 1.12 both the zanza pots and the ZG buff should persist through death,  as I am sure it was a custom change by Retro wow. And therefore should remain as they are on the live server with the same requirements at the moment.

**Comment by kurtosmurtos** [comment]
![Screenshot (181)](https://user-images.githubusercontent.com/112797709/209867378-86de826c-ded5-42d0-9c55-edf7acd529dd.png) Also I can confirm. I drank a zanza pot, fell and died. It can be seen on the combat log. And if you look in the top right corner of the picture, there is no Swiftness of zanza

**Comment by MrKelzo** [comment]
I can't remember if we changed it back then. Will check it tomorrow.

**Comment by MrKelzo** [comment]
Made it just like on live
