### ISSUE TITLE
Rank bug

### ISSUE THREAD

**Issue by DenislavLichev** [RetroWoW/RetroWoW#312]
**Description**: My char rank bug

**Current behavior**: I have 530 honorable kills and still my rank is 0.

**Expected behavior**: 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by DenislavLichev** [comment]
ACC : Faultless
CHAR : Denislav

**Comment by MrKelzo** [comment]
The honor ranks are getting updated once a week (Wednesday morning)
