### ISSUE TITLE
Teleporter npc bug

### ISSUE THREAD

**Issue by scrapready** [RetroWoW/RetroWoW#315]
**Description**:

Every single time I talk to teleporter NPC, I am instantly teleported to Gurubashi Arena.

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

I want to use the teleporter as normal.

**Steps to reproduce the problem**:

1. It happens every time on every character.
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please disable your addons and try again.
