### ISSUE TITLE
I cant log into my account, on the website or the game

### ISSUE THREAD

**Issue by Staviat** [RetroWoW/RetroWoW#316]
I try to log in on the website and it says invalid email or password, and then i try to request password reset and it sends me to a page 
![retrowtf](https://user-images.githubusercontent.com/34897979/34393543-3bef449a-eb21-11e7-96d3-40eb749989a9.jpg)
 and says an email has been sent to me and im not getting an email

**Comment by Staviat** [comment]
Now it is letting me log into game, but not the website...

**Comment by Staviat** [comment]
also getting message "An email has been sent to you with further information. Please check your inbox to proceed. " but im not receiving an email. sectil@yahoo.com

**Comment by Nemathegreatone** [comment]
Hello.

The website password recovery is working normally, again.
