### ISSUE TITLE
The Savior of Kalimdor

### ISSUE THREAD

**Issue by shidden** [RetroWoW/RetroWoW#319]
**Description**:  I can´t complete the quest The Savior of Kalimdor

**Current behavior**: Tell us what happens
Can´t talk to the NPC
**Expected behavior**: Tell us what should happen instead
Nothing
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Nemathegreatone** [comment]
Press "C", click on Reputation tab, and uncheck "At war" box.
