### ISSUE TITLE
Blessing of might/kings getting dispelled by wind fury totem. 

### ISSUE THREAD

**Issue by kamil87** [RetroWoW/RetroWoW#32]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Blessing of might and blessing of kings are getting dispelled by Wind Fury Totem. 
**Expected behaviour**: Tell us what should happen instead
You should not be dispelled by the totem when the weapon effects is refreshed.
**Steps to reproduce the problem**:

1. Make a fresh Pala and a fresh shaman and group them up
2. Buff the pala with either king or might then use wind fury totem 
3. Look up for your might / king that will disappear as soon as wind fury is refreshed, you can buff yourself for like 4 seconds before the totem kicks in again. (works as well on any other class with the might buff that receive wind fury totem enhancement)

**Include proofs for this behaviour**
I think it's pretty self explanatory. 
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MrKelzo** [comment]
They simply don't stack. Not a bug.
