### ISSUE TITLE
PTR - You can learn more than 2 primary professions

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#32]
**Description**:
Being an Engineer + Blacksmith, I've successfully learned Herbalism and Leatherworking.
**Current behavior**: Tell us what happens
You can know more than 2 professions.
**Expected behavior**: Tell us what should happen instead
The game should not allow you to learn new professions when you already know 2 of them.
**Steps to reproduce the problem**:

1. Visit trainers and learn professions, no matter if in a profession zone or in the world.
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/76588473/209865278-18d483e8-989d-49c6-a906-b2eafff26970.png">

**Comment by kurtosmurtos** [comment]
Try to unlearn your ALL of your professions (your 2 maxed out ones and the new 2 ones). This could be a bug because your logged onto your old character on the PTR. Or it is indeed an issue.

**Comment by Dovlatoff** [comment]
> Try to unlearn your ALL of your professions (your 2 maxed out ones and the new 2 ones). This could be a bug because your logged onto your old character on the PTR. Or it is indeed an issue.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/76588473/209867215-76f8cad9-bbe6-43ce-a895-dbfdda4c6e3a.png">
This is new character that was created after the PTR went live.


____________
By the way, even if it were a bug related only to old characters, it would still be unfair and need a fix because the new players won't be able to get more than two professions.

**Comment by MrKelzo** [comment]
It was set to max since I was testing all and forgot to revert, should be fixed now.
