### ISSUE TITLE
Raid locks

### ISSUE THREAD

**Issue by Kimdamien** [RetroWoW/RetroWoW#320]
**Description**: All my chars are still locked in BWL and MC

**Current behavior**: All my chars are locked in BWL/MC after reset.

**Expected behavior**: They should not be locked in BWL/MC after reset :)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by thepilot324** [comment]
i'm also saved instantly to ony/mc after raids reset. seeing a lot of other people through world chat/discord having this problem too

**Comment by frooshen** [comment]
Hello
Raid ID
358 (molten core) my char is still saved. This is the second time the character is still saved after the reset. 
i cannot find any other post or solutions for this on the forums/bugtracker
