### ISSUE TITLE
Hunter: can't tame the pet fro Pet Zone

### ISSUE THREAD

**Issue by giopie** [RetroWoW/RetroWoW#320]
PET ZONE: IT'S IMPOSSIBLE TO TAME THE PET

My Hunter can't tame the pet from the Pet Zone (and in world too)

Everytime I try to tame a pet the target is signed as "invalid target"

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Danhali** [comment]
remove everything from WDB folder in your wow folder :)
