### ISSUE TITLE
Night Elves Wisp Spirit broken in battlegrounds

### ISSUE THREAD

**Issue by Yawnmon** [RetroWoW/RetroWoW#321]
**Description**:
Night Elf racial Wisp Spirit works as intended on Alliance side of Battlegrounds, but is broken when placed on the Horde side
**Current behavior**:
When placed on the Horde side dead Night Elves loose all effects of Wisp Spirit including both the movement speed increase and the Wisp appearance. Instead the Night Elves appear in a normal ghost form like other races
**Expected behavior**:
Wisp Spirit should work regardless of which side of the Battleground they are on
**Steps to reproduce the problem**:

1. Play a Night Elf
2. Join a Battleground on the Horde side
3. Die and become a Night Elf ghost (not a wisp)

**Source:**
Yawnmon

**Include Screenshots from the issue if necessary**:
![pics](https://user-images.githubusercontent.com/51276920/58755894-04b43c80-84a2-11e9-8cdf-7313b418f036.png)

**Comment by MrKelzo** [comment]
Related to xfac BGs
