### ISSUE TITLE
Missing Naxxramas items at Vendor

### ISSUE THREAD

**Issue by Yharnstrom** [RetroWoW/RetroWoW#334]
**Description:** There are missing items from Naxxramas Vendor that should be available.

Mark of the Champion - caster and melee trinkets.
https://classicdb.ch/?item=23206
https://classicdb.ch/?item=23207

**Current behavior:** Items not available at vendors.

**Expected behavior:** Items should be available for purchase for gold.

**Steps to reproduce the problem:**

Visit Naxxramas vendors in Hyjal to see these items are not there.

**Comment by VovremyaRetroWoW** [comment]
It's quest reward from The Phylactery of Kel'Thuzad which has 100% drop chance. It is not hard to kill KT nowadays. If it costed 15k like other naxx gear, it would be a true waste of gold.
