### ISSUE TITLE
Broken Tooth pet bugged. 

### ISSUE THREAD

**Issue by Aurheim** [RetroWoW/RetroWoW#337]
**Description**: The tamebale rare "Broken Tooth" is completely bugged. 

**Current behavior**: He does 1 attack damage, and is NOT categorized as a beast so you can't tame him. 

**Expected behavior**: He should deal normal level 37 mob damage and be categorized as a beast. 

**Steps to reproduce the problem**: 

1. Go and find him at his location. He's always there every 4 hours or so. 
2. Aggro him.
3. Profit. 

![brknth](https://user-images.githubusercontent.com/36826096/36831228-da29bf3c-1cf4-11e8-8ee5-9877cd892b2b.png)

**Comment by MrKelzo** [comment]
Close your client and remove your WDB folder
