### ISSUE TITLE
Hunter ans beast bug

### ISSUE THREAD

**Issue by GuillaumeThevenet** [RetroWoW/RetroWoW#339]
**Description**: It seems like lot of beast cant be tamed

**Current behavior**: lot of npc which has to be beasts can't be tamed or tracked. It's like their type isn't beast. It's the case for all the pet zone

**Expected behavior**: Those beast should be tamed 

**Steps to reproduce the problem**:

1. Bring back their type

**Source:**

**Comment by Nemathegreatone** [comment]
Open your World of Warcraft game folder, and search for a folder called WDB. After you have found the mentioned folder, you have to remove it. Then open a game and test it out.
