### ISSUE TITLE
Warrior rage values lower than usual

### ISSUE THREAD

**Issue by sweene17** [RetroWoW/RetroWoW#34]
On new core warriors are generating far less threat. Even on fights like Patchwerk, the tank was not generating enough rage from hits taken. (Anecdotally, a full BiS experienced tank on Patchwerk due to lack of rage was losing aggro to a Salv'ed warlock (with tier-6 aggro reduction) doing 600-650dps [and had to slow dmg] despite the increased fight damage on Patchwerk).

Please review the rage  generation formulas and test whether this is currently accurate.

**Comment by kamil87** [comment]
Can confirm, rage generation when taking DMG is bugged out. I just get destroyed for my whole health bar on my warrrior and I'm still siting at 30 rage

**Comment by mentos987** [comment]
Can confirm. I was rage starved during Patch fight.

**Comment by Bam27** [comment]
Please provide source and a method to reproduce this behavior.

**Comment by sweene17** [comment]
I don't play warrior, so I can't replicate personally. Though I've seen it an issue in every single raid run since new core.

One thing (don't know if on this server but found on other blizzlike servers: "Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked.")

How to reproduce:
GM take a warrior, spawn a raid boss or TP and test on invulnerable mode. Check rage generation to see if an issue. Then compare rage generation to combat log/output to see if data matches or if there's an area somewhere that wars are not generating threat or under-generating threat.

**Comment by MrKelzo** [comment]
No our formula is correct. 
Todo: "Warriors are supposed to get a small rage boost every time they block, dodge, or parry"
