### ISSUE TITLE
PvP Tokens BUG

### ISSUE THREAD

**Issue by DenislavLichev** [RetroWoW/RetroWoW#343]
**Description**: PvP Tokens bug

**Current behavior**: I dont receive pvp token after kill in arena. In rbgs its okey, but in open world i dont get any pvp tokens.

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:** ACC : Faultless Char : Rogueakali
 Ty for help.

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
You can only get them by killing the opposite faction (in World)
