### ISSUE TITLE
Fix the Dragons of Nightmare (Lethon, Emeriss, Ysondre, Taerar). Currently undoable encounter with 40 man raid.

### ISSUE THREAD

**Issue by Yharnstrom** [RetroWoW/RetroWoW#347]
**Description:**  Dragons of Nightmare currently oneshot bis buffed prot wars in full 40 ppl raid. We managed to get 40 ppl raid and tried them. There are no chances to kill them now. 

**Current behavior:** Worldbosses Dragons of Nightmare (Lethon, Emeriss, Ysondre, Taerar) are currently unkillable with 40-ppl group. They just 1 shot BIS buffed T3 tanks.

**Expected behavior:**  It's weird that KT is killed in 5 ppl group and those dragons are undoable even in full 40-man raids. Scale them to 5man or make them like Azuregos, which is doable, please.

**Steps to reproduce the problem:**

Just go and try one of them.

**Comment by MrKelzo** [comment]
The Dragons are blizzlike with no changes
