### ISSUE TITLE
Rank not getting updated for 2 weeks

### ISSUE THREAD

**Issue by Nasmina** [RetroWoW/RetroWoW#347]
**Description**: PVP RANK

**Current behavior**: Tell us what happens
Not getting updated
**Expected behavior**: Tell us what should happen instead
Getting updated every week since im around 20th standing. HELP
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Nemathegreatone** [comment]
You should enter the game and open a ticket. We can update your rank through the game.
