### ISSUE TITLE
Eye of cthun bugged

### ISSUE THREAD

**Issue by Haargie** [RetroWoW/RetroWoW#348]
**Description**: Got the eye of cthun, from cthun... Went to deliver to anachronos. I am exalted with brood of nozdormu btw, but still I couldnt. I had been told earlier to drop quest in AQ40 for set pieces and try again, that worked... So I ofc thought to drop the eye of cthun quest and pick again from the item.... but nope the eye and quest both disappared.

**Current behavior**: Tell us what happens - Eye of cthun AND the quest disappeared when I tried to repick in order to deliver the quest. 

**Expected behavior**: Tell us what should happen instead - I should be able to deliver the quest to anachronos and then I would pick the cloak.

**Steps to reproduce the problem**: I got eye of cthun a little back in time, when I didnt have so much reputation, since I did a few other AQ40 runs and now I am exalted so I thought I could deliver. My guess is that if you pick up the eye of cthun and take the quest when you do not have reputation, maybe you wont be able to do the quest?

1.  Pick eye up from cthun when a character does not have rep
2. try to deliver?
3. you cant, and if u abandon quest to take it, both quest and item for quest disappears.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Haargie** [comment]
My ingame character that this happened on = Jeebaz (rogue)

**Comment by Haargie** [comment]
Please give me the eye of cthun back :D <3

**Comment by Vorkasigan** [comment]
Make a ticket in game and GM will help you.

**Comment by Haargie** [comment]
How do I make a ticket ingame?
