### ISSUE TITLE
PTR - Onyxia might not have Deep breath

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#35]
**Description**:
We were doing Onyxia 2-men, we had relatively long phase 2 and 0 "Deep breathes" occurred.
**Current behavior**: Tell us what happens
Onyxia doesn't use "Deep breath" ability during phase 2.
**Expected behavior**: Tell us what should happen instead
Onyxia should use the ability "Deep breath" on page 2.
**Steps to reproduce the problem**:

I understand that this ability is random and maybe we were lucky, but the fight was long, so it's kinda suspicious.

1. Put Ony into the phase 2.
2. Make the fight really long to make sure there should be at least one deep breath.

Or maybe it would be faster to check the code.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/209936605-67559979-9244-4ec9-b039-aca6ff270115.png)
![image](https://user-images.githubusercontent.com/25086832/209936626-ef384e21-8c53-4345-bd16-a1ca4ee9cb32.png)

Tested with bots and it works fine
