### ISSUE TITLE
I dont know why banned my account

### ISSUE THREAD

**Issue by burakbrk33** [RetroWoW/RetroWoW#354]
Dear GM. My account banned why :( Please help me my account id : burakbrk33 character name : Tsleachen(rogue-undead) please i dont know why i banned ( mboxingpvpfaming ) what is this mboxingpvpfaming ? and I have 2 computer one home one office I entered 2 pc. I'm waiting for return my message. I love this game so much please help me. I want my account back.

**Comment by Vorkasigan** [comment]
Post a thread in this sections, please.
https://retro-wow.com/forum/forumdisplay.php?fid=35

**Comment by burakbrk33** [comment]
Hello i posted please help me. I need my account back i don't know what is that '' mboxingpvpfaming '' please help me.

________________________________
Gönderen: Vorkasigan <notifications@github.com>
Gönderildi: 13 Haziran 2019 Perşembe 20:54
Kime: RetroWoW/RetroWoW
Bilgi: burakbrk33; Author
Konu: Re: [RetroWoW/RetroWoW] I dont know why banned my account (#354)


Post a thread in this sections, please.
https://retro-wow.com/forum/forumdisplay.php?fid=35
