### ISSUE TITLE
Deletet Charakter 

### ISSUE THREAD

**Issue by Xyleys** [RetroWoW/RetroWoW#355]
Dear GM

I had alvl 1 Charakter on my Account while my little brother was Playing, the Sad Point is the Charakter Had 10k Gold in his Inventory and my little Brother doesnt like that Charakter so he delete it without my Permission my question now is ... Can u maybe or PLEASE give me that 10k back on this Charakter the name was :Nalathana Druid Nightelf... im so sad and acutally f##t up i hope u can Help me !!! =) 

i got no Screenshot but my Friend Traded me and he Can Prove the Buy of the Gold for Real money! 
 Hope for help !

**Comment by Vorkasigan** [comment]
Make a ticket in game or create thread here: https://retro-wow.com/forum/forumdisplay.php?fid=52
