### ISSUE TITLE
2/9 Paladin Tier 3

### ISSUE THREAD

**Issue by hederob** [RetroWoW/RetroWoW#36]
**Description**:
T3 Redemption not improving Seal of Light or Judgement of Light
**Current behaviour**: Tell us what happens
When using at least 2 pieces of T3, Seal of Light and Judgement of Light only heals 94 and 61 respectively. 
**Expected behaviour**: Tell us what should happen instead
The 2/9 is supposed to increase it by 20. It should be increased by a flat value of 20; so they should be 114 and 81 respectively.
**Steps to reproduce the problem**:

1. Attempted with 2/9
2. Attempted with 1/9
3. Deleted WDB folder and  attempted with 2/9 again

**Source:**
Bugsbuddy retroWow

**Comment by hederob** [comment]
Still not working as intended, 2/9 tier 3 for paladins has no effect on Seal of Light and Judgement of Light

**Comment by robinsch** [comment]
Can someone link items and auras.

**Comment by hederob** [comment]
ty
