### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by Ciridash** [RetroWoW/RetroWoW#362]
**Description:** Died in blackrock spire and also dead (Viwil)

**Current behavior:** Falling in the air

**Expected behavior**:  

**Steps to reproduce the problem**: 

1.  try to tame a wolf in blackrock spire
2.  mobs hitting hard
3.  dead
4.  fall down

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Yharnstrom** [comment]
Make a ticket in game, please.
