### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by Av2231** [RetroWoW/RetroWoW#365]
hello .On one of my characters my chat is bugged. Nothing is displayed , I can t see what is written in chat, nor apply for groups. I tried reseting everything  in setting , but it did not help me. Can you help me?

**Comment by Nemathegreatone** [comment]
Hello.

Open your World of Warcraft game folder, and search for a folder called "WTF" and for a folder called "WDB/CACHE", close your game, and remove both folders. Then open your game and check if the chat is working.

NOTE: By removing WTF, you will also remove your user interface configurations. And, if you bump on a problem in the future, simply open a ticket, and one of our gamemasters will answer your ticket.
