### ISSUE TITLE
Character fell through world, still falling

### ISSUE THREAD

**Issue by sethik** [RetroWoW/RetroWoW#369]
I was in Black Rock Spire, and I fell through the map. I was trying to tame a wolf. I will not do this again, LOL I didn't know that area was incomplete. LOL

Sethuk Night Elf Hunter

thank you

PS having a lot of fun :)

**Comment by Gruffers** [comment]
DId you find a way to resolve this?

I think I did the same thing and my character is constantly moving with health going from 22 to 11 to 6 to 3 and then back to 22 again and again.  The .st command does work it just gets interrupted.
