### ISSUE TITLE
[Wolfshead Helm] ID:8345

### ISSUE THREAD

**Issue by Popsis** [RetroWoW/RetroWoW#38]
**Description**: Hello , this is my first report , I just created account to help Retro-wow. This is my first report.

**Current behaviour**: Helm doesnt work , no energy when i shapeshift to cat , no rage when i shapeshift to bear.

**Expected behaviour**: It should give +20 enegy in when shapeshifting in cat , and +5rage in bear .
Together with talents 40+20=60 in cat on shapeshift act and 10+5=15 in bear form.

**Steps to reproduce the problem**:

1. Create druid .
2. Equip Helm
3. Shift to cat.
4. Shift to bear.

**Source: http://db.vanillagaming.org/?item=8345#wh-comments Actually i dont even see reason , to look for more source as everyone knows that item. Posted this source for old Wowhead comments.

**Comment by Rushor** [comment]
fixed here https://github.com/r4z0r84/TBCPvP/commit/c2f39cf1f744727660174e7fcb9613a040b8a7e6

**Comment by robinsch** [comment]
@Rushor No on vanilla it has a internal CD that's why it's not working :P

**Comment by Rushor** [comment]
kay :(
