### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by privateworm** [RetroWoW/RetroWoW#383]
**Description**: I got banned for buying gold off a different website. " Had no idea the million people whispering me weren't gms or bots of the server. For gold buying." 

**Current behavior**: Depressed

**Expected behavior**: Take Gold Take some gear from my character. Take anything but my guild and my warlock.
  
 Hi, Ive donated quite a lot on my account and have a active and Relying guild for a guild master. 
I went on to what I thought to be one of your sister websites and purchased gold. I understand now that I shouldn't have done that. Because I am unaware of really why. Ive had atleast 3 people in the past 2 weeks join your server and donate more than 50$ U.S to your website. All I wish is for my account back please </3 Sincerely asking.

**Comment by homosapienzzz** [comment]
I got banned for no reason, tried loging in my account missed the password 5 times and trying to type it again and it says "Could not log in to World of Warcraft at this time"
