### ISSUE TITLE
Difference in the item between shop and game

### ISSUE THREAD

**Issue by Michouzos** [RetroWoW/RetroWoW#387]
**Description**:

I bought the priest enchant with 3 DP.
The enchant is presented as 10 stamina 13 Spell power and 4 MP5.
When I received the item in game the stats are 10 stamine 24 heal and 4 MP5

I am shadow, I dont need heal. If the shop would have been correctly indicated, i would not have bought it.

**Current behavior**: cf above

**Expected behavior**: reimbursement of 3 DP i suppose. Or find the item i intended to buy !

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

shop : 

![image](https://user-images.githubusercontent.com/52569320/60719610-8aeff280-9f28-11e9-847a-504c341536e3.png)

game : 

![image](https://user-images.githubusercontent.com/52569320/60719620-93482d80-9f28-11e9-88f7-32659068fc92.png)

**Comment by tara81** [comment]
Old post but I'll respond. The reason it is incorrect is because when burning crusade came out , + healing was changed to +spellpower (converted), so the old items had their stats changed. I think they need to get new links to the old items.
