### ISSUE TITLE
Banned Account - Issue: Change_Password??

### ISSUE THREAD

**Issue by Squiffy000** [RetroWoW/RetroWoW#390]
**Description**: Apparently my account is banned and all it says next to status is: Change_password?

**Current behavior**: Can't login to server

**Expected behavior**: Can login to server with un banned account

Account: SquiffyRetro

**Comment by classicslawa** [comment]
hello I have the same problem with me is banned and GS help

**Comment by Squiffy000** [comment]
GS?

**Comment by oropos1987** [comment]
Same and with me ,what joke is this!!!
