### ISSUE TITLE
hello I have the same problem with me is banned and GS help I only paid 100 € yesterday in the shop

### ISSUE THREAD

**Issue by classicslawa** [RetroWoW/RetroWoW#392]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. hello I have the same problem with me is banned and GS help
2. I just bought 100 € yesterday in the shop weapon :(
3. Please turn me on again.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
Open a ban appeal here -> https://retro-wow.com/forum/forumdisplay.php?fid=35
