### ISSUE TITLE
Combo Points 

### ISSUE THREAD

**Issue by stushx** [RetroWoW/RetroWoW#397]
My Combo Points as rogue are dropping off at random as I am spamming backstabs or sinister strikes on one target. They should only fall off when you switch target. I am not able to reproduce this in duels only battlegrounds, where it is happening to me every other fight.

Here is a video demonstrating https://streamable.com/wgq9z

I have lots of footage of combo points disappearing at random.

**Comment by Bam27** [comment]
Cannot reproduce. Check your addons.
