### ISSUE TITLE
Illiyana Moonblaze <Silverwing Supply Officer> in mall sells nothing

### ISSUE THREAD

**Issue by Feltyham** [RetroWoW/RetroWoW#4]
Hello,

As per the subject: Illiyana Moonblaze <Silverwing Supply Officer> in the mall sells nothing

This NPC found in the Hyjal Mall used to sell various items including the "Major Healing Draught" which is a potion that stacks to 10 and can only be used in BGs.

https://classicdb.ch/?item=17348

**Comment by Feltyham** [comment]
For ease of seeing what the NPC used to sell, I've added the following link:
https://classicdb.ch/?npc=14753#sells:50+1

**Comment by MrKelzo** [comment]
You will be able to see all items once you have enough reputation.
