### ISSUE TITLE
PTR - Class trainers do not work

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#4]
**Description**:
All the class trainers have the same model, and players can't interact with them.
**Current behavior**: Tell us what happens
All the class trainers have the same model, and players can't interact with them.
**Expected behavior**: Tell us what should happen instead
The player should have the ability to learn spells and reset talents. Each class trainer should have a unique model as on the live version.
**Steps to reproduce the problem**:

1. Check class trainers in the Hyjal mall.
2. 
3. 

**Source:**
<img width="731" alt="image" src="https://user-images.githubusercontent.com/76588473/209807573-023e1458-4a5e-4365-9928-fe7a36c2692b.png">

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
You can only interact with your own class trainer

**Comment by MrKelzo** [comment]
Models will be updated later
