### ISSUE TITLE
Vengeance ID:20059 [Paladin talents]

### ISSUE THREAD

**Issue by Popsis** [RetroWoW/RetroWoW#40]
**Description**: This talents in retribution tree isnt working as it should http://db.vanillagaming.org/?spell=20059

**Current behaviour**: When seal of command yellow hit crits , it doesnt proc this talents , same with fiery weapon crit. 
White hit crits and judgement crits does proc it currently.

**Expected behaviour**: Any crit made by paladin should proc it Spell , enchant , trinket , weapon.

**Steps to reproduce the problem**:

1.  Get those talents in retribution tree.
2. Get enchant of fiery weapon.
3. Hit target until you will get seal of command proc crit , or fiery weapon

**Source: Video 1min20s - https://www.youtube.com/watch?v=f6SPpRZmuBU&feature=youtu.be&t=1m20s
The page i got info from , also alot of detailed information in here https://elysium-project.org/bugtracker/issue/13
https://vanilla-twinhead.twinstar.cz/?issue=1757

**Comment by Nemathegreatone** [comment]
@robinsch test this one out again
