### ISSUE TITLE
Twilight Corrupter, too many spawns

### ISSUE THREAD

**Issue by zagara1** [RetroWoW/RetroWoW#400]
**Description**:
Should only spawn one Twilight Corrupter
**Current behavior**: Tell us what happens
20 spawns of him
**Expected behavior**: Tell us what should happen instead
1 spawn of him
**Steps to reproduce the problem**:
??
1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
Invalid report. Cannot reproduce. Please give more information.
