### ISSUE TITLE
Hunter Pet Broken tooth

### ISSUE THREAD

**Issue by Bodazzle** [RetroWoW/RetroWoW#401]
**Description**: I have tamed this elusive beast TWICE in the last day with no problems, however shortly after (10-20 minutes) he just vanishes!

**Current behavior**: Tell us what happens 
First attempt. tame him. celebrate and port back to orgrimmar, log in and out then to the profession zone (still with me) and before i can google where a meat vendor is hes gone! 
Second attempt. Me bad orc. me no good to friend. me bring all the meat. fast forward 8 hours and read "how to hunter pet for dummies" oh! there he is! tame him with this cool macro i made in my spare time :) port back to orgrimmar (train some abilities, feed him again, give him a name!!!!! and start running to the barrens feeding him when i stop to collect nodes. just into the north part of the barrens and were killing some mobs, hes looking happy, hes level 60. nibblin on his meat... look down to check my quiver. look up for the next target and notice hes gone.. !!@#!@$!@

So maybe its me? i tame a raptor.. feed him two or three times.. kill twenty mobs(same as before) log in and out doing the same steps as before.. still here.. stop feeding him.. let the locals beat his head in.. still here.. dismiss him! put him on stay and leave his ass behind!! still shows up.. tell him theres food over yonder as i mount up and run away till he dies of exhaustion... Surely now.. he must be gone.. still shows up to the usual call. I cant get rid off this guy... dismissed him soo many times i felt bad and started trying to find him a new home... 

I did not try putting him in the stable.
we were figjhting lvl 12 mobs so theres no way he died.. he had plenty of food in his belly and im familiar with the kitty diet.couldnt find anything on him related to the server, found one similar result but that was fixed clearing the cache, which i did. 

**Expected behavior**: Tell us what should happen instead
He should be a good boy and stay with his new master! 

**Steps to reproduce the problem**:

1. tame broken tooth. give him food. water and a place to call home.
2. wait for him to leave...
3. Get salty.............

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
Cannot reproduce. The pet works fine for me and doesn't run away if properly cared for.
