### ISSUE TITLE
Heigan the Unclean - Dance

### ISSUE THREAD

**Issue by Memon1** [RetroWoW/RetroWoW#402]
**Description**: During the "dance" part of the fight

**Current behavior**: During the "dance" part of the fight the aoe that comes up from the ground in the middle of the room bugs out and kills you even if you are standing at a safe place. 

**Expected behavior**: Should not kill you when you are in the safe-zones

**Steps to reproduce the problem**:

1. Get to the dance part of the fight
2. Try out the different zones that are supposed to be safe

**Comment by VovremyaRetroWoW** [comment]
Man, you just dunno how to dance. Practice, more practice! I did not get any damage from it last 10 runs while tanking.
