### ISSUE TITLE
Atiesh Staff

### ISSUE THREAD

**Issue by Aenour** [RetroWoW/RetroWoW#403]
**Description**:
Atiesh, Greatstaff of the Guardian

**Current behavior**: Tell us what happens
I have Atiesh, Greatstaff of the Guardian with 2% crit chance with spells, it doesnt work at all for me, I have the buff but it doesnt count at all, I've even tryied with a priest who had Atiesh, Greatstaff of the Guardian with spell damage and when we grouped together and stood next to each other my staff buff dissapeard, we left group and I've had to unequip and equip it back again to get the buff, but that buff doesnt give anything at all and everytime I die buff dissapaers. I've purchased this staff from you guys. 

**Expected behavior**: Tell us what should happen instead
It should work properly and give 2% crit chance, showing to me now with the staff equiped 11% crit chance in total, I unequip staff and showing still the same. 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:
https://imgshare.io/image/ax6xe
https://imgshare.io/image/amz7w

**Comment by Aybarrin** [comment]
Same here for a mage.
The bonus of 2% crit isn't working.
Do something or refund us in DP... 
thanks

**Comment by Aenour** [comment]
9 days ago and still no answer, not even a message that you are working on it. My opinion, either fix it or return DP please. If you are willing to sell it, then be willing to make sure that it works

**Comment by Aybarrin** [comment]
cela est dommage de ne pas répondre à ses clients

**Comment by VovremyaRetroWoW** [comment]
CasterStats addon does not count buffs effects, only from gear. Vanilla client does not contain visible spell stats values, only melee. It's addon problem. Atiesh buffs really give their effects, so you can test it by experiment using DPSMate.

Atiesh buffs does not stack as it should be. So how to choose which buff will work? I have noticed that atiesh buff from member who was reloged last time has a priority. Tell your priest remove his buff while you are reloging. After that re-equip your atiesh.
