### ISSUE TITLE
AV character stuck

### ISSUE THREAD

**Issue by tim3434** [RetroWoW/RetroWoW#408]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. In AV my char got stuck when the battleground ended and couldn't leave and couldn't hearth either. I ended up restarting my game which put me in booty bay with the guards attacking me and the av tokens from the win missing.
2. To be able to leave the BG without my character bugging out.
3.  see Q1.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by mah0nka2** [comment]
1. мой персонаж умер, его дух упал под текстуры. я не могу подойти к ангелу чтобы воскреситься. я не могу указывать команды потому что я мертв (unstuck and....)
2. возродите моего персонажа в любом месте. ник Motarika . паладин человек
3.  q1

**Comment by Bam27** [comment]
Open a ticket in game.
