### ISSUE TITLE
Talent Martyrdrom not working (Priest discipline tree)

### ISSUE THREAD

**Issue by Sunqtt** [RetroWoW/RetroWoW#41]
Talent Martyrdrom not wroking (Priest discipline tree) : http://db.vanillagaming.org/?spell=14774

Here is what should proc when taking any kind of crit  (melee strike hit / spell that use melee weapon / ranged attack / spell that use ranged weapon)

-20% resist to any interupt effect 'kick, pummel, cs ...)  
-100% No pushback

**Comment by robinsch** [comment]
Melee based attacks could never be resisted due to these effects.

**Comment by robinsch** [comment]
Invalid report, working fine.
