### ISSUE TITLE
PTR- Enrage, Redoubt, Blood Craze and Reckoning sit+crit 

### ISSUE THREAD

**Issue by kurtosmurtos** [RetroWoW/RetroWoW#41]
**Description**: Warriors cannot force Enrage, https://classicdb.ch/?spell=13048, and Blood craze, https://classicdb.ch/?spell=16492. 
 procs by sitting and being critically hit. It seems the situation is the same with the Paladin talents Redoubt(https://classicdb.ch/?spell=20135) and Reckoning(https://classicdb.ch/?spell=20182).

**Current behavior**: On the PTR Warriors cannot force Enrage (https://classicdb.ch/?spell=13048) and Blood craze (https://classicdb.ch/?spell=16492)procs by sitting and being critically hit. It seems the situation is the same with the Paladin talents Redoubt (https://classicdb.ch/?spell=20135) and Reckoning (https://classicdb.ch/?spell=20182). Sitting still does means that the player will be critically hit but effects such as these cannot seem to be forced like they can be on live by spamming /sit. On the PTR they do work when enemies crit the player on their own.

**Expected behavior**: I am not sure if which version is blizzlike, but if this is to be kept as same as on the live server atm, these effects should be able to be forcably procced by the player by spamming the /sit command.

**Steps to reproduce the problem**:

1. Attack a hostile target
2. Smap /sit and get critically hit
3. Follow the combat log and notice that the effects are not triggering 
4. Try the same on the live server and compare results

**Source:** Gameplay / screenshots from the live server

**Include Screenshots from the issue if necessary**:
![Screenshot (199)](https://user-images.githubusercontent.com/112797709/210064950-49569c9b-ed7e-450a-be66-ba6a9ac06136.png) PTR, no Enrage or Blood Craze.
![Screenshot (200)](https://user-images.githubusercontent.com/112797709/210065034-42337c1e-5676-4859-a318-98e4e55881a6.png) PTR no Redoubt or reckoning.
![Screenshot (205)](https://user-images.githubusercontent.com/112797709/210065134-66cde529-f661-47a6-8a16-d5d872693808.png)  Live server, Redoubt procced
![Screenshot (206)](https://user-images.githubusercontent.com/112797709/210065199-ec2b585f-4ef6-4f36-a542-1801418ed1b8.png) live server, Redoubt procced again
![Screenshot (208)](https://user-images.githubusercontent.com/112797709/210065281-551fa69f-1bfb-439a-8b92-35d25c9c3e67.png) Live server, Enrage and Blood craze active
![Screenshot (209)](https://user-images.githubusercontent.com/112797709/210065341-3301a3b1-8cec-4140-9a08-d958dbf1a5b3.png) Live server, same case as previous

**Comment by MrKelzo** [comment]
Report 1 issue per case and not multiple in 1 report.

"Source" means like wowwiki, old video shown how it works, old comments from 2004-2006
