### ISSUE TITLE
Why im i banned? IP BAN? Could not log into wow, please try later

### ISSUE THREAD

**Issue by nonek7** [RetroWoW/RetroWoW#410]
**Description**:Whats up?

**Current behavior**: Tell us what happens banned?

**Expected behavior**: Tell us what should happen instead what?

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
If you entered incorrect information associated with the account too many times then the account will be locked for a short time. Try again later.
