### ISSUE TITLE
Onyxia Healing and Tanking with a Shadow Priest

### ISSUE THREAD

**Issue by Gruffers** [RetroWoW/RetroWoW#416]
**Description**:
Went into Onyxia, started fighting her as a group, about half way through she completely healed back to 100%.  So we wiped and tried again and the same thing happened.

Then, we decided to try it with no tank.  As a joke we used  Shadow Priest to tank it.  And mind you no one was overly geared or buffed.  And the Shadow Priest had no problem tanking Onyxia.  

The trash mobs have also immediately respawned and I am unable to get the loot.

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead
Onyxia should not be able to heal.
A Shadow Priest should not be able to tank her.

**Steps to reproduce the problem**:

1. Uncertain as raid lock out does not allow me to test it.  Raid ID is 3105
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:
I wish I had been recording it.

**Comment by Bam27** [comment]
Not enough information. Cannot reproduce.
