### ISSUE TITLE
loot disappeared, boss despawned (AQ40) ouro

### ISSUE THREAD

**Issue by highheelsninevolt** [RetroWoW/RetroWoW#417]
**Description**:
Skin of the Great Sandworm and Wormscale Blocker despawned whilst trying to loot it
on my Shaman named-"Ninevolt"
**Current behavior**: Tell us what happens
Killed boss
Boss despawned with loot after less than 5 mins
**Expected behavior**: Tell us what should happen instead
Loot and boss should stay there like literally every other instance and boss within that instance
**Steps to reproduce the problem**:

1. Kill ouro
2. wait 5 mins
3. Boss and loot are gone - be sad

**Source:**
Temple of the Qiraji

**Include Screenshots from the issue if necessary**:
No screenshots, but can you please allocate me those items? I won them fairly and they are hard to come by.

**Comment by Bam27** [comment]
Open a ticket in game.
