### ISSUE TITLE
Mainhand & Shield deleted/vanished? I did not delete it.

### ISSUE THREAD

**Issue by tiagoamaral456** [RetroWoW/RetroWoW#418]
**Description**: Main hand sword from ZG is gone, as well as the shield I got from BWL most recently. I use item rack addon and switch from sets all the time but by no means would I have deleted those items or sold them all the while I still have junk in my bag.

**Current behavior**: Item get's deleted

**Expected behavior**: Item switch but don't get deleted maybe compatibility problem with addon.

**Steps to reproduce the problem**:

1. addon itemrack
2. switch gear constantly
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
Items are not simply deleted by the server for no reason. Cannot reproduce.
