### ISSUE TITLE
Getting disconnected after about 20 sec

### ISSUE THREAD

**Issue by Gatten** [RetroWoW/RetroWoW#419]
**Description**:
Gettiing dc after 20 sec
**Current behavior**: Tell us what happens
We can logging on me and my wifes acount but getting dc after about 20 sec

**Expected behavior**: Tell us what should happen instead
We have fun playing Retrowow
**Steps to reproduce the problem**:

1. logging
2. wait 20 sec
3. dc

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
Cannot reproduce. Please check your connection to the server via a trace-route and see where the problem occurs.
