### ISSUE TITLE
Paranoia : Reduce the range of stealth detection in pvp

### ISSUE THREAD

**Issue by Sunqtt** [RetroWoW/RetroWoW#42]
Right now, the distance from wich locks can spot rogue is 15/20 yards. 

In pvp, it is way too much, and should be 3 or 4 yard maximum, otherwise paranoia is just like human perception basically, or almost. : 

https://forum.nostalrius.org/viewtopic.php?f=37&t=34704

**Comment by Popsis** [comment]
If we have 5 yards melee range , and you want 3-4 yards for warlocks to spot you?
If warlock has detection buff + paranoia , i think its ok that they can see you from far range. 
Even in that discussion on nostalrius forums you can see that 15-20 yards for warlock is ok.
https://www.youtube.com/watch?v=E3z6nyycNjk his video from 2:25 shows some nice fixing on this question. And all that was without warlock buff , just paranoia and perception.

**Comment by Sunqtt** [comment]
according to kronos video thats the correct range so issue closed
