### ISSUE TITLE
NPC Raider Bork (PVP Mounts)  missing from Orgrimmar

### ISSUE THREAD

**Issue by djstingray** [RetroWoW/RetroWoW#422]
**Description**: Horde PVP Mount NPC (Raider Bork) Missing for 2 weeks.

**Current behavior**: Cannot find him.

**Expected behavior**: Usually outside Hall of Legends on a Wolf

**Comment by djstingray** [comment]
![BORK](https://user-images.githubusercontent.com/53822181/62858501-be583680-bcb7-11e9-9a58-1d42e4770319.JPG)

**Comment by rapp5190** [comment]
Bump, Been looking to get a black pvp war mount for a bit now, i can get one on my alliance character, id love to be able to get one on horde <3

**Comment by Bam27** [comment]
Fixed.
