### ISSUE TITLE
Account unnecessarily Banned - Reason: ChangePassword_ConfirmOwnership

### ISSUE THREAD

**Issue by Bucknle** [RetroWoW/RetroWoW#426]
**Description**:
Hi Support,
My account was banned recently for reason _ChangePassword_ConfirmOwnership_

Though I have changed password recently.Also, I have created this account in December of 2015 and I no longer have access to the email that I created this account with.

**Current behavior**: Tell us what happens
Cannot login.
No end user option within UI to update email or address ban reason
**Expected behavior**: Tell us what should happen instead
Should be able to login successfully
**Steps to reproduce the problem**:

1. enter credentials for account rjthejock
2. observe banned message
3. 

**Source:**
n/a

**Include Screenshots from the issue if necessary**:
n/a

Can you guys please address this behavior and let me know how this can be prevented in the future?

**Comment by Bam27** [comment]
PM Ossirian or Kelzo via discord or the forums to recover your account. 

Please do not share account informations across other projects, or this kind of thing can happen.
