### ISSUE TITLE
Banned for reason "Verify ownership change password". I did this. Did not help. What do i do? none of the other threads with the same issue clears out any answers. 

### ISSUE THREAD

**Issue by jackant-star** [RetroWoW/RetroWoW#428]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
PM Ossirian or Kelzo via discord or the forums to recover your account.

Please do not share account informations across other projects, or this kind of thing can happen.
