### ISSUE TITLE
Item problem

### ISSUE THREAD

**Issue by Plabol** [RetroWoW/RetroWoW#429]
I bought the Atiesh, Greatstaff of the Guardian in the shop but the staff doesn't have the stats for my spec. I play balance spec and this staff gives attack power for feral combat. Pleas can you change the stats or refund the dp? Thank you.

**Comment by Plabol** [comment]
In the shop the staff stat is "Increases spell power by 160." but the one I received has +420 attack power instead. Please fix it.

**Comment by Bam27** [comment]
Open a ticket in game.
