### ISSUE TITLE
Shaman/Stormstrike

### ISSUE THREAD

**Issue by Serdevos** [RetroWoW/RetroWoW#43]
**Description**:
Stormstrike: Gives you an extra attack. In addition the next 2 sources of nature damage dealt to the target are increased by 20%. Lasts 12 seconds.

**Current behaviour**: Tell us what happens
Whats currently happening is that the strike isn't seen as an extra attack but a spell like Mortal strike (yellow damage) so it can't procc windfury like it should.

**Expected behaviour**: Tell us what should happen instead
What should happen is that the strike is seen as a normal white hit like in this video on the same patch:https://www.youtube.com/watch?v=LZrTVeWQmKo&t=28s- 

Watch at 00:42 and 1:12 where the stormstrike proccs the windfury.

Steps to reproduce the problem:

1:Find a dummy 
2:Stormstrike it
3:Yellow hits like a spell/cant produce windufry
**Source:**
Functionality
When you cast this spell, you immediately launch a melee attack against the currently targeted opponent, which has a normal chance to hit, and is subject to normal combat procs like Windfury. From wowwiki

**Comment by robinsch** [comment]
Please post a video from retail. Nostalrius is definitly not a valid source.

**Comment by Serdevos** [comment]
https://www.youtube.com/watch?v=ja1j7xWpB3w

Famous vid from retail. At 8:49 and 9:47.

**Comment by Serdevos** [comment]
Bump.

**Comment by Serdevos** [comment]
Rebumping. Added video.

**Comment by modnaros** [comment]
Serdevos is right, the video highlights it

**Comment by robinsch** [comment]
On PTR.

**Comment by Serdevos** [comment]
Thanks alot!
