### ISSUE TITLE
Missing items!!

### ISSUE THREAD

**Issue by Suzywong** [RetroWoW/RetroWoW#430]
Hello!
My skull of Impending doom off hand and my main hand just disappeared when i equipped them with my macro:
/script UseContainerItem(0,1);
/script UseContainerItem(0,2); 
Never got this kind of problem before...    please, HELP ME GET MY WEAPONS BACK :(

**Comment by Suzywong** [comment]
I had staff equipped, wanted to swap weapons to my main hand mace + skull of impending doom but they literally both disappeared from my character when i tried to equip them...

**Comment by Bam27** [comment]
Open a ticket in game.
