### ISSUE TITLE
 character stuck

### ISSUE THREAD

**Issue by mah0nka2** [RetroWoW/RetroWoW#432]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
my character died, his spirit fell under the texture. I can’t go to the angel to be resurrected. (unstick and ....)
revive my character anywhere. nickname Motarika. paladin man
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by Bam27** [comment]
Open a ticket in game.
