### ISSUE TITLE
Could not log in to world of warcraft at this time. please try again later

### ISSUE THREAD

**Issue by pursius** [RetroWoW/RetroWoW#433]
**Description**:
Could not log in to world of warcraft at this time. please try again later
**Current behavior**: Tell us what happens
Could not log in to world of warcraft at this time. please try again later
**Expected behavior**: Tell us what should happen instead
to log me in

**Comment by Bam27** [comment]
If you entered incorrect information associated with your account too many times the account will be locked for a short time before you are allowed to access again. 

Closing this report.
