### ISSUE TITLE
Ret paladin spells weak

### ISSUE THREAD

**Issue by Steffystylle** [RetroWoW/RetroWoW#434]
**Description**:

**Current behavior**:The Paladin's Seal of Command is not proccing properly and the Vengeance talent is the same, 

**Expected behavior**: please reinforce/fix these spell/talent because it's unuseable for PVP and PVE too.

**Steps to reproduce the problem**:

1. Low DPs Low damage paladin 
2. slow auto attack 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:
![68697132_524306104988996_7486705253417484288_n](https://user-images.githubusercontent.com/54271523/63267315-0c5dd300-c292-11e9-95d9-4c6f174e2064.png)

**Comment by Bam27** [comment]
Invalid report. Include proper sources and more information.
