### ISSUE TITLE
[Bug] WSG/AB queue doesn't depop if you're in Alterac Valley

### ISSUE THREAD

**Issue by Capracou** [RetroWoW/RetroWoW#44]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
All in the title, the queue for wsg never depops if you're in Alterac Valley, screwing wsgs big time because the player slot remains unused, resulting in recurrent 6v10 wsgs
**Expected behaviour**: Tell us what should happen instead
You already know

**Include proofs for this behaviour**
(you can see the time at the bottom of the screenshots)
Screenshot 1 : wsg popped and should depop in 1min01sec in the screenshot
Screenshot 2 : 2m30sec later wsg queue shouldn't appear anymore
Screenshot 3 : me joining the wsg 3 minutes later

**Include Screenshots from the issue if necessary**
![wowscrnshot_061118_110831](https://user-images.githubusercontent.com/25414875/41223376-dfef10a0-6d69-11e8-9d07-c41bd7da7409.jpg)
![wowscrnshot_061118_111112](https://user-images.githubusercontent.com/25414875/41223715-def0c7b0-6d6a-11e8-95aa-e260ad11260f.jpg)
![wowscrnshot_061118_111123](https://user-images.githubusercontent.com/25414875/41223667-ba8b85ea-6d6a-11e8-941c-eaf20291954a.jpg)

**Comment by MrKelzo** [comment]
Will be applied after the next restart. Thanks for reporting.
