### ISSUE TITLE
Stealth and pet's

### ISSUE THREAD

**Issue by Sunqtt** [RetroWoW/RetroWoW#44]
When you stealth, the pet that is following you should stop following you, in retrowow the pet keeps following you and hits you when he gets to you, so lock and hunters just have to send their pet to you whenever they see you : 
 
Look at 7:20 and 7:30

https://www.youtube.com/watch?v=yPXCZGacoH4&t=249s

**Comment by Sunqtt** [comment]
closed
http://blue.mmo-champion.com/topic/125724-commonly-reported-issues-that-are-not-qa-bugs/

https://www.youtube.com/watch?v=Q0O4RKeD4g4

**Comment by xiaoxoxo** [comment]
Pets chasing is blizzlike, like seen on https://www.youtube.com/watch?v=Q0O4RKeD4g4.
Also trying to link sources from Peenix is not a good source. (Pets chased till vanish there too, dunno what that hunter was doing).

**Comment by Sunqtt** [comment]
yea i know that's why i closed the post, i'm the one that linked the video dude
