### ISSUE TITLE
Gold disapear

### ISSUE THREAD

**Issue by coyote421** [RetroWoW/RetroWoW#441]
**Description**:
I made an echange of 186k gold with my bank character that already had 186k. My bank caracter was supposed to have 372k, but it capped at 214.... So i just lost 158k gold

**Current behavior**: Tell us what happens
Gold capped at 214. So i lost money

**Expected behavior**: Tell us what should happen instead
I should not have lost money during transactions

**Steps to reproduce the problem**:
1. 
2. 
3. 
**Source:**
**Include Screenshots from the issue if necessary**:
1)First one we can see my two character having respectivly 186 and 186k. This was the first transaction of 100k 
2)Second we can see a second transaction of 86k (it's capped at 214 but i didn't notice)
3)Third, we can see that it's always at 214 even after the second transaction, and that all the money disapeard

Thanks for help and sorry for my english !

![Before_Echange](https://user-images.githubusercontent.com/55353921/64923142-7311d600-d7d7-11e9-870c-144211cdbbbe.png)
![SecondTransaction](https://user-images.githubusercontent.com/55353921/64923151-8fae0e00-d7d7-11e9-8c27-34e98c99c1de.png)
![WTF](https://user-images.githubusercontent.com/55353921/64923154-92a8fe80-d7d7-11e9-8474-c7a8fac9647d.png)

**Comment by kamazuzu** [comment]
Same here, please Check Priezz 's transactions too lost about 90500 gold.
