### ISSUE TITLE
My account was banned while i was farming.

### ISSUE THREAD

**Issue by 1x444** [RetroWoW/RetroWoW#455]
**Description**: im pretty fucking pissed i spend day and nights tryna make gold and get good ass gear , and i was farming like usual and i jumped 3 times like it was a glitch and i continued thinking it was no big deal , but then BAM! i was banned. i would like to be unbanned for this nonsense bc i took time into doing dungeons and getting the swords i got and gear i got. 

**Current behavior**: Tell us what happens

**Expected behavior**: nothing bc i did nothing wrong

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by tara81** [comment]
I am not a part of the staff, but I suggest you post in the server forums about this issue under ban appeals. Sometimes this happens sadly.

**Comment by 1x444** [comment]
Thank you very much will do
