### ISSUE TITLE
How to avoid ban? 

### ISSUE THREAD

**Issue by sysqo** [RetroWoW/RetroWoW#457]
**Description**:
Gold from friend
**Current behavior**: Tell us what happens
Hi there, I'm writing you because I've seen you are doing daily transaction scans and I'm afraid of getting a ban after my friend give me some gold.

**Expected behavior**: Tell us what should happen instead
I just want to make sure not to ban us because of giving gold.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

Thank you very much!

David aka Sysqo

Best regards. 

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
We check the history of accounts aswell, so don't worry.
