### ISSUE TITLE
Pet movement speed

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#46]
**Description**: Currently any pet abillities/talents that should improve speed don't work.

**Current behaviour**: Spells like Dash, Dive and Bestial Swiftness don't give any effect at all.

**Expected behaviour**: With these spells active pet should gain movement speed.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:** read mouseover tooltip on spells/talent

**Comment by Phocus26** [comment]
+1, pet movement speed is also effected when the player gets CC'd

**Comment by Soviethammer** [comment]
When will it work on live?

**Comment by xiaoxoxo** [comment]
Dash still doesnt give +speed

**Comment by Soviethammer** [comment]
Xiao they havent had the restart yet

**Comment by xiaoxoxo** [comment]
Hunter talent beastail swiftness still doesn't work, dash is fixed however.

**Comment by Soviethammer** [comment]
Ah im glad to hear that. Do you know if hunter pets should have more hp than they have currently? I know its been bugged on other servers that ive played on (tbc patch for pets) currently my pets dies in 2 hits and have 3k hp

**Comment by xiaoxoxo** [comment]
looks like its blizzlike unfortunately

**Comment by Soviethammer** [comment]
dash is not fixed?

**Comment by Soviethammer** [comment]
nvm had to resummon pet

**Comment by Soviethammer** [comment]
or actually sometimes it doesnt work
