### ISSUE TITLE
Cannot /who more than once

### ISSUE THREAD

**Issue by Sunqtt** [RetroWoW/RetroWoW#46]
The command /who that allows any player to see how many/which players are located in a specific area only works once.

For instance, I can type /who naxx one time, but then i won't be able to /who anymore.
Same thing happens when you shift-click a name in the world or of someone that wrote something, since when you shift click, you basically do a /who on the name you just clicked, and you'll see his position, race, lvl and class.

Shift-click and /who are two important features in order to recruit the right class into a raid, or being aware of what's happening on the server overall.

Thank you,

**Comment by MrKelzo** [comment]
There is some delay added for goldsellers
