### ISSUE TITLE
Cannot recover my body. Please resurrect!

### ISSUE THREAD

**Issue by stronglift-sudo** [RetroWoW/RetroWoW#461]
**Description**: I was running from the mobs in Cursed Island. Then on last hit before I died I managed to press: teleport to next place under CI. At the same time I died and my body fell under the mountain. My spirit arrived in Onyxia. And I can't recover. I can't also go out of this place and get resurected for exiting the Raid. 

Quick story. I died in cursed island but my body fell underground and I arrived in MC. Please help me resurrect. 

**Current behavior**: Tell us what happens. I am unable to play my character Mage. <name: Stronglift> 

**Expected behavior**: Tell us what should happen instead I would appreciate not coming back to normal and be able to resurrect somehow. 

**Steps to reproduce the problem**: to reproduce the problem someone should receive last hit before death in CI at the same time they teleport to another location and their body will fall in abbyss. 

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by tara81** [comment]
Here are some temporary solutions until this is resolved:

1. Join chat /world and ask a player to group queue wsg or ab with you. Once the queue pops up, you can join even while dead.
2. Create an ingame ticket.
3. Try the .unstuck command

**Comment by stronglift-sudo** [comment]
Fixed. Thank you! 


Sent from Yahoo Mail for iPhone


On Monday, March 2, 2020, 08:08, tara81 <notifications@github.com> wrote:


Here are some temporary solutions until this is resolved:
   
   - Join chat /world and ask a player to group queue wsg or ab with you. Once the queue pops up, you can join even while dead.
   - Create an ingame ticket.
   - Try the .unstuck command
