### ISSUE TITLE
Love Is In The Air Event : Innkeeper missing items to followup a questline

### ISSUE THREAD

**Issue by Funnie1** [RetroWoW/RetroWoW#463]
**Description**:
ALL Innkeepers during the Love is In The Air Event have missing items to complete a quest chain. Helpful for PVE players to obtain the food items that provide great stacking buffs while the event lasts.
**Current behavior**: Tell us what happens
Innkeepers are missing items needed to continue on an event questline.
**Expected behavior**: Tell us what should happen instead
The items should be sold by the following Innkeepers listed in qyazo link put down below.
"Love Token"
"Cologne Bottle"
"Perfume Bottle"
**Steps to reproduce the problem**:

1.  Go to any Innkeeper in any Major City or the ones put in the gyazo link.
2.  Open their option of "Let me browse your seasonal fare."
3.  No items are shown to be sold.

**Source:**
Taken in game.

**Include Screenshots from the issue if necessary**:
https://gyazo.com/033cc6832bdbbc6f74e62352adc6532c  (List of Innkeepers that should sell said items. 
https://gyazo.com/9582fd04e598548f0c1b41aa16e05148 (Showing of no items being sold)
https://classicdb.ch/?item=21815 (Love Token)
https://classicdb.ch/?item=21829 (Perfume Bottle)
https://classicdb.ch/?item=21833 (Cologne Bottle)

**Comment by Yharnstrom** [comment]
I confirm this. This is wonderful event. Make it work.

**Comment by JetHammer22** [comment]
Testing showed that even when there are love tokens in your inventory and you used cologne bottle, nothing works. The hearts pop up over NPC's heads, but you can't give love token to them because there is no option in dialogue menu.
Unfortunatelty, this is core mechanic of the entire event. 

Fix will be appreciated :)
