### ISSUE TITLE
Naxxramas - 4 horsemen - No reward chect

### ISSUE THREAD

**Issue by Shadowomen** [RetroWoW/RetroWoW#47]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Naxxramas
Currently. 23:30 12-06-2018 
Cleared 4 - horsemen
No loot chest.
Don't know why, that what we thought.
Aeal, Zmokaren, Darkliz, Tegyrius, and Shadowomen

**Expected behaviour**: Tell us what should happen instead
A loot chest should appear, with loot in it.

**Steps to reproduce the problem**:

1.  Engage 4 horsemen
2.  let the 2 melee die of some strage melee cleave damage
3.  3 person kill the bosses

**Include proofs for this behaviour**

It is hard to provide proof of something that is not there. For all you would care, we could already have looted it and the chest would have disappeared. you got only my word, and i tell you there is a issue. Look into this issue. Others might stumble across it aswell. 
Thx for a cool private server.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MrKelzo** [comment]
This happens when you try altloot.
