### ISSUE TITLE
Rare boss "Blind Hunter"

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#47]
**Description**: The rare boss Blind Hunter in rfk is currently never spawning, I was trying to tame him by running to where he should be spawned around 15 times and no sign of him. (Reset the instance with script)

**Current behaviour**: Creature is apparently missing

**Expected behaviour**: Should be in game

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:** http://db.vanillagaming.org/?npc=4425

**Comment by Soviethammer** [comment]
Been bugged on many other servers.
