### ISSUE TITLE
I accidentally bought gold for wrong character

### ISSUE THREAD

**Issue by themandevilhanzo** [RetroWoW/RetroWoW#471]
**Description**:
Im kind of new to the retrowow scene and i didnt know i had to choose a character to buy something on him so i just pressed checkout without realizing i had to choose a character:(
**Current behavior**: Tell us what happens
says above^
**Expected behavior**: Tell us what should happen instead
I was trying to buy it for the character Exosu but i bought it for my mage who is the person i didnt mean to send the gold and the pvp tokens too his name is Loliamfrostm
**Steps to reproduce the problem**:

1. Remove 50,000 gold and 2,000 pvp token's  from the Mage Loliamfrostm 
2. Give 50,000 gold and 2,000 pvp tokens To the paladin Exosu
3. ill be happy

**Source:**
me being stupid

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please open a ticket ingame if this isn't fixed yet.
