### ISSUE TITLE
PTR - Gurubashi Arena 20g and PVP token.

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#48]
**Description**:
Killing a player on the Gurubashi Arena gives you neither 20g nor PVP token.
**Current behavior**: Tell us what happens
Killing a player on the Gurubashi Arena gives you neither 20g nor PVP token.
**Expected behavior**: Tell us what should happen instead
It should award you with 20g (and possibly PVP token). Don't remember if it should award you with PVP token as well, but it does not right now.
**Steps to reproduce the problem**:

1. Go to Gurubashi arena and kill someone.
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Works fine, you don't get gold if the enemy player has the same IP address of yours
