### ISSUE TITLE
Banned for no reason

### ISSUE THREAD

**Issue by CrusterBrops** [RetroWoW/RetroWoW#486]
Hello, i have a problem with my account:

**Current behavior**: I can't played Wow Classic because my account is banned for RazA3n: Failed login Autoband

**Expected behavior**: When i was play in Wow Classic send me a message that my account has been temporarily suspended

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:** My account is CrusterBrops
![Sin título](https://user-images.githubusercontent.com/64567517/80664017-db55b500-8a52-11ea-8d2c-19ab3815536c.png)

**Comment by tara81** [comment]
You need to post in the forums under Ban Appeal.
