### ISSUE TITLE
Can't learn Smelt Elementium bars from Master elemental Shaper Krixix.

### ISSUE THREAD

**Issue by Buranyx** [RetroWoW/RetroWoW#488]
**Description**: 

**Current behavior**: Hello ! I tried to learn how to smelt Elementium bars from Master elemental Shaper Krixix in BWL. We went with a priest that did mind controlled him, but when I tried to right click on him, nothing happenend... I tried for weeks, everytime people are killing it, because they dont care, and the only time I could manage a group with nice people to help me out, I couldnt speak to him, and didnt learn it. 

**Expected behavior**: Well, Master elemental Shaper Krixix should have teached me how to craft elementium bars I guess, like it is supposed to be. 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:
![Screenshot 030520](https://user-images.githubusercontent.com/64737900/80916134-2de6e800-8d57-11ea-9fb1-897b2b9f6fd0.png)

**Comment by Funnie1** [comment]
The priest MC'ing krixix has to be the same faction as the character recieving the smelt elementium ability

**Comment by Buranyx** [comment]
We were both Undead... :(

**Comment by Buranyx** [comment]
Been fixed by Ossi, thank you very much I appreciate this :)
