### ISSUE TITLE
Spell registration

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#49]
**Description**: Often my spells (warlock pov) won't register. Lets say I cast a shadowbolt, it will just disappear, no dmg done, no resist, it will just disappear. Same thing happens with dots, they don't always register either.. however Dotimer addon will register it.

This is a quite new issue, since last patch or so.

**Current behaviour**: Spell disappears, neither hits or resists

**Expected behaviour**: Should either hit or resist

**Steps to reproduce the problem**:

1. Go enter a raid as a warlock and watch some of ur spells not registering (might be bugged for other classes too, I don't know)
2. 
3. 

**Source:**

**Comment by needmorgold** [comment]
dunno, as my experience is all ok about this.

**Comment by Bam27** [comment]
Could you provide video of this, or elaborate on a method of reproducing? I have yet to encounter this issue like you have described.

**Comment by xiaoxoxo** [comment]
Seems to happen quite abit in raid enviorments for me atleast, no problem on dummies. Any boss really.

**Comment by robinsch** [comment]
Please make a video with combat log open.
