### ISSUE TITLE
Banned with reason MB ?

### ISSUE THREAD

**Issue by Sharkoss** [RetroWoW/RetroWoW#491]
We have banned, me and my girlfriend with a reason MB?

Can you explain me is it forbidden to play with my girlfriend from home with same IP address ? 

We was in same Alterac Valley and from nothing we have banned both accounts, what is the reason ?

**Comment by Sharkoss** [comment]
still no answers from admins....

**Comment by tara81** [comment]
Sounds like MB means Multibox. (one user using multiple accounts outside of hyjal) You should post on the forums under Ban Appeals, and try to explain what you were both doing when you both got banned. Also , if you have any proof you both game together you would include that there.

**Comment by Sharkoss** [comment]
I understand. I have no idea how i can proof you the real situation that me and my wife got together in AV(she is new player, i had to explain her everything) and in this time looks like i do mb because we are played from same ip (witch is home wifi network). But still i cant prove it and our accounts got banned already for more than 4 months. If you think it is enough punishment for nothing please unbann my acc Saskoy with chars: Sharkus , Sharkas.
Thank you.
