### ISSUE TITLE
naxx issue

### ISSUE THREAD

**Issue by Chuckwar** [RetroWoW/RetroWoW#5]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Gluth's spawned adds has 50k hp, which is too much, in retail 40 men it was 100k hp each add, 50k hp is equivalent to 20 men. as of right now, it's unkillable

Anub spawns 25 scraps in p2, which is too much as well. very very difficult to kill. 

**Expected behaviour**: Tell us what should happen instead
gluth: it would be reasonable to reduce add hp to 10k and nerf it's damage little bit
Anub: reduce scraps to 10 or 15.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MrKelzo** [comment]
Scarabs spawn only when the guards are killed.

I bet you also don't know when you should kill zombies..
