### ISSUE TITLE
[Warlock] Ritual of Doom: Doomguard is lost after zoning out or relog

### ISSUE THREAD

**Issue by codehoge** [RetroWoW/RetroWoW#501]
**Description**:
Ritual of Doom: Doomguard is lost after zoning out

**Current behavior**: Tell us what happens
The spell **Ritual of Doom** (https://classic.wowhead.com/spell=1854) summons a Doomguard which disappears if you are summoned / enter or leave instance / enter or leave battleground / logging out.

**Expected behavior**: Tell us what should happen instead
1. Just like other warlock pets, the Doomguard should be preserved wherever the warlock changes instance, logs out or accepts a summon.

**Steps to reproduce the problem**:
1. Summon a Doomguard via Ritual of Doom.
2. With your new Dommguard summoned, enter a battleground / enter instance / accept a world summon.
3. The pet disappears.

**Source:**
WoWhead: https://classic.wowhead.com/spell=18540

**Include Screenshots from the issue if necessary**:

**Comment by VovremyaRetroWoW** [comment]
Same post (https://github.com/RetroWoW/RetroWoW/issues/504) but in other words. Not a bug.
