### ISSUE TITLE
[Warlock] Enslave Demon: Enslaved demon is lost after chaning instance

### ISSUE THREAD

**Issue by codehoge** [RetroWoW/RetroWoW#504]
**Description**:
Enslaved demons by Warlocks should not disappear after changing instances.

**Current behavior**: Tell us what happens
All enslaved pets become bugged and do not follow the warlock when it changes instance.

**Expected behavior**: Tell us what should happen instead
The Doomguard should be able to be buffed and healed just like any other pet.

**Steps to reproduce the problem**:
1. Enslave a demon with a warlock.
2. Travel with portal from Hyjal to Stormwind.
3. The pet is gone.

**Source:**
Source: https://vanilla-wow.fandom.com/wiki/Enslave_Demon

**Include Screenshots from the issue if necessary**:

**Comment by VovremyaRetroWoW** [comment]
Your source does not contain proofs that it's possible. It says it works like Mind Control. Mind controlled npc will never be teleported with you. Not a bug 99%.
