### ISSUE TITLE
[Warlock] Ritual of Doom: Not affected by cooldowns reset

### ISSUE THREAD

**Issue by codehoge** [RetroWoW/RetroWoW#505]
**Description**:
Unlike all other Warlock spells, the cooldown of Ritual of Doom is not reset when you enable the duel mod.

**Current behavior**: Tell us what happens
Unlike all other Warlock spells, the cooldown of Ritual of Doom is not reset when you enable the duel mod.

**Expected behavior**: Tell us what should happen instead
The cooldown should be reset just like all other normal warlock spells.

**Steps to reproduce the problem**:

1. Use Ritual of Doom and trigger the cooldown.
2. Use Duel mod to reset cooldowns.
3. Ritual of Doom is still not reset. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by VovremyaRetroWoW** [comment]
It does not need in pvp, it's called duel mod, not pls reset all mine cd.
