### ISSUE TITLE
PTR - Getting instantly attacked by the guard after using the portal of the opposing faction in Hyjal.

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#51]
**Description**:
Using the portal of the opposing faction in Hyjal mall makes you attacked by the guard right after the loading screen.
**Current behavior**: Tell us what happens
When you use:
- Orgrimmar, and Undercity portals as Alliance you get instantly attacked by the guard right after the loading screen.
- Stormwind, Ironforge and Darnassus portals as Horde you get instantly attacked by the guard right after the loading screen.

**Expected behavior**: Tell us what should happen instead
Players should not be attacked by the guards instantly after using the portal of the opposing faction (that's how it works on live).
T**he most meaningful portal is Orgrimmar portal,** because it is being used daily by the Alliance players during world bosses runs.

**Steps to reproduce the problem**:

1. User portal to the city of the opposing faction.
2. 
3. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/76588473/210188540-d4d307f7-4c39-4e2e-af85-fb304fb85574.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/76588473/210188288-26dcc595-248f-49bf-b1a5-b0230b993952.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/76588473/210188336-68e57c17-0485-4694-8107-64c2f96faeb3.png">

**Comment by MrKelzo** [comment]
This is actually blizzlike, when you enter a enemy city, guards will spawn/start attacking

**Comment by Dovlatoff** [comment]
> This is actually blizzlike, when you enter a enemy city, guards will spawn/start attacking

Of course, this is blizzlike, but it works differently on live, that's why I reported it. Thought that you disabled this thing on purpose on live version long ago.
