### ISSUE TITLE
Clearing or changing target removes combo points for Rogues

### ISSUE THREAD

**Issue by RealPorridge** [RetroWoW/RetroWoW#510]
Description: As titled.

Current behavior: As titled.

Expected behavior: Combo points should not disappear from a target when changing or clearing target, and any combo points gained should stay on the target when selecting that target again.

Steps to reproduce the problem:

1. Please
2. Fix
3. This <3

Source: Me (Porridge, rogue), and countless hours of gathering combo points on a target, switching to another target to blind it, and switching back to the combo pointed target to find them all gone.

Include Screenshots from the issue if necessary: None

**Comment by VovremyaRetroWoW** [comment]
It's blizzlike behavior since patch 1.4.0 until 2.0.3. Not a bug.
Source: https://vanilla-wow.fandom.com/wiki/Combo_point
