### ISSUE TITLE
Banned IP for Advertising? When I was just looking for someone to play with me on a blizzlike server?What's wrong with you?

### ISSUE THREAD

**Issue by Noksyne** [RetroWoW/RetroWoW#511]
**Description**:

**Current behavior**: Tell us what happens
Banned IP for Advertising? When I was just looking for someone to play with me on a blizzlike server? What's wrong with you?
**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by VovremyaRetroWoW** [comment]
Oh, cmon. It's bug tracker only. Go on forum pls.
