### ISSUE TITLE
Wow forum login not working

### ISSUE THREAD

**Issue by AppleSauce4** [RetroWoW/RetroWoW#518]
**Description**:
Login on retrowow forum not working. Getting the error Authorization code mismatch. Are you accessing this function correctly? Please go back and try again.
**Current behavior**: Whenever i try to login i get the error message.

**Expected behavior**: Tell us what should happen instead (It should login ;-)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:
![Bug](https://user-images.githubusercontent.com/69209884/89731675-2ebfa200-da49-11ea-9362-8bf9b6258f78.JPG)

**Comment by tara81** [comment]
Forums have not been working for almost 3 weeks. Players cannot report hackers, cheaters, or do ban appeals on the forums.

**Comment by AppleSauce4** [comment]
Yeah indeed still not able to do login i wanted to do it for a ban appeal, but i just made a new account since it's not being fixed sadly.
