### ISSUE TITLE
PTR- WSG battle ground buffs respawn timers

### ISSUE THREAD

**Issue by kurtosmurtos** [RetroWoW/RetroWoW#52]
**Description**: The BG buffs in WSG, Berserk, and Restoration have very strange respawn timer on the PTR compared to the Live server

**Current behavior**: The BG buffs in WSG, Berserking( https://classicdb.ch/?spell=24378) zerk, Speed (https://classicdb.ch/?spell=23451) and Restoration , Leaf (https://classicdb.ch/?spell=23493) have very strange respawn timers on the PTR compared to the Live Server. The leaf has a 20 second, the most obvious and biggest bug, zerk has a 2 minute (+-a few seconds) and speed has 2 minutes and ~30 seconds. While on the Live server all of the 3 boosts have a 3 minute cooldown.

**Expected behavior**: All of the 3 battle ground boosts should have a same cooldown. The exact information is hard to find because there is no source that clearly states the numbers. To keep the gameplay what it was the and safest solution is to set the respawns to 3 minutes like it is on the Live server.

**Steps to reproduce the problem**:

1. Join WSG and pick the the Leaf.
2. Notice it spawns after exactly 20 seconds.  Set a stop watch to measure.
3. Set the stopwatch for the other 2 buffs/effects.
4. Compare with the live server 

**Source:**
The Boots of Speed now have a random spawn timer between 2 and 3 minutes, and the effect duration has been lowered to 10 seconds. This is taken from https://wowwiki-archive.fandom.com/wiki/Patch_1.5.0. There do not seem to be any mentions of the other too boosts in any other vanilla patch note. Which could be because all the other boosts had the same respawn timer.

**Include Screenshots from the issue if necessary**: The time difference is the respawn timer. I captured the times when I took and when the the buffs respawned. Some are a few seconds off but the case is perfectly clear. 
![Screenshot (228)](https://user-images.githubusercontent.com/112797709/210235410-d81e98d6-55f7-4921-9df1-cd882e64e7e0.png)
PTR, taking Zerk.
![Screenshot (229)](https://user-images.githubusercontent.com/112797709/210235488-43e195cf-7186-424d-ad62-ea47158a1c99.png)
PTR, zerk respawn. ~2 minutes
![Screenshot (230)](https://user-images.githubusercontent.com/112797709/210235564-aa24b9ba-eea9-4879-ad62-ba07ca1e74bd.png)
PTR, taking speed.
![Screenshot (231)](https://user-images.githubusercontent.com/112797709/210235628-da406ce3-b9fd-46de-9144-0d8db9f8c89e.png)
PTR, speed respawn. Respawn 2 minutes and 30+ seconds.
![Screenshot (232)](https://user-images.githubusercontent.com/112797709/210235751-ebccaf8a-c8b8-4e23-9dd2-52eebc0cd570.png)
PTR, taking Leaf
![Screenshot (233)](https://user-images.githubusercontent.com/112797709/210235861-afeaef04-2b9f-40e0-914e-e2555cb8a7a9.png)
PTR, Leaf respawn 20 seconds. THIS IS THE THE BIGGEST ISSUE.
![Screenshot (236)](https://user-images.githubusercontent.com/112797709/210236159-d8c278cc-c1dc-453a-9d4a-5303ba409b95.png)
Live, taking speed
![Screenshot (237)](https://user-images.githubusercontent.com/112797709/210236301-d58e11ec-ef8d-45d4-aeb3-569686f8d2f5.png)
Live, Speed respawn. 3 minutes
![Screenshot (238)](https://user-images.githubusercontent.com/112797709/210236357-6c6ecdde-ac0b-4dca-8b2d-be30bd0c18f2.png)
Live, taking leaf
![Screenshot (239)](https://user-images.githubusercontent.com/112797709/210236411-3ae69491-9345-467f-90e0-0870b99efee2.png)
Live, Leaf respawn. 3 mintes
![Screenshot (240)](https://user-images.githubusercontent.com/112797709/210236468-ed1f50df-c5d4-4a53-98fd-671611d546d7.png)
Live. Taking zerk
![Screenshot (241)](https://user-images.githubusercontent.com/112797709/210236518-0bb5ce79-9c27-4f84-8c8c-58e379f8572c.png)
Live zerk respawn. I died and so was 15 seconds late. 3 minutes respawn

**Comment by MrKelzo** [comment]
Set to 3 min just like on live.
