### ISSUE TITLE
Undead Priest missing 2 skills

### ISSUE THREAD

**Issue by thebeardedT** [RetroWoW/RetroWoW#525]
**Description**: Made an undead priest and I'm missing touch of weakness and devouring plague.

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by VovremyaRetroWoW** [comment]
You know about this spells but dunno how to get them. I N T E R E S T I N G.

**Comment by tara81** [comment]
They are from the undead priest trainer . Under city.
