### ISSUE TITLE
Blue Pearls too rare

### ISSUE THREAD

**Issue by tara81** [RetroWoW/RetroWoW#529]
**Description**: Giant clams off the coast of the vile reef are supposed to have 100% drop rate of Blue Pearls. It is more like 25% on retro. There are also only 5 spawns , with one that cannot be opened (says target not in line of sight, is stuck under a coral reef. ) there are supposed to be 44 spawns on the vile reef. These are used in engineering, and obtaining engineering design “flash bombs” and are too rare to farm. 

**Current behavior**: Giant clams have a 25% drop rate of blue pearl. There are only 5 nodes.

**Expected behavior**: Giant clams should have a 100% drop rate of blue pearls. There should be more nodes. Wowhead says 44. 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
https://classicdb.ch/?item=4611#contained-in-object
