### ISSUE TITLE
Heart of Wyrmthalak not Proccing

### ISSUE THREAD

**Issue by AnnonDRose** [RetroWoW/RetroWoW#53]
**Description**: Heart of Wyrmthalak https://classicdb.ch/?item=22321 is supposed to proc on melee attack (like Darkmoon Card: Maelstrom)

**Current behavior**: It do not

**Expected behavior**: It do

**Steps to reproduce the problem**:

1. Equip Heart of Wyrmthalak
2. Attack for several minutes
3. Alas, it procs not

**Source:**
Machteld the paladin hitting a training dummy for several minutes

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/41470767-e791660a-70b1-11e8-8d16-5be0acae6fbd.png)
