### ISSUE TITLE
mage t3 6/9

### ISSUE THREAD

**Issue by needmorgold** [RetroWoW/RetroWoW#53]
mage t3 6/9 doesnt work as indeed
http://classic.openwow.com/item=22498

**Current behaviour**: now its puts debuff, but it immediately dissapear 

**Expected behaviour**: it must stay for 30 sec http://classic.openwow.com/spell=28771

**Steps to reproduce the problem**:

1. equip t3 mage set
2. ???
3. dont work

**Source:**

**Comment by robinsch** [comment]
```sql
UPDATE `spell_proc_event` SET `procEx`=262145 WHERE (`entry`=28744);

**Comment by robinsch** [comment]
No it's only working for one spell 🤣
