### ISSUE TITLE
Stuck in death

### ISSUE THREAD

**Issue by hareemaree** [RetroWoW/RetroWoW#534]
**Description**:

**Current behavior**: Tell us what happens
I died in MC raid and i rsge quit amd when i camw back i was still dead far awqy feom my corpse witch disallows me to rez

**Expected behavior**: Tell us what should happen instead
I should be alive

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by tara81** [comment]
That stinks. If you group with someone and they queue for wsg you should be able to res there. Or maybe you can try .go arathi command while dead?
