### ISSUE TITLE
curse of doom

### ISSUE THREAD

**Issue by jonyjones** [RetroWoW/RetroWoW#538]
**Description**:
curse of doom description say cannot affect player
**Current behavior**: Tell us what happens
i target a non player target, a pet, it say invalid target
**Expected behavior**: Tell us what should happen instead
pet arent player, they should be affected
**Steps to reproduce the problem**:
 1. roll lock
2. go target non player
3. curse of doom
4. and see message

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
It cannot be cast on players or their pets
https://classic.wowhead.com/spell=603/curse-of-doom#comments
