### ISSUE TITLE
druid t3 2/9

### ISSUE THREAD

**Issue by needmorgold** [RetroWoW/RetroWoW#54]
**Description**: must have chance to regen energy from each tick, now works only from initial cast
http://classic.openwow.com/item=22488
**Current behaviour**: now regen your energy only from initial hit

**Expected behaviour**: must have chance to get energy from each tick

**Steps to reproduce the problem**:

1. eq druid t3
2. ???
3. cast rejuv on self

**Source:** item tooltip

**Comment by robinsch** [comment]
UPDATE `spell_proc_event` SET `procEx`=262145 WHERE (`entry`=28716);

**Comment by Phocus26** [comment]
This appears to have been fixed?
