### ISSUE TITLE
Cenarion Salve Plant quester bug

### ISSUE THREAD

**Issue by roprzz** [RetroWoW/RetroWoW#540]
**Description**:
I cannot get the quest to get the cenarion salve plant

**Current behavior**: Tell us what happens
When I open the window with quests and "Please make me a Cenarion beacon", the window closes automatically, giving me no chance to grab the quest

**Expected behavior**: Tell us what should happen instead
Window should stay opened and user should be able to grab quest

**Steps to reproduce the problem**:

1. Go to Maybess Riverbreeze
2. Try to open window

**Comment by roprzz** [comment]
+ Same issue occurs with Juju's quester

**Comment by MrKelzo** [comment]
Works fine for me, try disable addons.
