### ISSUE TITLE
Horde: Flight Path Error

### ISSUE THREAD

**Issue by ybother123** [RetroWoW/RetroWoW#542]
**Description**: When taking the flight path from Orgrimmar to Nigel's Point, Desolace it instead takes your through the alliance theremore isle in duskwallow and kicks you off the flight path.

**Current behavior**: Tell us what happens
Flight path from orgrimmar to nigel's point, desolace takes you to theramore isle in duskwallow marsh and kicks you off the bat. As horde, being dropped off in alliance place is bad, you HAVE to hearth back to the mall lmao

Removed the other pre-made text because this is the issue lol, don't need to repeat myself more.

**Comment by ybother123** [comment]
Update:
Trying to get to Nigel's point from ANY flight master yields this from what I can tell. Spent the last few minutes trying it from feralas,thousand needles and crossroads

Why is theremore isle even a flightpath for the horde.

**Comment by ybother123** [comment]
https://youtu.be/GLQe_4KcK-E

Not sure why you closed this. It isn't fixed even after a year.

It was marked as an invalid report though I don't know why.
Also marked as Cannot reproduce though my video that I just made a year later clearly shows that its still not fixed.

**Comment by MrKelzo** [comment]
Hey thanks for the video, I couldn't reproduce it but will take a deeper look at it.

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/147129082-5bcb2235-a699-4d97-a1a3-8b49754aec84.png)

https://classic-wow-archive.fandom.com/wiki/Desolace

![image](https://user-images.githubusercontent.com/25086832/147129164-ed705d6c-403a-4c99-9be1-93ef8c1ff170.png)

Nijel's Point is an alliance flight path. I'm not sure how you got it but as you can see on the first picture I don't have it. Did you make use factionchange?

**Comment by ybother123** [comment]
No, I had never used a faction change back in the day and still haven't to this day.
:\

**Comment by ybother123** [comment]
Way back in the day was there an option to purchase (with donor points) all flight paths? My account is kind of old so maybe it was something that i was able to buy way back in the day and it just included that point or something.

**Comment by ybother123** [comment]
I just made a new character and you're correct its not on the new character, but it is on my 3 horde chars haha. Strange. You can mark as closed ill just deal with it on my 3 chars no biggy.

**Comment by MrKelzo** [comment]
We switched to a new core back mid 2018, that could be the reason if it was bugged on the old core in case you were playing back then

**Comment by MrKelzo** [comment]
Thanks for your time

**Comment by ybother123** [comment]
Yeah i was haha. You too. Cheers and happy holidays.
