### ISSUE TITLE
druid t3 6/9

### ISSUE THREAD

**Issue by needmorgold** [RetroWoW/RetroWoW#55]
**Description**: gives 50hp only from initial cast, must give hp from each tick also
http://classic.openwow.com/item=22488
**Current behaviour**: givese 50hp only from initial cast

**Expected behaviour**: must give 50hp from initial and from each tick of hot also

**Steps to reproduce the problem**:

1. eq druid t3
2. ???
3. cast regrowth

**Source:** druid t3 tooltip

**Comment by robinsch** [comment]
```sql
UPDATE `spell_proc_event` SET `procEx`=262145 WHERE (`entry`=28744);
