### ISSUE TITLE
Doomguard: Rain of Fire

### ISSUE THREAD

**Issue by sinerp** [RetroWoW/RetroWoW#558]
**Description**:
Doomguard spell is not working
**Current behavior**:
Nothing happens when press Rain of Fire on pet tab with enslaved Doomguard, nothing happens in combat when Rain of Fire is put on auto-cast
**Expected behavior**:
Spell should be usable, auto-cast should be working
**Steps to reproduce the problem**:

1. Summon Doomguard
2. Enslave summoned Doomguard
3. Try to cast Rain of Fire
4. Try to use pet's Rain of Fire while enslaved Doomguard is attacking target
5. Try to send enslaved Doomguard into attack with Rain of Fire auto-cast toggled on

**Source:**
N/A

**Include Screenshots from the issue if necessary**:
N/A

**Comment by MrKelzo** [comment]
Will be applied after next restart
