### ISSUE TITLE
Cant Skin Ony! :<

### ISSUE THREAD

**Issue by Scufd** [RetroWoW/RetroWoW#559]
**Description**: We looted all the items on both sides. No loot icon for Horde or Alliance but there is a skinning icon and it gives me the corpse must be looted error lol.

**Current behavior**: I cannot skin the dragon

**Expected behavior**: I should be able to skin the dragon

**Steps to reproduce the problem**:

1. Kill the dragon
2. Loot the items
3. Cant skin
2. 
3. 

**Source:**
?

**Include Screenshots from the issue if necessary**:

**Comment by AkOneVanilla** [comment]
Leave grup , relog ( you also need 315 skining for it ) , Also you can buy free onyxia cape from starter vendor.
