### ISSUE TITLE
PTR- WSG tunnels and other buildings that dismount 

### ISSUE THREAD

**Issue by kurtosmurtos** [RetroWoW/RetroWoW#56]
**Description**: Many building in the open world and Battlegrounds dismount players and prevent them from mounting.

**Current behavior**: Many building in the open world and Battlegrounds dismount players and prevent them from mounting. It would be best to give an example regarding some of the cases on the PTR WSG and AB. When arriving a top the horde tunnel, player cannot mount and get dismounted if they reach it while riding. The Alliance tunnel on the PTR does not have this issue (it is the same as it is on the live). The same can be said about the alliance zerk hut, and horde leaf hut. The AB LM same case. Other places like the entirety of the Gurubashi arena, Troll-like ruins all over the world, stones and such also dismount and prevent mounting. On the Live server none of this is the case. Player can mount and get to roofs, rocks etc on their mounts

**Expected behavior**: I am not sure if the current situation regarding building on the live server is a custom change by retro. However if the decision is to keep thing as it is on live, all of these buildings, especially the  Horde WSG tunnel and buildings should be fixed so that mounts could work on it . If the decision is to keep thing as they are on the PTR, it appears that the only exception is the Alliance tunnel.  In that case, it should be changed so that it also prevents mounting. The most important thing is fixing the tunnels the other building are less of a concern.

**Steps to reproduce the problem**:

1. Ride a mount to the Alliance tunnel in WSG on the PTR
2. Ride a mount to the horde tunnel tunnel in WSG on the PTR, notice getting dismounted
3. Compare with the live server.
4. visit the places on the screenshots

**Source:**

**Include Screenshots from the issue if necessary**: I will first include the WSG tunnel photos.
![Screenshot (242)](https://user-images.githubusercontent.com/112797709/210262882-96b8086f-0348-4148-a003-c3c7d4bf175a.png)
![Screenshot (243)](https://user-images.githubusercontent.com/112797709/210262900-e658511f-5b70-4de6-a240-6412db7a6a8d.png)
PTR- WSG horde tunnel. Cannot mount. Red text and pointer is on the mount.

![Screenshot (244)](https://user-images.githubusercontent.com/112797709/210263005-7a22d125-3be3-4a37-8ee0-ad9b1abebdf3.png)
![Screenshot (245)](https://user-images.githubusercontent.com/112797709/210263016-8c5d7bec-b487-459f-aa97-73401883cc47.png)
PTR- ALliance tunnel. Mounts work.
![Screenshot (246)](https://user-images.githubusercontent.com/112797709/210263139-4a24bdd9-a0fd-4fe3-bf1b-2206f028486a.png)
PTR- Alliance zerk hut. Cannot mount.
![Screenshot (247)](https://user-images.githubusercontent.com/112797709/210263311-2c3f6a6d-9c1d-41ce-a59c-44cfd1c437ad.png)
PTR- Horde resto hut. Mounts don't work.
![Screenshot (248)](https://user-images.githubusercontent.com/112797709/210263967-940c50ac-e339-4c3d-92d6-843e7477d36b.png)
PTR- AB Lumber Mill. Doesn't work. Works on Live. Same case is with the Gold Mine in Arathi Basin.
![Screenshot (255)](https://user-images.githubusercontent.com/112797709/210263473-a537bbae-fb51-4be1-9bd5-72dc958e800e.png)
Live- Alliance tunnel. Works. AGAIN, this works on the PTR too but the rest doesnt.
![Screenshot (256)](https://user-images.githubusercontent.com/112797709/210263516-3f871df2-e1f9-4fb2-9ed9-017e470720e5.png)
Live-horde tunnel. Works.
![Screenshot (254)](https://user-images.githubusercontent.com/112797709/210263554-972d968a-8406-45df-a955-f881e9b53e9a.png)
Live- Alliance zerk hut. Works 

Now some location on the PTR as more examples of building dismounting:
![Screenshot (250)](https://user-images.githubusercontent.com/112797709/210264076-78798276-17a4-4f1c-98e4-c9d1a0ca5c9d.png)
![Screenshot (251)](https://user-images.githubusercontent.com/112797709/210264092-d1eb315d-65d6-4c60-b49b-4082fb5fd602.png)
![Screenshot (252)](https://user-images.githubusercontent.com/112797709/210264113-aab26d5c-baaa-4dc4-9dd1-0a2e2870693a.png)
![Screenshot (253)](https://user-images.githubusercontent.com/112797709/210264144-b7feaf7a-aa2a-48dc-ae20-b956b15dd5d4.png)

Same places on Live Server with mounts:

![Screenshot (260)](https://user-images.githubusercontent.com/112797709/210264431-291df685-8c89-4e4a-a41f-879f5defc2de.png)
![Screenshot (261)](https://user-images.githubusercontent.com/112797709/210264441-73247ead-9776-4a68-9ab4-a663ee8d69d3.png)
![Screenshot (259)](https://user-images.githubusercontent.com/112797709/210264458-cf9d4b2a-a3aa-4a26-b5db-b3caee2d01d5.png)
![Screenshot (264)](https://user-images.githubusercontent.com/112797709/210264683-1068669c-89ec-44f9-928f-e846692ab957.png)

**Comment by kurtosmurtos** [comment]
If it is not a bug. Will the PTR situation stay when the merge comes?

**Comment by MrKelzo** [comment]
Tested on classic as well, not a bug, is blizzlike and will remain like that
