### ISSUE TITLE
warlock talent Improved Shadow Bolt crit eat 1st stack

### ISSUE THREAD

**Issue by needmorgold** [RetroWoW/RetroWoW#56]
**Description**: 

> Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 20% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.

http://db.vanillagaming.org/?spell=17803

**Current behaviour**:  when you crit with sb you will apply this debuff, but shadow bolt, that placed debuff, eats self placed debuff, i.e. there only 3 stacks of it, not 4

**Expected behaviour**:  you crit with sb and after it there must be 4 stacks of debuff, first crit, that who placed debuff doesnt counts and doesnt affected by imp shadow bolt debuff

**Steps to reproduce the problem**:

1. get talent
2. cast shadow bolt
3. look at debuffs

**Source:** talent tooltip

**Comment by Phocus26** [comment]
This has not been fixed.  Crits still generate 3 stacks.  I did notice however that Shadowbolt instantly aggros mobs when the cast completes instead of when the projectile hits them (this is not the case for all projectile attacks).

**Comment by MrKelzo** [comment]
@robinsch fix causing crashes

**Comment by Nemathegreatone** [comment]
http://prntscr.com/enjfwq

Still eating forth stack
