### ISSUE TITLE
Hunter range talent not working against players.

### ISSUE THREAD

**Issue by barfighter** [RetroWoW/RetroWoW#563]
**Description**:
Hunter range talent to increase range by 6 yrds not working

**Current behavior**: Tell us what happens
Only changes range for non-player targets. This happens in all bg's, effectively gimping a major class mechanic.

**Expected behavior**: Tell us what should happen instead
All shots should have 41 yrd range, not 35 against players. I should be able to out range all other casters, but I can't. In fact I have been out ranged by elemental shammys.

**Steps to reproduce the problem**:

1. make a hunter
2. Talent it to have the max range
3. try to attack a player at your max range and see if they can hit you at the same time.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by freshmurda** [comment]
Bump

**Comment by barfighter** [comment]
still broken :(

**Comment by barfighter** [comment]
Yep, still broken

**Comment by barfighter** [comment]
Still broken.

**Comment by MrKelzo** [comment]
Please follow the report guide, include spell name / link / source
