### ISSUE TITLE
Flamewrath weapon not scaling with spell power

### ISSUE THREAD

**Issue by dwarist** [RetroWoW/RetroWoW#568]
**Description**: Flamewrath weapon not scaling with spell power as it should
https://classic.wowhead.com/item=11809/flame-wrath#comments

**Current behavior**: the shield proc hits back for 10 damage and it doesnt scale with spell power

**Expected behavior**: spell power should scale 1:1 
https://www.reddit.com/r/classicwow/comments/m1clbd/does_the_wow_classic_version_of_flamewrath_still/

**Steps to reproduce the problem**: equip Flamewrath, get the proc via melee and watch the 10 damage return :( 

**Source:
Here a video that also confirms the 100% spell damage scaling
https://youtu.be/iH_HnGyFplI?t=30

and here a video from classic wow that shows it:
https://www.youtube.com/watch?v=xhm2L0-ADdc

**Include Screenshots from the issue if necessary**:

**Comment by dwarist** [comment]
bumped for hope :)

**Comment by MrKelzo** [comment]
its the shield reflect damage that scales with spell power 1:1

**Comment by mauricioreyes** [comment]
Hi Kelzo, yes, but i think it doesnt scale w spell damage in RW, can you confirm it or comment about it? Thanks

**Comment by mauricioreyes** [comment]
Here a screenshot of my combat log during a test, showing the reflect hits for only 10fire damage (weapon wielder sporting 350 spell damage)

<img width="677" alt="flamewrathtest" src="https://user-images.githubusercontent.com/1540025/147113118-bc572ec6-032d-48a4-b2ab-88c2edfef6d2.png">
)
