### ISSUE TITLE
Regalia of Undead Cleansing

### ISSUE THREAD

**Issue by Popsis** [RetroWoW/RetroWoW#57]
**Description**: I offer to completely remove this set from game , its out of control , everyone is abusing it . It scales with wands gives almost 200% damage. It scales insane with warlock corruption , syphon life and other spells.

**Current behaviour**: Increases wand Damage by 200% and insane damage increase on other spells , far far more then t3 items in thoses places.

**Expected behaviour**: It should scale like normal spell damage.

**Steps to reproduce the problem**: 
1. Equip that set 
2. test damage on mob
3. equip normal items with equal spell dmg

**Source:** Well... it's clearly fuked up

**Comment by robinsch** [comment]
On PTR.
