### ISSUE TITLE
Depth of view in battlegrounds is too low

### ISSUE THREAD

**Issue by Samb101** [RetroWoW/RetroWoW#583]
**Description**:

**Current behavior**: The current depth of view in battlegrounds is not blizzlike. It's the same depth than outdoors, we do not see players until being at ~100 yards. Outdoors depth and BG depth should be differents.

**Expected behavior**: We should see further in BG. It seems to be around ~160 yards.

**Source:**
https://www.youtube.com/watch?v=PyOPIHPECzo
2:27 : see the tauren on the kodo 
6:39 : see carefully the unit falling the gy
8:59 : see carefully the unit falling the gy

**Comment by Kelzior** [comment]
Its set to 180 yards for several years now

**Comment by MrKelzo** [comment]
Its set to 180 yards for several years now.

**Comment by Samb101** [comment]
Maybe i'm wrong about the numbers, but you don't see as further on RetroWow than the video I linked.
