### ISSUE TITLE
Gyrofreeze Ice Reflector & Hyper-Radiant Flame Reflector & Ultra-Flash Shadow Reflector

### ISSUE THREAD

**Issue by samrogueRW** [RetroWoW/RetroWoW#6]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Once you use Gyrofreeze Ice Reflector it does reflect the spells but it doesn't make you immune to AoE spells like "Nova" "Cone of cold"
**Expected behaviour**: Tell us what should happen instead
It should reflect the normal spells "1 target spells" but it should also make you immune to stuff like Nova/cone of cold and frostbite 
**Steps to reproduce the problem**:

1. duel a mage
2. pop Gyrofreeze Ice Reflector
3. let him cast spell like nova or cone of cold

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.
http://web.archive.org/web/20061215122310/http://www.thottbot.com/?i=37247
Quote: And to answer questions...

This is how these work. Any spell that is a single target spell hitting you will bounce back to the caster. That means frostbolt, frost shock, Icy enchants, and hunter's freezing traps (for example).

Anything that is a frost AoE will not bounce back, but you will be immune. This means frost nova, Cone of Cold, Blizzard, etc. So if a mage frost novas while i have this active, I will be immune, but it won't root the mage. However, if he frostbolts me, it will bounce off of me, hit him, damage him, and snare him.

Hyper-Radiant Flame Reflector should work the same for spells like "Blast wave" as well
Ultra-Flash Shadow Reflector should work the same as well for spells like Psychic Scream and other shadow AoE spells
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

SOURCE : http://www.wowhead.com/item=18634/gyrofreeze-ice-reflector#comments

**Comment by Bam27** [comment]
Source? You should provide a source, not list places where one can be found when investigated.

**Comment by samrogueRW** [comment]
@Bam27 http://www.wowhead.com/item=18634/gyrofreeze-ice-reflector#comments

**Comment by samrogueRW** [comment]
Since Bam find it without a real source, and since my text couldn't prove it... here is a guy that proved how they are supposed to actually work https://forum.elysium-project.org/topic/22508-gyrofreeze-ice-reflector-how-it-should-work/

**Comment by Bam27** [comment]
The patch notes this is referring to offers no indication as to what you're suggesting should happen. Please provide video evidence or blue post/patch notes referring to this behavior specifically. Closing this.

**Comment by ifyousayso** [comment]
Cool! Highest upvoted comment on the largest WoW site is not "proof" enough.
https://www.wowhead.com/item=18634/gyrofreeze-ice-reflector#comments:id=4615

I guess there's no point in reporting any bugs since they are ignored.
