### ISSUE TITLE
rocketboots malfunction ending bug while CC'd

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#60]
**Description**: Loss of control of character is removed when the malfunction finishes, 

**Current behaviour**: you are able to control your character once the malfunction ends, even though you are under the effect of another form of crowd control

**Expected behaviour**: you should still be unable to control your character

**Steps to reproduce the problem**:

1. use rocket boots and have them malfunction
2. get CC'd in some form (polymorph for example)
3. when the malfunction ends you will be able to control your character even though you are CC'd

**Source:**

**Comment by robinsch** [comment]
Duplicate.
