### ISSUE TITLE
Paladin talent Redoubt and Reckoning

### ISSUE THREAD

**Issue by Pinusmugo** [RetroWoW/RetroWoW#60]
**Description**: The paladin talents redoubt and reckoning does not work when /sitting or using X. 

**Current behavior**: Tell us what happens
Reckoning and Redoubt does not activate when a player attacks and you use /sit or X.  Using /sit or X should make the attacker crit on you and trigger the mentioned talents. It does not. 

**Expected behavior**: Tell us what should happen instead
As mentioned, when using /sit or X it should make the attacker crit on you and in turn generate reckoning and redoubt. 

**Steps to reproduce the problem**:

1. Take the paladin talents redoubt and reckoning.
2.  Get another player to attack you
3.  Use the command /sit or click X while the player attacks. 

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)
I played back in 2004-06 and redoubt + reckoning did get triggered by using the command /sit and clicking X back then. If redoubt and reckoning has been "fixed" on the PTR so it doesn't work that way then you have fixed something that is not faulty to begin with. 

Here is a video that shows how it should work (and as it currently does on the live version of retro, but not on the PTR). Pay attention to when the video is posted. 

https://www.youtube.com/watch?v=kuPEzEoexLI

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Google it, there is enough proof that this was patched

**Comment by kurtosmurtos** [comment]
It can clearly be seen on the video that not every hit from the lava spider was a crit and that it took way more than 4 or 5 hits (crits) to build up 4 stacks of reckoning. The same case is with redoubt duration.

**Comment by karatro** [comment]
mm I also checked if I could replicate what the video shows..spamming X until charges appear...but nothing happened, I would get crit when sitting but zero charges! This is not vanilla IMO, please fix it, thanks
