### ISSUE TITLE
PTR - reckoning does not work

### ISSUE THREAD

**Issue by skunkin** [RetroWoW/RetroWoW#61]
**Description**: paladin talent reckoning does not work

**Current behavior**: after you are the victim of a critical strike it does not give you an extra weapon swing

**Expected behavior**: should give extra swings per crit against you

**Steps to reproduce the problem**:

1.  spec into reckoning
2.  get crit
3. see that you dont get a stack for extra hits

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)

**Include Screenshots from the issue if necessary**:

**Comment by karatro** [comment]
did you sit to get the crit? if you did, PTR doesnt consider sitting as source of recknoning, crit happens but thats all

there is another post where there is a video from 2005 where the player spams 'x' and after several presses he gets the charges. This cannot be replicated in PTR at the moment, though

**Comment by skunkin** [comment]
I was normally being crit by the bots in WSG not through sitting. That was not giving out stacks (extra hits) towards reckoning

**Comment by karatro** [comment]
Oh then thats a potential bug. I assume you had 5/5 on reckoning, right? 

@MrKelzo , maybe this something that can be easily tested w bots? My own experience with NPCs around was that reckoning charges would happen when getting crit (without sitting) but didnt test with players

**Comment by karatro** [comment]
I tested it myself and i did get charges, but some others confirmed what you say...I dunno if all this is related to something else...in PTR I have serious issues with keeping my target...somehow I lose the target (feels like a hunter's FD)..
