### ISSUE TITLE
Priest: Benediction/Anathema quest.

### ISSUE THREAD

**Issue by Shmoke** [RetroWoW/RetroWoW#61]
**Description**: Benediction/Anathema quest "unavailable"?
 
**Current behaviour**: "Eris Havenfire" does not spawn or is missing?

**Expected behaviour**: Once a priest has the Eye of Divinity equipped, they receive a buff. (This works)
                                        This then enables the priest to see the NPC "Eris Havenfire" to begin the quest
                                        "The Balance of Light and Shadow"
**Steps to reproduce the problem**: 

1. Equip Eye of Divinity & The Eye of Shadow
2. Go to Eastern Plaguelands (17.6 , 14.1)
3. Eris Havenfire does not exist. (sadface)

**Source:**
Eris Havenfire: http://db.vanillagaming.org/?npc=14494

The Balance of Light and Shadow: http://db.vanillagaming.org/?quest=7622

**Comment by robinsch** [comment]
Removed because of internal reasons.

**Comment by Shmoke** [comment]
Is it possible to provide an explanation as to why it's been ignored? Spent a decent amount of time and put money into the server to support it and the devs for their hard work.. However, I feel a bit uneasy going forward if there is no active development being done to better the server. I understand you can purchase Benediction with gold but.. just like the Bindings, with enough time and effort can be earned. Always wanted the staff, so im passionate about fixing this so I can do the quest :)

**Comment by robinsch** [comment]
I fixed the quest some months ago and it was causing a crash after a period of time. But there is tons of other stuff to do with a higher priority. Not saying the quest will stay unavailable for ever, but currently there are other projects that needs to be done before.

**Comment by Shmoke** [comment]
Appreciate the answer. Pretty much, that was the answer I received from several players about the quest (regarding the crash). I understand prioritization and that it is not important. Was just hoping to keep it here for reference as I have not seen anything regarding it. Thanks again.
