### ISSUE TITLE
Savory Deviate Delight

### ISSUE THREAD

**Issue by RetroSiscon** [RetroWoW/RetroWoW#61]
**Description**:
Savory Deviate Delight no longer gives all of its buffs.

**Current behavior**: 
Savory Deviate Delight will only turn you into a pirate or ninja.

**Expected behavior**: 
There used to be several random effects from savory deviate delights.

Yaaarrrr (turns you into a pirate)
Flip Out (turns you into a ninja)
Oops (turns you into a pile of goo for 10 sec)
Rapid Cast (50% increase in cast speed for 2 mins)
Cowardice (causes random "Run Away" fear effect for 10 mins)
+50 Rage for warriors, +50 energy for rogues
Fake Death (identical to hunter feign)

**Steps to reproduce the problem**:

1. I ate a bunch of Savory Deviate Delights  :'(

**Source:**
Savory Deviate Delight - https://classicdb.ch/?item=6657
Yaaarrrr  - https://classicdb.ch/?spell=8221
Flip Out  - https://classicdb.ch/?spell=8219
Oops  - https://classicdb.ch/?spell=8223
Rapid Cast  - http://classicdb.ch/?spell=8215
Cowardice - https://classicdb.ch/?spell=8224
+50 Rage for warriors/+50 energy for rogues -https://classicdb.ch/?spell=8214 
Fake Death - https://classicdb.ch/?spell=8226

I am not 100% sure on the +50 rage/energy spell as I had to randomly type in numbers on classicdb to find most of the spells here.

**Comment by nono234** [comment]
This was removed at patch 1.6.0, source: http://wowwiki.wikia.com/wiki/Savory_Deviate_Delight **(Patch 1.6.0 (12-Jul-2005): All effects other than pirate and ninja transformations were removed.)**

**Comment by RetroSiscon** [comment]
It's a fun item though.
