### ISSUE TITLE
Account issues

### ISSUE THREAD

**Issue by kudejingcai** [RetroWoW/RetroWoW#62]
**Description**:My team mates and I just left our char in the NAXX at 4horse man the day before new core , when after replace core, we log online and kill the boss.But we cant loot the chest ,and its dispear soon with out looting. Now ,we kill this BOSS like 3-4times after new core ,we still cant loot the chest . But other ppl doing raid with us (who didnt put their char there like us) can loot .So we think this is the account problem, we hope we can get fix .Two of my account have the same issues.

**Current behavior**: We should can loot from the chest.

**Expected behavior**: It can be loot.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**My acc ID is "kudejingcai"and"kudejingcai1"

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Alt looting doesn't work. Play with your alt.

**Comment by kudejingcai** [comment]
but its not alt issues bro, the char we played even cant loot
