### ISSUE TITLE
Corrupted ashbringer bug

### ISSUE THREAD

**Issue by 484Hobobrine** [RetroWoW/RetroWoW#64]
i think more people noticed this but some features of the corrupted ashbringer are not working. and as these features are the main reason i bought the corrupted ashbringer, PLEASE fix this...

first of all, with the ashbringer equiped you should be friendly with the scarlet crusade but no: they are still attacking me.

second the special event that should start in scarlet monastery if the player has corrupted ashbringer did not start.

the player should be friendly with scarlet crusade, and the special event should have to start when someone with corrupted ashbringer goes in scarlet monastery.

**Steps to reproduce the problem**:

1. i did not dispelled the ashbringer effect so it should work
2. the only thing of corrupted ashbringer is that the argent dawn is attacking me if i come too close
3. it happens every time i enter the monastery (>10 times)

**Source:**
i don't know what you mean with this

**Comment by Rushor** [comment]
most of the event was scripted here https://github.com/TrinityCore/TrinityCore/issues/12666 (by me) and improved here https://github.com/azerothcore/azerothcore-wotlk/commit/e7582c9ac7de9da6919c2e1607322251a62d7d99

the reactionfix for the asbringer is following:

``´c++
diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index 785aaa3..0c9d3bb 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3156,6 +3156,13 @@ void SpellMgr::LoadDbcDataCorrections()
         spellInfo->EffectApplyAuraName[EFFECT_1] = SPELL_AURA_MOD_MOUNTED_AND_FLIGHT_SPEED_NOT_STACK;
         spellInfo->EffectBasePoints[EFFECT_1] = 14;
         break;
+            case 28282: // Ashbringer
+                spellInfo->Effect[2] = SPELL_EFFECT_APPLY_AURA;
+                spellInfo->EffectImplicitTargetA[2] = TARGET_UNIT_CASTER;
+                spellInfo->EffectApplyAuraName[2] = SPELL_AURA_FORCE_REACTION;
+                spellInfo->EffectMiscValue[2] = 56; // Scarlet Crusade
+                spellInfo->EffectBasePoints[2] = 4; // Friendly
+                break;
             case 31344: // Howl of Azgalor
                 spellInfo->EffectRadiusIndex[0] = EFFECT_RADIUS_100_YARDS; // 100yards instead of 50000?!
                 break;
```
