### ISSUE TITLE
Unable to summon infernal with pet out

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#65]
**Description**: Warlocks can't cast "Inferno" spell with a pet out.

**Current behaviour**: When trying to cast Inferno with a pet out, you will receive an error message stating "

**Expected behaviour**: Your pet should automatically be dismissed 

**Steps to reproduce the problem**:

1. Summon any warlock pet
2. Cast Inferno
3. You'll receive an error message that you already have a pet out and the cast will be canceled.

**Source:**
https://youtu.be/CPjngFs8dOg?t=8m21s

**Comment by Nemathegreatone** [comment]
You can summon infernal, but your pet is still not being dismissed, you also receive the message "You already control a creature", plus the summoned Infernal is flagged as "Enemy" creature to you, so the "Inferno Effect" hits you and all characters in the casting area, no matter if they are friendly or not.

**Comment by Nemathegreatone** [comment]
Summoning process works okay, but the Inferno is not attacking targets.
