### ISSUE TITLE
ONYXIA NEEDS WORK

### ISSUE THREAD

**Issue by matm2** [RetroWoW/RetroWoW#65]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. When onyxia is pulled her adds not only respawn but also join the fight and wipe groups.
2. Onyxia's adds should be dead like MC's adds (you wipe, walk back, no problem) with onyxia you wipe and clear adds over and over and over making the community unhappy.
3. In phase 3 she has a bug where her HP resets to full sometimes.
Just looking out for the server and community, cheers guys :)

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
I can't reproduce the issues listed.
