### ISSUE TITLE
"Random Enchantment"

### ISSUE THREAD

**Issue by Kelenestus** [RetroWoW/RetroWoW#67]
**Description**: Items purchased from the Mall vendors that come with a Random Enchantment come with no additional stats.

**Current behavior**: Tell us what happens
Flaming Band is an example. It gives +Fire Spell Damage and a Random Enchantment tag. When purchased, it only gives the Fire Damage. The same thing happens for any other item with said tags.

**Expected behavior**: Tell us what should happen instead
It should roll for, and include a random enchantment when purchased. I should be able to get a Flaming Band "of the Gorilla," or "of the Monkey," "of the Whale," etc....

**Steps to reproduce the problem**:
1. Go to Mall
2. Walk to vendors
3. Open vendor interface
4. Purchase item
5. Mouseover item
6. ????
7. Be disappointed

**Source:**
The game

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
It works fine to me
