### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by abdulm1** [RetroWoW/RetroWoW#68]
**Description**: when ever i logged in to my retro account i am asked to choose realm and after choosing the realm it show logging into game server and after some moments it again then asked me to choose realm.

**Current behaviour**: Tell us what happens
it is asking me again and again to choose realm.
**Expected behaviour**: Tell us what should happen instead
instead of asking about realm it must logged my account but it always ask me to choose my realm

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Nemathegreatone** [comment]
Open realmlist.wtf

set realmlist logon.retro-wow.com
set realmname "RetroWoW"

Save realmlist.wtf

**Comment by abdulm1** [comment]
My realmlist is already set to logon.retro-wow.com

**Comment by Nemathegreatone** [comment]
Please read once again what i have said.

You need to add both lines

set realmlist logon.retro-wow.com
set realmname "RetroWoW"


Simply copy both lines and add them into the file.

**Comment by abdulm1** [comment]
this does not solve the problem mate.

**Comment by MrKelzo** [comment]
Please download our client.
