### ISSUE TITLE
Quartermaster Miranda Breechlock Quests

### ISSUE THREAD

**Issue by tobin53** [RetroWoW/RetroWoW#69]
**Description**:
When you click on 2 of the quartermaster's quests, your game client crashes. The quests are as follows:
Epic Armaments of Battle - Revered Amongst the Dawn
Superior Armaments of Battle - Revered Amongst the Dawn
This isn't a big issue since I don't believe anyone is  trying to complete the quests, but just wanted to make you guys aware that there is a client breaking bug here.

**Current behaviour**: Tell us what happens
Causes your game client to crash when you click on the quests. 

**Expected behaviour**: Tell us what should happen instead
The quest should open up and allow you to accept them.

**Steps to reproduce the problem**:

1. Talk to quartermaster
2. Click on quests mentioned above
3. Watch game client crash

**Source:**
Tobinz

**Comment by MrKelzo** [comment]
I can't reproduce it.

**Comment by genoism** [comment]
I have the same issue. I was told by someone to clear the wtf and wdb folders and was able to pull up the quest rewards but cannot actually select an item and receive it. 
I did notice that after i select a reward item and click accept, the npc becomes no longer clickable unless I relog.
After communicating with her for the first time, attempting to complete the quest for the reward again causes a client crash - along with trying to view her regular inventory.
