### ISSUE TITLE
Shirt of Shadow Buff Removed On Mounting

### ISSUE THREAD

**Issue by Soletta4Haumea** [RetroWoW/RetroWoW#69]
**Description**:
The visual effect from [Shirt of Shadow] daily token quest reward is removed every time a character finishes casting a mount.

**Current behavior**: Tell us what happens
The visual effect is removed form character when mounting.

**Expected behavior**: Tell us what should happen instead
The visual effect should stay on at all times while the shirt is worn.

**Steps to reproduce the problem**:
1. Equip [Shirt of Shadow]
2. Use mount
3. Visual effect is lost
4. ** I have only tested it on [Sabre Tiger] & [Great Brown Kodo] as these are the only mounts my character has.

**Source:**
(Source to confirm how it works: Eg. info from Wowwiki, an old video as proof, comments from 2004-2006 etc)
This is a custom retro item and cannot be sourced from old databases.

**Include Screenshots from the issue if necessary**:
Video demonstrating bug reproduction steps.
https://www.youtube.com/watch?v=8gH6QCtpL28

**Comment by MrKelzo** [comment]
The aura still remains after mounting up, this is a client issue

**Comment by Soletta4Haumea** [comment]
I just downloaded a fresh client from the retro-wow website and logged in immediately after unzip without changing any settings or adding any addons and this problem still happened. Can you be more specific about how it is a client issue and what to do to fix?
