### ISSUE TITLE
Petrified Scarab is not working properly

### ISSUE THREAD

**Issue by kurtosmurtos** [RetroWoW/RetroWoW#70]
**Description**:  The item Petrified Scarab, https://classicdb.ch/?item=21685#comments, is not working properly. Th player keeps the resistance buff after activating and unequiping the trinket.

**Current behavior**: The item Petrified Scarab, https://classicdb.ch/?item=21685#comments, is not working properly. The player keeps the resistance buff after activating and unequiping the trinket. 

**Expected behavior**: Once the trinket is is used and if the player swaps Petrified Scarab for something else, the buff from the scarab. This is the case for for every on-use trinket  or item in the game. An example is a simple Spell power or AP trinket. These need to be kept in the same trinket slot from the moment they were used to retain their effects.

**Steps to reproduce the problem**:

1. Use Petrified Scarab
2. Unequip it
3. Notice the buff is still present 

**Source:**
https://classicdb.ch/?item=21685#comments
https://vanilla-wow-archive.fandom.com/wiki/Trinket
There are no comments suggesting that the item ever worked as it does on the live server. The screenshots will provide further information.

**Include Screenshots from the issue if necessary**:
![Screenshot (307)](https://user-images.githubusercontent.com/112797709/226612093-1476b6d3-a7e5-4f81-a95b-afdf4564b0b5.png)
Trinket used and still equiped.
![Screenshot (308)](https://user-images.githubusercontent.com/112797709/226612223-003d49f8-b147-4ff9-b744-70f73d47263b.png)
Scarab swapped yet the effect still remains

**Comment by MrKelzo** [comment]
Works as intended
