### ISSUE TITLE
Help with mail

### ISSUE THREAD

**Issue by Emrickon** [RetroWoW/RetroWoW#71]
**Description**:Not a bug but didn't see another way to contact a GM. I just accidentally hit return on a mail with a 20k token in it lol 

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Please open a ticket ingame.
