### ISSUE TITLE
Hunter Pet and player combat linked

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#72]
**Description**: When a hunter's pet gets into combat, it puts the hunter into combat.  And it shouldn't.

**Current behavior**:  When a hunter's pet gets into combat, it puts the hunter into combat.

**Expected behavior**: The hunter and their pet should have independent combat states.

**Steps to reproduce the problem**:

1. send pet to attack a target
2. observe combat state
3. 

**Source:**
I have submitted a ticket for this previously on the old core with retail vanilla video clips as evidence.

**Include Screenshots from the issue if necessary**:

**Comment by Sunqtt** [comment]
It seems pretty op to let your pet in combat to prevent the enemy to be in combat while you can regen freely.
The nostalrius team didn't "forget" that pet situation, it was a choice made by them as they think it is the blizzlike way; and they seem pretty sure about it as shown in this video:
https://youtu.be/YPsnRtXudxc?t=1m11s

If you have 1.12 videos of a pet not putting in combat then it is indeed a bug

**Comment by Sunqtt** [comment]
Btw, this is also why when you feign death, your pet automatically stops attacking; because the normal behavior of pet attacking puts the hunter in combat.
Blizzard creating that pet behavior occurs is one more element that pets put you in combat

**Comment by Phocus26** [comment]
I think this is something that was changed in later vanilla patches.  I’ve seen footage where their combat isn’t linked and where it acts like the Nost Clip (private serve footage is not a valid source).

That said, I can’t actually find a source that I know for sure is 1.12 where this is happening so I’ll close it for now.
