### ISSUE TITLE
Destroying Towers in AV does not despawn the associated Marshal

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#73]
**Description**: I don't know if this is intentional or not.

**Current behavior**: Destroying a tower doesn't despawn its associated Marshal

**Expected behavior**: Destroying a tower should kill the associated Marshal.

**Steps to reproduce the problem**:

1. Destroy tower
2. NPC doesn't despawn
3. 

**Source:**

http://wowwiki.wikia.com/wiki/Alterac_Valley

"Generals are guarded by several Marshals (Alliance) or Warmasters (Horde), and they can not be pulled separately. Each general starts with four, but each one is linked to one of the four towers and dies when the tower is destroyed. Each Warmasters and Marshalls add a stackable buff that increases damage and health by 25%, so the general begins with +144% health and +144% damage, which makes him very difficult to kill without any tower destroyed. "

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
It does.
