### ISSUE TITLE
Sheen of Zanza bugged / disabled

### ISSUE THREAD

**Issue by Doubleooseven** [RetroWoW/RetroWoW#74]
Sheen of Zanza is bugged / disabled

**Current behavior**: Unable to use consumable

**Expected behavior**: Should be able to use consumable

**Steps to reproduce the problem**:

1. Try use Sheen of Zanza
2. Realise its disabled 
3. cry

**Source:**
Ive played entirety of the relaunch of the official Classic blizzard servers for pass 4 years and use Sheen of Zanza like candy on the official blizzard classic servers and always carry one on me.
I still use them to this day on classic era. In real official blizzard classic server mages can solo aoe farm zg and have unlimited bijous,  In official classic real pvpers carried a Sheen of Zanza at all times.

https://classicdb.ch/?item=20080#reward-of
**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
It will remain disabled since players abused it in PvE in the past. Has been disabled for years.
