### ISSUE TITLE
Mage Frostbite applied too quickly

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#75]
**Description**: As soon as a frostbolt is cast, if frostbite procs the target is instantly rooted while the frostbolt is still in the air.

**Current behaviour**: As soon as a mage finishes casting a frostbolt, if frostbite procs the target is rooted.

https://youtu.be/6CTmoevsgIA?t=7m9s

**Expected behaviour**: The root from frostbite should be applied once the frostbolt hits the enemy

**Steps to reproduce the problem**:

1. Cast frostbolt until a frostbite proc occurs
2. 
3. 

**Source:**
https://youtu.be/4sj21TAmQ-M?t=5m32s
https://youtu.be/4sj21TAmQ-M?t=6m16s

**Comment by robinsch** [comment]
No, check Faxmonkey videos. Frostbite proced instantly on retail.

**Comment by Phocus26** [comment]
https://youtu.be/3O_pNDc73MM?t=1m51s

**Comment by Phocus26** [comment]
https://youtu.be/5frS6BjaiD8?t=55s

**Comment by Phocus26** [comment]
This shows it more clearly:
https://youtu.be/3O_pNDc73MM?t=5m41s

**Comment by robinsch** [comment]
15:32 shows a Frostbite immune on spell release rather then hit.

**Comment by Phocus26** [comment]
The clips from Even Stupider Mage Tricks were recorded in patch 1.11 so it would be tough to find something more recent than that.  I guess the proc is just calculated on cast but the root is not applied until the projectile contacts the target.

**Comment by Bam27** [comment]
if proc -> immune: display immune on cast; || not immune: root on projectile collision
