### ISSUE TITLE
Pet slow

### ISSUE THREAD

**Issue by Soviethammer** [RetroWoW/RetroWoW#76]
I saw a closed topic about pet slow, and it says fixed on live. But it's not.

When hunter is slowed, the pet is slowed.

**Comment by Phocus26** [comment]
Same if the hunter is CC'd

**Comment by xiaoxoxo** [comment]
and same for warlocks

**Comment by MrKelzo** [comment]
Will be applied after the next restart

**Comment by xiaoxoxo** [comment]
Still not fixed?

**Comment by Soviethammer** [comment]
Has it been a restart tho?

**Comment by xiaoxoxo** [comment]
Says fixed, but not working on server?
