### ISSUE TITLE
Immune to disarm gauntlets does not work

### ISSUE THREAD

**Issue by iurkel** [RetroWoW/RetroWoW#77]
**Description**: Immune to Disarm does not work (only tried in WSG (PVP) and Duels.

**Current behavior**: Im using Dark Edge axe, and Stronghold Gauntlets, which say they should make me immune to disarm. However warriors can still disarm me. Confirmed in duel vs another warrior.

**Expected behavior**: The gauntlets should make me immune to disarm. I dont want to use wep chain, instead i want to use these gauntlets.

**Steps to reproduce the problem**:

1. Equip Dark Edge of Insanity (with +25 agility.)
2. Equip Stronghold Gauntlets
3.  Duel a warrior who disarms you. Confirm that it goes through the gauntlets immune function.

**Source:**
Comments from 2004 in the thread below. Gauntlets considered BIS for PVP etc.
https://www.wowhead.com/classic/item=12639/stronghold-gauntlets#comments

**Include Screenshots from the issue if necessary**:
N/A

**Comment by MrKelzo** [comment]
![image](https://github.com/RetroWoW/RetroWoW/assets/25086832/6c15f311-4413-448f-9e18-412160031338)
