### ISSUE TITLE
Lost Character

### ISSUE THREAD

**Issue by forsakenheal** [RetroWoW/RetroWoW#79]
**Description**:
Not much to it, been off for about a year and came back to notice just about all my toons were gone.
**Current behavior**: Tell us what happens
Logged in and my toons were gone.
**Expected behavior**: Tell us what should happen instead
Log in and toons should be there.
**Steps to reproduce the problem**:

1. I would like my characters back.
2. Their names are Corpsescream and Corpsestench. 
3. Would like to have them back soon, hopefully y'all can get back to me.

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
I'm sorry no characters found.
