### ISSUE TITLE
Linkens Boomerang not working as intended

### ISSUE THREAD

**Issue by GeorgiGeorgievShett** [RetroWoW/RetroWoW#79]
**Description**:
Linkens boomerang trinket is not working as it is intended to
**Current behavior**: Tell us what happens
When using Linkens Boomerang it throws the boomerang upon casting and it only deals damage to the enemy. 
**Expected behavior**: Tell us what should happen instead
Linkens boomerang should not only deal damage to the enemy but it should either knock them down or disarm them (sometimes both)
**Steps to reproduce the problem**:

1. Equip Linkens Boomerang
2. Target an enemy and cast it
3. Result

**Source:**
Couldn't find a source to show this from old videos or forum posts only in recent ones in 2020.

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Works perfectly fine, it does known down the target (low chance). Tested and confirmed
