### ISSUE TITLE
Slidores Gryphon chilling in AV without being summoned 

### ISSUE THREAD

**Issue by Soulweavver** [RetroWoW/RetroWoW#8]
**Description**: On the AV Test Realm there is a 45k level 60 gryphon called Slidore's and he is not suppose to be there without being summoned

**Current behaviour**: Tell us what happens
He sits at the frostwolf graveyard not moving 
**Expected behaviour**: Tell us what should happen instead
Slidore's Gryphon will patrol between Tower Point and Frostwolf Graveyard, "if summoned successfully".
**Steps to reproduce the problem**:

1. Go into AV
2. Head into frostwolf graveyard
3. You will see him

**Source:**
Daedratics in-game report. Slade on test server

http://imgur.com/a/PNVbU

**Comment by robinsch** [comment]
```sql 
DELETE FROM `creature` WHERE (`guid`=54610);
