### ISSUE TITLE
Character Stuck

### ISSUE THREAD

**Issue by Eldiabolicus** [RetroWoW/RetroWoW#80]
Character Stuck on Retro Wow

I was farming Frostmaul E'ko in Frostwhisper Gorge (Winterspring).
When attacking a Frostmauler a felt thru the floor getting damage but did not die.
I try to use the Heartstone but it says cant do that while moving.
please can some Game Master unstuck me.
Character  = Alliance Warrior 
Name = Rooie

Thank you.

**Comment by Phocus26** [comment]
This is not a place for GM tickets.
