### ISSUE TITLE
Frost Trap LoS Bug

### ISSUE THREAD

**Issue by Senexity** [RetroWoW/RetroWoW#82]
**Description**: Frost Trap

**Current behavior**: My frost trap does not work and disappear if the enemy stepping on it is not in my line of sight.

**Expected behavior**: My frost trap should work when the enemy is stepping on it, irrespective of whether he is in my line of sight or not. Expected behavior of the frost trap should be similar to the freezing trap's one (_i.e._ no line of sight requirement).

**Steps to reproduce the problem**:

1. Cast frost trap.
2. Get out of line of sight of the enemy.
3. Enemy steps on the frost trap.
4. The frost trap does not work and disappear.

**Source:**
No line of sight requirement mentioned anywhere on internet. Also, freezing trap does work without any line of sight requirement.
Still looking for evidence on old wow videos but it is kinda hard to find.

**Include Screenshots from the issue if necessary**: 
![Capture d’écran (64)](https://github.com/RetroWoW/RetroWoW/assets/133498850/f0a002af-1de3-4986-82d5-aa112f596917)
![Capture d’écran (65)](https://github.com/RetroWoW/RetroWoW/assets/133498850/0f3ee9ea-2efa-4872-b228-c1b1a76172cd)

**Comment by MrKelzo** [comment]
This is because of our own LoS changes.

**Comment by Senexity** [comment]
The bug is still occuring after the core update, should I create another thread? Many thanks.
