### ISSUE TITLE
Entangling roots are capped to 12sec in pvp

### ISSUE THREAD

**Issue by vanilla-wow-addons** [RetroWoW/RetroWoW#83]
**Description**:
Entangling roots are capped to 12sec in pvp no matter which rank, but pvp CC cap was introduced in 2.0.1
**Current behavior**: Tell us what happens
Cast max rank entangling roots on a player target = 12 sec root
**Expected behavior**: Tell us what should happen instead
https://thedruidsgrove.org/archive/wow/t-8592.html 
It should work more o less like a sap
**Steps to reproduce the problem**:

1. cast max rank entangling roots on a player
2. observe 
3. 

**Source:**
https://thedruidsgrove.org/archive/wow/t-8592.html 

**Include Screenshots from the issue if necessary**:

**Comment by MrKelzo** [comment]
Where do you get that info? It's not even 12 sec, it does break by heartbeat

**Comment by vanilla-wow-addons** [comment]
So did you ever get full duration root of 18 seconds (rank 3) on a enemy player? 
For reference I got full sap duration quite often.
