### ISSUE TITLE
Nerf Golemagg/Majordomo dmg

### ISSUE THREAD

**Issue by Spriest2** [RetroWoW/RetroWoW#86]
nerf golemagg and adds dmg and majordomo fireaoe dmg its insane. ragnaros is doable

**Comment by MrKelzo** [comment]
Golemagg + Adds are nerfed. "majordomo fireaoe dmg its insane" is not a valid report. Follow this format: https://github.com/RetroWoW/RetroWoW/blob/master/issue_template.md
