### ISSUE TITLE
duel's dosen't resets CD's

### ISSUE THREAD

**Issue by hamrogue** [RetroWoW/RetroWoW#89]
**Description**:...

**Current behavior**: Tell us what happens when i duel ppl it should resets the CD right but that's not what is happing at the 1st it was good but now it's not working , i tryed typing .duel mode on but it says Incorrect value , use in or off ! , what ! 
i used on but still can u fix this issue please cuz it's so annoying with duel and BG also thank you...

**Expected behavior**: Tell us what should happen instead it should resets !

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by xiaoxoxo** [comment]
It's .duelmod on
