### ISSUE TITLE
PTR - You don't get deserter debuff after /AFK from running bg.

### ISSUE THREAD

**Issue by Dovlatoff** [RetroWoW/RetroWoW#9]
**Description**:
You don't get deserter debuff after /AFK from running bg.
**Current behavior**: Tell us what happens
You don't get deserter debuff after /AFK from bg.
**Expected behavior**: Tell us what should happen instead
You should get "deserter" debuff after leaving the bg that is not finished.
**Steps to reproduce the problem**:

1. Join BG and /AFK out.
2. 
3. 

**Source:**

**Include Screenshots from the issue if necessary**:

**Comment by kurtosmurtos** [comment]
That is most likely just a PTR feature
