### ISSUE TITLE
Gouge and Sap

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/RetroWoW#90]
**Description**: Currently since maybe 2 months ago gouge has no dr at all, and It doesn't share dr with sap like it's intended to.

**Current behaviour**: Tell us what happens
Rogues can gouge, wait for stealth cd, cast a full duration sap, or spam gouge every 10 sec without it being on dr.

**Expected behaviour**: Tell us what should happen instead
Gouge should have dr and share it with sap.

**Steps to reproduce the problem**:

1.  Spam gouge every 10 sec
2.  Cast sap after gouge
3. 

**Source:**
Very reliable addon Nature Enemycastebar. http://tinypic.com/r/29bhibn/9
Another one: http://wow.gamepedia.com/index.php?title=Diminishing_returns&oldid=390493

**Comment by modnaros** [comment]
Confirmed. 

However, gouge, sap, and blind with randomly break with heartbeat so I think if the DR's are fixed, heartbeat should be as well.

**Comment by xiaoxoxo** [comment]
Rogues are way too op with this bug around, can reset fight whenever they want.. Should get fixed either way.

**Comment by modnaros** [comment]
If this is fixed and heartbeat isn't, it will make rogues gimped and only capable of 1v1 rofl

**Comment by Bam27** [comment]
Heartbeat does not affect gouge or blind on live server. 

There is a report opened on the subject of gouge/sap DR, I am looking for a source [youtube video circa 1.12, official blizzard statements, etc]  for sap -> gouge DR. 

Gouge DR will be fixed to apply to gouge.

**Comment by modnaros** [comment]
Oh by the way Bam, I noticed kidney shot is DRing on itself somehow.

**Comment by Bam27** [comment]
The DR timer for kidney shot starts the last moment it is applied; meaning that with a 20 second cooldown, it is still within the range of applying DR to itself with full combo points.

**Comment by modnaros** [comment]
How do you mean? As I understand it, the DR for kidney shot started the instant the debuff was applied, and that's reflected in DR timers. That's why I'm confused as to why it DR's on itself

**Comment by xiaoxoxo** [comment]
High priority I hope
