### ISSUE TITLE
Dimishing returns not correctly reducing CC duration

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#94]
**Description**: Long-duration crowd control effects (sap, polymorph, fear, freezing trap, ect..) last too long on subsequent applications to a target

**Current behaviour**: Currently a repeated CC effect applied to a target will last the following durations: 15 seconds, 10 seconds, 5 seconds.

**Expected behaviour**: As described in the 1.4.0 patch notes, it should be 15 seconds, 7.5 seconds, 3.75 seconds

**Steps to reproduce the problem**:

1. repeatedly fear, polymorph, sap or freezing trap a target
2. 
3. 

**Source:**
http://wowwiki.wikia.com/wiki/Patch_1.4.0

**Comment by MrKelzo** [comment]
Tested with polymorph

15s/8s/6s
15s/8s/6s
13s/8s/6s

**Comment by MrKelzo** [comment]
Lastest test with polymorph

+- 9/8/4 max
+- 6/8/4 max
+- 14/8/4 max
+- 16/8/4 max
+- 15/8/4 max

fixed
