### ISSUE TITLE
Hunter pets are not summoned upon res in battleground

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#96]
**Description**: Hunter pets are not summoned upon res in battleground

**Current behaviour**: Hunter pets are not summoned upon res in battleground

**Expected behaviour**: Spirit Guides in Battlegrounds should summon/resurrect your current pet when the Hunter is resurrected. 

**Steps to reproduce the problem**:

1. die in a bg
2. get resurected
3. 

**Source:**
http://wowwiki.wikia.com/wiki/Patch_1.5.0

**Comment by Nemathegreatone** [comment]
Pet's not being resurrected
