### ISSUE TITLE
Aegis of Preservation scales with +healing

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#97]
**Description**: Currently my priest heals for about 300 dmg PER hit.

**Current behaviour**: The healing from this item scales with +healing gear

**Expected behaviour**: This item should not be effected by +healing

**Steps to reproduce the problem**:

1. activate trinket
2. 
3. 

**Source:**

**Comment by robinsch** [comment]
```sql
INSERT INTO `spell_bonus_data` (`entry`, `comments`) VALUES (23781, 'Item - Aegis of Preservation');
