### ISSUE TITLE
Recking stacks are not properly reset and are generated from white hits

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#98]
**Description**: There are several conditions which should cause a player to lose their reckoning stacks which are not working.  A few excerpts from the following blue post reckoning FAQ from 2006:

Why didn't my Reckoning bomb go off?
The following things can cause you to drop your charges:

* Ending a Duel
* Mounting up (including gryphons)
* Autoattacking too early (e.g. from out of range)
* Switching Continents
* Switching Weapons
* Losing control of your character (Fear, Scattershot, Blind, Polymorph, Mind Control, etc.) 

You will however retain reckoning charges after casting Blessing of Protection on yourself or Divine Shield. 

Does reckoning work on both spell and melee crits?
Yes.

Can I sit down to force a crit and gain a charge?
Charges will not generate off auto attacks or npc attacks by trying to sit down and force a crit. However, ability crits from physical abilities such as Sinister Strike, Hamstring, Auto-shot, Aimed shot, etc will generate a charge if you're sitting.

Will the charges last through being stunned/stunlocked?
Assuming you leave your autoattack disabled, the charges will persist, and continue to be generated through stuns.

How long do charges last?
Forever, as long as they aren't knocked off by one of the afforemented reasons for Reckonings dropping above. If you heal for a minute and then release you'll see them all. If you duel a rogue friend, charge up, and then run across the map to find a horde to kill, they will likely evaporate. So, as long as you use it sensibly you shouldn't notice an issue. 

**Current behavior**: 
-Stacks are not reset upon starting auto attack out of range of your target
-Stacks are not reset on weapons swap
-Stacks are not reset upon mounting or taking a flight path
-Stacks are not reset upon continent swap
-Stacks are not reset upon TALENT RESET
-Stacks are not reset when character control is lost (with the exception of being stunned)
-Stacks are not reset when a duel ends
-White hits currently generate a stack

**Expected behavior**: 

-Stacks should be reset upon starting auto attack out of range of your target
-Stacks should be reset on weapons swap
-Stacks should be reset upon mounting or taking a flight path
-Stacks should be reset upon continent swap
-Stacks should be reset upon TALENT RESET
-Stacks should be reset when character control is lost (with the exception of being stunned)
-Stacks should be reset when a duel ends
-White hits should not generate a stack

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

http://blue.cardplace.com/cache/wow-paladin/1069149.htm

**Comment by xiaoxoxo** [comment]
Not sure about this, here is an old vid showing reck charges persist after mounting up:
https://www.youtube.com/watch?v=Kr_inDkNPBQ @22:18

**Comment by xiaoxoxo** [comment]
Can I sit down to force a crit and gain a charge?
Charges will not generate off auto attacks or npc attacks by trying to sit down and force a crit. However, ability crits from physical abilities such as Sinister Strike, Hamstring, Auto-shot, Aimed shot, etc will generate a charge if you're sitting. 
**Wrong**
https://www.youtube.com/watch?v=kuPEzEoexLI

**Comment by Phocus26** [comment]
Both of those look to be before patch 1.9 when Paladin's had their entire talent tree reworked.  I'll try to find other sources though.

**Comment by robinsch** [comment]
Core/Unit: Drop extra attack charges on death, duel complete, item remove, taxi path and teleporting

Please confirm other under this issue and reopen the issue if you found sources.

**Comment by Phocus26** [comment]
https://youtu.be/lQzxgkXRA1Y?t=5m12s

Reck reset on poly, fear, blind, scatter

**Comment by Phocus26** [comment]
Not sure what this means but... this was extracted from the ReckCounter addon from 2006:

function reckcounter_OnLoad()
    this:RegisterForDrag("LeftButton");
    this:RegisterEvent("VARIABLES_LOADED"); --Watch for initialization
    this:RegisterEvent("CHAT_MSG_SPELL_SELF_BUFF"); -- Watch for Reckoning procs
    this:RegisterEvent("PLAYER_ENTER_COMBAT"); -- Events below are for resetting ReckCounter
    this:RegisterEvent("PLAYER_LEAVE_COMBAT");
    this:RegisterEvent("PLAYER_DEAD");
    this:RegisterEvent("CHAT_MSG_COMBAT_SELF_HITS");
    this:RegisterEvent("CHAT_MSG_COMBAT_SELF_MISSES");

**Comment by robinsch** [comment]
Can you upload the addon somewhere?

**Comment by Phocus26** [comment]
https://wow.curseforge.com/projects/project-1032

**Comment by modnaros** [comment]
That gankadin video is indeed pre-1.9, it is correct that reckoning no longer procced from white hits after the nerf/hotfixes it endured due to players being able to walk into org, aggro a guard, use the sit-crit glitch and gain stacks and 1shot any player of their choosing.

I used to abuse that on retail on my paladin in vanilla

http://us.battle.net/wow/en/character/draka/Duncan/achievement#15234
I can provide proof of ownership if need be, I'd just have to update my wow client.

**Comment by MrKelzo** [comment]
Commit freezing server & enemy cannot move when he dies from reck

**Comment by robinsch** [comment]
Server doesn't freeze. Enemy can still move after a death caused by Reck.
