### ISSUE TITLE
Hunter Pets don’t stop attacking when casting feign death

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/RetroWoW#99]
**Description**: Hunter Pets don’t stop attacking when casting feign death.  This gives the appearance of feign death hugging and not removing you from combat.

**Current behavior**: when you cast feign death your pet continues to attack and will instantly put you back in combat.

**Expected behavior**: Your pet should stop attacking its current target and return to you.

**Steps to reproduce the problem**:

1. Send pet to attack
2. Cast feign death
3. Instantly get put back in combat

**Source:**
https://youtu.be/v5bIKjadBfw

14 mins 1 second

**Include Screenshots from the issue if necessary**:

**Comment by heinpz** [comment]
this isnt a bug u have to create a macro

**Comment by skunkin** [comment]
The timing is off even when you have the macro. It should cancel pet attack prior to casting feign death but it does not and sends hunters back into combat instantly.
